### ISSUE TITLE
Rescanning Filesystem halted if it encounters restricted video

### ISSUE THREAD

**Issue by mdajr** [tubearchivist/tubearchivist#206]
v0.1.3
Docker:latest

Used "Rescan Filesystem" to import videos from a previous install. After a couple hundred videos, the metadata scanner encountered an age restricted video that it failed to pull info for. This crashed the scanning thread. Subsequent attempts to scan fail at this video every time, meaning that there are videos left in the queue that have not (and can't) be scanned.

```
[2022-04-03 13:33:33,147: WARNING/ForkPoolWorker-4] index new videos
[2022-04-03 13:33:33,148: WARNING/ForkPoolWorker-4] vW8evni8Lj4: get metadata from youtube
[2022-04-03 13:33:34,302: WARNING/ForkPoolWorker-4] ERROR: [youtube] vW8evni8Lj4: Sign in to confirm your age. This video may be inappropriate for some users.
[2022-04-03 13:33:34,302: WARNING/ForkPoolWorker-4] vW8evni8Lj4: failed to get info from youtube
[2022-04-03 13:33:34,330: ERROR/ForkPoolWorker-4] Task home.tasks.rescan_filesystem[81a73fcc-2c25-4aa3-9f07-dcaa4e29d334] raised unexpected: ValueError('failed to get metadata for vW8evni8Lj4')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 205, in rescan_filesystem
    scan_filesystem()
  File "/app/home/src/index/filesystem.py", line 305, in scan_filesystem
    index_new_video(youtube_id)
  File "/app/home/src/index/video.py", line 470, in index_new_video
    raise ValueError("failed to get metadata for " + youtube_id)
ValueError: failed to get metadata for vW8evni8Lj4
```

I know there's an open issue about cookies that would workaround this, but this issue is specifically that the scanner should continue even if it encounters an error.

**Comment by bbilly1** [comment]
That's a tricky question. If it doesn't fail, how will you know which video file couldn't be imported? Now you know which file you need to take out of the media folder and run the task again.

I made it fail on purpose here, and I think it makes sense that it fails. That's an inherit limitation, if yt-dlp can't extract the info, Tube Archivist won't know what to do with the video and you'll need to handle that manually. I know, in this example there is a workaround with the cookie, but in general.
