### ISSUE TITLE
Reindex task failes if channel name has changed

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#211]
If the channel name has changed since last indexing, the reindex task won't find the media files because they are in a unexpected folder now.

```
tubearchivist  | [2022-04-07 12:00:00,090: INFO/MainProcess] Scheduler: Sending due task schedule_check_reindex (check_reindex)
tubearchivist  | [2022-04-07 12:00:00,095: INFO/MainProcess] Task check_reindex[7280f22e-859d-492a-b823-89338f1321cd] received
tubearchivist  | [2022-04-07 12:00:00,174: WARNING/ForkPoolWorker-4] reindexing 167 videos
tubearchivist  | [2022-04-07 12:00:00,175: WARNING/ForkPoolWorker-4] PH-2FfFD2PU: get metadata from es
tubearchivist  | [2022-04-07 12:00:00,179: WARNING/ForkPoolWorker-4] PH-2FfFD2PU: get metadata from youtube
tubearchivist  | [2022-04-07 12:00:01,947: WARNING/ForkPoolWorker-4] UCdkGV51Nu0unDNT58bHt9bg: get metadata from es
tubearchivist  | [2022-04-07 12:00:01,953: ERROR/ForkPoolWorker-4] Task check_reindex[7280f22e-859d-492a-b823-89338f1321cd] raised unexpected: FileNotFoundError(2, 'No such file or directory')
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/app/home/src/index/video.py", line 371, in add_player
tubearchivist  |     vid_path = self.build_dl_cache_path()
tubearchivist  |   File "/app/home/src/index/video.py", line 365, in build_dl_cache_path
tubearchivist  |     raise FileNotFoundError
tubearchivist  | FileNotFoundError
tubearchivist  | 
tubearchivist  | During handling of the above exception, another exception occurred:
tubearchivist  | 
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist  |     R = retval = fun(*args, **kwargs)
tubearchivist  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist  |     return self.run(*args, **kwargs)
tubearchivist  |   File "/app/home/tasks.py", line 139, in check_reindex
tubearchivist  |     reindex_old_documents()
tubearchivist  |   File "/app/home/src/index/filesystem.py", line 312, in reindex_old_documents
tubearchivist  |     handler.reindex()
tubearchivist  |   File "/app/home/src/index/reindex.py", line 211, in reindex
tubearchivist  |     self._reindex_single_video(youtube_id)
tubearchivist  |   File "/app/home/src/index/reindex.py", line 152, in _reindex_single_video
tubearchivist  |     video.build_json()
tubearchivist  |   File "/app/home/src/index/video.py", line 305, in build_json
tubearchivist  |     self.add_player()
tubearchivist  |   File "/app/home/src/index/video.py", line 376, in add_player
tubearchivist  |     all_files = os.listdir(channel_dir)
tubearchivist  | FileNotFoundError: [Errno 2] No such file or directory: '/youtube/VMware Cloud Native Apps'         
```

EDIT: Manual fix for now is rename the folder in question to match with the expected name in the "FileNotFoundError".

**Comment by bbilly1** [comment]
There is now a fix for that in v0.1.5.
