### ISSUE TITLE
Manual Import Error in v0.1.4

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#228]
Halted my ingestion of pre-archived videos to update to 0.1.4 and now cannot resume manual imports.  I'm assuming it's looking for the thumbnail?

```
[2022-04-16 00:33:36,624: ERROR/ForkPoolWorker-1] Task home.tasks.run_manual_import[ff8e8483-7c1a-4fe0-b3ec-05863e1ef245] raised unexpected: FileNotFoundError(2, 'No such file or directory')

Traceback (most recent call last):
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/home/tasks.py", line 154, in run_manual_import
all_videos_added = import_handler.process_import()
File "/app/home/src/index/filesystem.py", line 241, in process_import
vid_dict = index_new_video(youtube_id)
File "/app/home/src/index/video.py", line 600, in index_new_video
video.build_json()
File "/app/home/src/index/video.py", line 405, in build_json
self._process_youtube_meta()
File "/app/home/src/index/video.py", line 440, in _process_youtube_meta
base64_blur = ThumbManager().get_base64_blur(self.youtube_id)
File "/app/home/src/download/thumbnails.py", line 250, in get_base64_blur
img_raw = Image.open(file_path)
File "/root/.local/lib/python3.10/site-packages/PIL/Image.py", line 3068, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/cache/videos/u/U1j8ldnZ-gM.jpg'
```

**Comment by bbilly1** [comment]
Very unfortunate. Just pushed a quick fix for that. Pull the image again.
