### ISSUE TITLE
Embed thumbnails into media file - erroring out

### ISSUE THREAD

**Issue by fromnack** [tubearchivist/tubearchivist#231]
Hi there

Tried to run the above function and I'm getting an error in the logs:
`[2022-04-18 11:28:18,340: INFO/MainProcess] Task home.tasks.re_sync_thumbs[97022821-bf60-4333-90c9-7983d0cb8cf3] received
[2022-04-18 11:28:18,994: ERROR/ForkPoolWorker-4] Task home.tasks.re_sync_thumbs[97022821-bf60-4333-90c9-7983d0cb8cf3] raised unexpected: AttributeError("'bool' object has no attribute 'append'")
Traceback (most recent call last):
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/home/tasks.py", line 219, in re_sync_thumbs
video_list = handler.get_thumb_list()
File "/app/home/src/download/thumbnails.py", line 299, in get_thumb_list
pending.get_indexed()
File "/app/home/src/download/queue.py", line 61, in get_indexed
self.to_skip.append(video["youtube_id"])
AttributeError: 'bool' object has no attribute 'append'`

I only turned on the inclusion of thumbnail in the file later in my download process, so there are a load without them; but this error is occuring on the latest docker build on Unraid.

**Comment by bbilly1** [comment]
Thanks for bringing this to my attention. Something went wrong during refactoring.

**Comment by bbilly1** [comment]
Thanks for reporting. Fix is published in v0.1.5.
