### ISSUE TITLE
Handling errors gracefully

### ISSUE THREAD

**Issue by Zyzto** [tubearchivist/tubearchivist#238]
I had some issue where some videos gets deleted on my NAS, so when TA try to scan the folder it doesn't find them and completely errors out. there should be catch error and continue

```
[2022-05-01 19:07:30,324: WARNING/ForkPoolWorker-16] UCARXGIEG3aQHxaKIZG0osEg: get metadata from es

[2022-05-01 19:07:30,332: WARNING/ForkPoolWorker-16] {"_index":"ta_channel","_type":"_doc","_id":"UCARXGIEG3aQHxaKIZG0osEg","found":false}

[2022-05-01 19:07:30,333: WARNING/ForkPoolWorker-16] UCARXGIEG3aQHxaKIZG0osEg: scrape channel data from youtube

[2022-05-01 19:07:30,324: WARNING/ForkPoolWorker-16] UCARXGIEG3aQHxaKIZG0osEg: get metadata from es

[2022-05-01 19:07:30,332: WARNING/ForkPoolWorker-16] {"_index":"ta_channel","_type":"_doc","_id":"UCARXGIEG3aQHxaKIZG0osEg","found":false}

[2022-05-01 19:07:30,333: WARNING/ForkPoolWorker-16] UCARXGIEG3aQHxaKIZG0osEg: scrape channel data from youtube

[2022-05-01 19:07:31,202: WARNING/ForkPoolWorker-16] downloading 1 channel artwork

[2022-05-01 19:07:32,833: ERROR/ForkPoolWorker-16] Task home.tasks.rescan_filesystem[aa3e3f42-9ccc-42de-ab3f-23dfe4836985] raised unexpected: FileNotFoundError(2, 'No such file or directory')

Traceback (most recent call last):
File "/app/home/src/index/video.py", line 494, in add_player
vid_path = self.build_dl_cache_path()
File "/app/home/src/index/video.py", line 488, in build_dl_cache_path
raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/home/tasks.py", line 205, in rescan_filesystem
scan_filesystem()
File "/app/home/src/index/filesystem.py", line 305, in scan_filesystem
index_new_video(youtube_id)
File "/app/home/src/index/video.py", line 600, in index_new_video
video.build_json()
File "/app/home/src/index/video.py", line 408, in build_json
self.add_player()
File "/app/home/src/index/video.py", line 499, in add_player
all_files = os.listdir(channel_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/youtube/gellal_clip'
```

as well I have couple of videos that went private after some time so when trying to download them or resacan them it will error out.
as well I have some files that I personaly downloaded as I can't download (paid youtube) so when it scan them it will give me this.
```
[2022-05-01 18:59:03,421: WARNING/ForkPoolWorker-16] 9RP3CuZ5IOY: failed to get info from youtube

[2022-05-01 18:59:03,421: ERROR/ForkPoolWorker-16] Task home.tasks.rescan_filesystem[1c2aa140-e00b-40f3-83fc-010633774da8] raised unexpected: ValueError('failed to get metadata for 9RP3CuZ5IOY')

Traceback (most recent call last):
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/home/tasks.py", line 205, in rescan_filesystem
scan_filesystem()
File "/app/home/src/index/filesystem.py", line 305, in scan_filesystem
index_new_video(youtube_id)
File "/app/home/src/index/video.py", line 602, in index_new_video
raise ValueError("failed to get metadata for " + youtube_id)

ValueError: failed to get metadata for 9RP3CuZ5IOY
```

I think by default if error occur durring scan or download it's just need to be skipped

**Comment by bbilly1** [comment]
I don't think I understand, you might have to clarify. 
1. So you deleted some files from the folder structure? Then a rescan should also delete them from the index, so I'm not sure what's going on here.
2. That looks like a duplicate from #206, that error is supposing to happen, if yt-dlp cant get the metadata from YouTube, you'll have to deal with that manually.

**Comment by Zyzto** [comment]
> I don't think I understand, you might have to clarify.
> 
> 1. So you deleted some files from the folder structure? Then a rescan should also delete them from the index, so I'm not sure what's going on here.

I am not sure how it get deleted but one folder got deleted. by default I think it should skip any not found items. since if downloaded a video and the channel gets deleted after it will give an error.

> 2. That looks like a duplicate from https://github.com/tubearchivist/tubearchivist/issues/206, that error is supposing to happen, if yt-dlp cant get the metadata from YouTube, you'll have to deal with that manually.

this issue is not only because of filesystem rescan, it happend to me also because there's couple of video that get uploaded then deleted/privated after couple of mins/hours and I have my schedule that it's scan for new content than after 2h it will download them. I had this issue couple of times where I need to clean the queue.

I think overall every error should be ignored or delt with like deleting the item from queue or from index.

**Comment by bbilly1** [comment]
> I think overall every error should be ignored or delt with

That's easier said than done. :-) Error handling might be one of the hardest problems there is out there. If you just ignore all errors, then you won't see any bugs, or when things break somewhere, and you won't be able to fix it or handle it because you don't know what's broken, so that's in general not a good idea. Or if you straight up delete the item, because you think it's not there any more, are you really sure? or is it just a temporary networking issue? Then you end up deleting the whole index. You can easily see, that this is also not a good solution.

Errors can only be handled if you expect them. so:
1. This is working for me as intended, when deleting a folder from the filesystem, then run a filesystem rescan, this detects the difference and will also remove it from the index. So I wasn't able to reproduce that error, please provide steps on how to reproduce that. 
2. I think on this one we are on the same page, if yt-dlp can't get the metadata, you have to deal with that manually.
3. Now for the download queue, if the video is not available any more when you start the download, this will skip it and will continue with the next one. Then you can decide what you want to do, ignore it, delete it... So that should throw an error, as that is an expected and handled error, I think?

Then you can also make errors in handling errors...
