### ISSUE TITLE
"ValueError" When trying to add a channel URL that redirects to a different channel URL

### ISSUE THREAD

**Issue by Jerrk** [tubearchivist/tubearchivist#276]
I'm running into an issue when im trying to add a list of subscriptions

it seems that when you try to add a URL that redirects to a new channel name you will get an error.

specifically this error:
```
[2022-07-24 11:02:36,072: WARNING/ForkPoolWorker-8] processing: https://www.youtube.com/user/DFizzy
[2022-07-24 11:02:36,072: WARNING/ForkPoolWorker-8] ParseResult(scheme='https', netloc='www.youtube.com', path='/user/DFizzy', params='', query='', fragment='')
[2022-07-24 11:02:41,260: WARNING/ForkPoolWorker-8] failed to extract channel id from https://www.youtube.com/user/DFizzy
[2022-07-24 11:02:41,264: ERROR/ForkPoolWorker-8] Task home.tasks.subscribe_to[88a4097c-4804-40c2-903e-a837592e61f3] raised unexpected: ValueError()
Traceback (most recent call last):
  File "/app/home/src/ta/helper.py", line 206, in extract_channel_name
    channel_id = url_info["channel_id"]
KeyError: 'channel_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 227, in subscribe_to
    to_subscribe_list = UrlListParser(url_str).process_list()
  File "/app/home/src/ta/helper.py", line 141, in process_list
    youtube_id, id_type = self.detect_from_url(parsed)
  File "/app/home/src/ta/helper.py", line 177, in detect_from_url
    youtube_id = self.extract_channel_name(parsed.geturl())
  File "/app/home/src/ta/helper.py", line 209, in extract_channel_name
    raise ValueError from error
ValueError
```

in this case the url that i added "https://www.youtube.com/user/DFizzy" redirects to "https://www.youtube.com/user/DeeFizzy".

**Comment by bbilly1** [comment]
Thanks for reaching out on Discord. Need to implement some error handling for cases like that. Or maybe there is another workaround so that still can succeed. 

Thanks for reporting !

**Comment by bbilly1** [comment]
Thanks for reporting, channel name redirects are now handled n v0.2.1. Please update.
