### ISSUE TITLE
Handle SSL errors in thumbnail download for unstable connections

### ISSUE THREAD

**Issue by Jerrk** [tubearchivist/tubearchivist#281]
Running the "rescan subscriptions" task but it seems to run into an error after running for 7~ hours where it runs into a thumbnail that it is unable to download and then throws an error and stops the task.

```
[2022-07-26 05:13:08,008: INFO/MainProcess] Task update_subscribed[925392d9-c0e4-4f8d-aa6a-00bbd8b26f7d] received
[2022-07-26 06:20:30,485: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:20:56,564: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:21:22,687: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:21:48,791: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:22:26,068: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:22:52,094: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 06:23:18,122: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
...
[2022-07-26 14:03:31,004: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 14:03:57,514: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 14:04:28,776: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 14:05:10,370: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 14:05:36,670: WARNING/ForkPoolWorker-8] downloading 1 thumbnails
[2022-07-26 14:06:00,895: ERROR/ForkPoolWorker-8] Task update_subscribed[925392d9-c0e4-4f8d-aa6a-00bbd8b26f7d] raised unexpected: SSLError(MaxRetryError("HTTPSConnectionPool(host='i.ytimg.com', port=443): Max retries exceeded with url: /vi/Zz_BcdYpOHU/hqdefault.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))"))
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.ytimg.com', port=443): Max retries exceeded with url: /vi/Zz_BcdYpOHU/hqdefault.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 68, in update_subscribed
    pending_handler.add_to_pending()
  File "/app/home/src/download/queue.py", line 213, in add_to_pending
    thumb_handler.download_vid(thumb_needed)
  File "/app/home/src/download/thumbnails.py", line 178, in download_vid
    img_raw = self.get_raw_img(thumb_url, "video")
  File "/app/home/src/download/thumbnails.py", line 148, in get_raw_img
    response = requests.get(img_url, stream=True)
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.ytimg.com', port=443): Max retries exceeded with url: /vi/Zz_BcdYpOHU/hqdefault.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```

Ideally when running into this error wait and retry because of possible network instability or such.

**Comment by bbilly1** [comment]
Good idea, thanks for reaching out on Discord!

**Comment by bbilly1** [comment]
Thanks for reporting. With the thumbnail download refactoring in v0.2.1, there are now additional error handling in place to avoid these kind of situations.
