### ISSUE TITLE
RYD API hiccup results in download error

### ISSUE THREAD

**Issue by scumola** [tubearchivist/tubearchivist#283]
I'm using the latest docker-based deploy..  Things are working ok, but downloader crashes frequently.  Also, downloader is *slow*.  I have 3500-ish videos in the queue and I've only downloaded around 100 videos over the last 8 hours.  The downloader has crashed a couple of times and the only way I know is to look at the docker logs.  Re-starting the downloader seems to work, but there should be a heartbeat for the downloader in the UI so we know to re-start it, or just restart it automatically.  I did have to restart the tubearchivist container once because things were hung quite a bit.  The only other variation in my config is the media volume is an NFS mount instead of a docker volume, so I'm writing the completed videos over NFS (which is working great).  Anyway, here is the docker logs output for when the downloader dies.  Sorry I can't provide any more info.

[2022-07-26 19:04:48,340: WARNING/ForkPoolWorker-2] UCxzC4EngIsMrPmbm6Nxvb-A: get metadata from es
[2022-07-26 19:04:48,446: WARNING/ForkPoolWorker-2] xt1blE07xHY: get ryd stats
[2022-07-26 19:04:48,712: ERROR/ForkPoolWorker-2] Task download_pending[722fd284-3825-4195-a9aa-c0e29fc477f9] raised unexpected: UnboundLocalError("local variable 'parsed' referenced before assignment")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 89, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 650, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 441, in build_json
    self._get_ryd_stats()
  File "/app/home/src/index/video.py", line 610, in _get_ryd_stats
    result = ryd_client.get(self.youtube_id)
  File "/root/.local/lib/python3.10/site-packages/ryd_client/ryd_client.py", line 259, in get
    result = VoteGet(youtube_ids).process()
  File "/root/.local/lib/python3.10/site-packages/ryd_client/ryd_client.py", line 202, in process
    to_return = self._get_vote(self.youtube_ids)
  File "/root/.local/lib/python3.10/site-packages/ryd_client/ryd_client.py", line 234, in _get_vote
    return parsed
UnboundLocalError: local variable 'parsed' referenced before assignment
download pending

**Comment by bbilly1** [comment]
Looks like the *return youtube dislike* API has a hiccup, maybe you run into rate limiting issues? The scraping interval on the settings page can help with that. 

There is a locking mechanism, to prevent starting double download tasks, depending where the error happens, you'll have to restart the container to release the lock. In any case this needs better error handling there. 

For download speeds, obviously there are a lot of variables, but I have also encountered some videos, where yt-dlp can't extract the streams properly and then falls back to a slower download method which can't saturate the connection anymore. That's a yt-dlp internal error handling.

**Comment by scumola** [comment]
FYI, my scraping sleep interval was set to 5 seconds.  Nothing else scrape-wise was changed from the default.

Scraper died again over night, but the subscription scraper (set to auto for all crontab-like settings in my config) ran.

I'd still like an auto-restart in the downloader/scraper if that would be possible as a feature request or at least a heartbeat in the UI so I can manually restart it if it dies.

**Comment by scumola** [comment]
Happened again overnight.  Crawl halted.

**Comment by bbilly1** [comment]
Thanks for reporting. There are now additional error handling in place in v0.2.1.
