### ISSUE TITLE
Unable to download video due to subtitling issue

### ISSUE THREAD

**Issue by DeaeLunae** [tubearchivist/tubearchivist#288]
Video in question:

https://www.youtube.com/watch?v=kOClr_bew38

Running theory: 

The video on youtube has a valid selector for english as a subtitle. However, since there is no dialogue, there are no subtitles displayed. Possible zero-byte or actually non-existent file throwing an error?

Log:

```tubearchivist    | kOClr_bew38: downloading now
tubearchivist    | set task id: 5350d2e8-88c9-4f16-9eea-1457f7acaf0b
tubearchivist    | [2022-07-29 09:49:12,213: INFO/MainProcess] Task home.tasks.download_single[5350d2e8-88c9-4f16-9eea-1457f7acaf0b] received
tubearchivist    | [2022-07-29 09:49:12,215: WARNING/ForkPoolWorker-4] Added to queue with priority: kOClr_bew38
tubearchivist    | [2022-07-29 09:49:13,882: WARNING/ForkPoolWorker-4] kOClr_bew38: get metadata from youtube
tubearchivist    | [2022-07-29 09:49:14,784: WARNING/ForkPoolWorker-4] UCoxcjq-8xIDTYp3uz647V5A: get metadata from es
tubearchivist    | [2022-07-29 09:49:14,931: WARNING/ForkPoolWorker-4] kOClr_bew38: get sponsorblock timestamps
tubearchivist    | [2022-07-29 09:49:15,060: WARNING/ForkPoolWorker-4] kOClr_bew38: sponsorblock failed: Not Found
tubearchivist    | [2022-07-29 09:49:15,060: WARNING/ForkPoolWorker-4] kOClr_bew38-en: get user uploaded subtitles
tubearchivist    | [2022-07-29 09:49:15,168: ERROR/ForkPoolWorker-4] Task home.tasks.download_single[5350d2e8-88c9-4f16-9eea-1457f7acaf0b] raised unexpected: TypeError("'NoneType' object is not iterable")
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist    |     R = retval = fun(*args, **kwargs)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist    |     return self.run(*args, **kwargs)
tubearchivist    |   File "/app/home/tasks.py", line 119, in download_single
tubearchivist    |     VideoDownloader().run_queue()
tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
tubearchivist    |     vid_dict = index_new_video(
tubearchivist    |   File "/app/home/src/index/video.py", line 654, in index_new_video
tubearchivist    |     video.check_subtitles()
tubearchivist    |   File "/app/home/src/index/video.py", line 638, in check_subtitles
tubearchivist    |     handler.download_subtitles(relevant_subtitles=subtitles)
tubearchivist    |   File "/app/home/src/index/video.py", line 135, in download_subtitles
tubearchivist    |     parser.process()
tubearchivist    |   File "/app/home/src/index/video.py", line 196, in process
tubearchivist    |     for idx, event in enumerate(all_events):
tubearchivist    | TypeError: 'NoneType' object is not iterable

**Comment by bbilly1** [comment]
Excellent find, thanks for reporting!

**Comment by bbilly1** [comment]
Thanks for reporting. That is now dealt with in v0.2.1.
