### ISSUE TITLE
Redis full disk (tubearchivist running on docker)

### ISSUE THREAD

**Issue by scumola** [tubearchivist/tubearchivist#289]
tubearchivist is saying that Redis is having problems.  Tailing the logs on the redis container, it says disk full.  My docker host has plenty of disk space available.  The redis container is using a docker volume for storage as designated in the tubearchivist docs.

From the tubearchivist container logs:

```
[2022-07-29 12:00:54,045: CRITICAL/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/root/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/root/.local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/root/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/root/.local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/root/.local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/root/.local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/root/.local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/root/.local/lib/python3.10/site-packages/kombu/transport/redis.py", line 955, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-07-29 12:01:35,092: WARNING/ForkPoolWorker-2] ERROR: Postprocessing: Conversion failed!
[2022-07-29 12:01:35,094: WARNING/ForkPoolWorker-2] M3FIignUwHs: failed to download.
[2022-07-29 12:01:35,554: ERROR/ForkPoolWorker-2] Task download_pending[0799a0b0-bd61-4b8b-b95a-6e344d0408c9] raised unexpected: ResponseError('Error running script (call to f_c3f8721cbb97f72bc19e972846bd7aaf91901658): @user_script:6: @user_script: 6: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.')
Traceback (most recent call last):
  File "/app/home/tasks.py", line 89, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 170, in run_queue
    youtube_id = queue.get_next()
  File "/app/home/src/ta/ta_redis.py", line 128, in get_next
    result = self.conn.execute_command("LPOP", self.key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 95, in download_pending
    my_lock.release()
  File "/root/.local/lib/python3.10/site-packages/redis/lock.py", line 253, in release
    self.do_release(expected_token)
  File "/root/.local/lib/python3.10/site-packages/redis/lock.py", line 257, in do_release
    self.lua_release(keys=[self.name], args=[expected_token], client=self.redis)
  File "/root/.local/lib/python3.10/site-packages/redis/commands/core.py", line 5710, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/root/.local/lib/python3.10/site-packages/redis/commands/core.py", line 5095, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/root/.local/lib/python3.10/site-packages/redis/commands/core.py", line 5079, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_c3f8721cbb97f72bc19e972846bd7aaf91901658): @user_script:6: @user_script: 6: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.


```

From the Redis container logs:

```
267:C 29 Jul 2022 16:01:11.086 # Write error saving DB on disk: No space left on device
1:M 29 Jul 2022 16:01:11.183 # Background saving error
1:M 29 Jul 2022 16:01:17.004 * 100 changes in 300 seconds. Saving...
1:M 29 Jul 2022 16:01:17.013 * Background saving started by pid 268
268:C 29 Jul 2022 16:01:17.015 # Write error saving DB on disk: No space left on device
1:M 29 Jul 2022 16:01:17.114 # Background saving error
1:M 29 Jul 2022 16:01:23.035 * 100 changes in 300 seconds. Saving...
1:M 29 Jul 2022 16:01:23.036 * Background saving started by pid 269
269:C 29 Jul 2022 16:01:23.041 # Write error saving DB on disk: No space left on device
1:M 29 Jul 2022 16:01:23.138 # Background saving error
1:M 29 Jul 2022 16:01:29.058 * 100 changes in 300 seconds. Saving...
1:M 29 Jul 2022 16:01:29.059 * Background saving started by pid 270
270:C 29 Jul 2022 16:01:29.063 # Write error saving DB on disk: No space left on device
1:M 29 Jul 2022 16:01:29.159 # Background saving error
1:M 29 Jul 2022 16:01:35.088 * 100 changes in 300 seconds. Saving...
1:M 29 Jul 2022 16:01:35.088 * Background saving started by pid 271
271:C 29 Jul 2022 16:01:35.092 # Write error saving DB on disk: No space left on device
1:M 29 Jul 2022 16:01:35.189 # Background saving error
1:M 29 Jul 2022 16:01:41.015 * 100 changes in 300 seconds. Saving...
1:M 29 Jul 2022 16:01:41.017 * Background saving started by pid 272
272:C 29 Jul 2022 16:01:42.713 * DB saved on disk
272:C 29 Jul 2022 16:01:42.714 * RDB: 0 MB of memory used by copy-on-write


```

My docker host:

```
$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              796M  1.7M  794M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   30G   24G  4.2G  86% /
tmpfs                              3.9G     0  3.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  244M  1.6G  14% /boot
tmpfs                              796M  4.0K  796M   1% /run/user/1000


```

Crawl is hung at this point.  Awaiting helpful comments.  :)

**Comment by bbilly1** [comment]
I think the error message is clear. With only 6G left, you will run out soon. Available blocks is one indicator, but also available inodes. For an archival software, 30G will only get you so far, best through a few TBs at it. :-)

Also ES will freeze up soon: https://github.com/tubearchivist/tubearchivist#disk-usage

**Comment by scumola** [comment]
Why does redis get so much larger storage-wise?  I'm storing my actual videos off to an NFS share.  Is the meta-data *that large*?

**Comment by scumola** [comment]
I think that I found the issue. The volume tubearchivist_cache has an "import" folder that had some lingering multi-Gig videos in it.  Cleaning out that directory made everything happy again.
