### ISSUE TITLE
Issue when video title includes a percentage sign (%)

### ISSUE THREAD

**Issue by p0358** [tubearchivist/tubearchivist#301]
Apparently if the video title includes a percentage sign, it ends up saving these files in `/cache/download`:
```
# ls /cache/download/
XExFzCzwJek_RUS_SUB_1%_Flute_Skills_99%_Editing_Skills.mp4           mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.mp4
mIj6WZQOr2E_RUS_SUB_1%%_Beatbox_Skills_Vs_99%%_Editing_Skills_1.png  mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.webp
```

The `.png` file has double percentages in its name, and this causes issues with code that does not expect that:
```
2022-08-06 10:55:49.932787+00:00[2022-08-06 12:55:49,932: INFO/ForkPoolWorker-4] Task update_subscribed[80a3fc0b-ed91-4a35-a4fc-c8dbb5e102bf] succeeded in 147.67788130199915s: None
2022-08-06 10:56:05.983360+00:00mIj6WZQOr2E: downloading now
2022-08-06 10:56:05.985747+00:00set task id: ecb75ba6-25e0-40e6-96d5-147dfda25709
2022-08-06 10:56:05.987515+00:00[2022-08-06 12:56:05,986: INFO/MainProcess] Task home.tasks.download_single[ecb75ba6-25e0-40e6-96d5-147dfda25709] received
2022-08-06 10:56:05.992089+00:00[2022-08-06 12:56:05,991: WARNING/ForkPoolWorker-4] Added to queue with priority: mIj6WZQOr2E
2022-08-06 10:56:08.058000+00:00[2022-08-06 12:56:08,057: WARNING/ForkPoolWorker-4] WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png'
2022-08-06 10:56:08.061263+00:00[2022-08-06 12:56:08,061: WARNING/ForkPoolWorker-4] WARNING: Unable to embed thumbnails using AtomicParsley; AtomicParsley error: can't open /cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png for reading: No such file or directory
2022-08-06 10:56:08.063774+00:00[2022-08-06 12:56:08,063: ERROR/ForkPoolWorker-4] Task home.tasks.download_single[ecb75ba6-25e0-40e6-96d5-147dfda25709] raised unexpected: FileNotFoundError(2, 'No such file or directory')
2022-08-06 10:56:08.063812+00:00Traceback (most recent call last):
2022-08-06 10:56:08.063824+00:00File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
2022-08-06 10:56:08.063834+00:00R = retval = fun(*args, **kwargs)
2022-08-06 10:56:08.063845+00:00File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-08-06 10:56:08.063864+00:00return self.run(*args, **kwargs)
2022-08-06 10:56:08.063875+00:00File "/app/home/tasks.py", line 119, in download_single
2022-08-06 10:56:08.063889+00:00VideoDownloader().run_queue()
2022-08-06 10:56:08.063899+00:00File "/app/home/src/download/yt_dlp_handler.py", line 174, in run_queue
2022-08-06 10:56:08.063916+00:00success = self._dl_single_vid(youtube_id)
2022-08-06 10:56:08.063929+00:00File "/app/home/src/download/yt_dlp_handler.py", line 360, in _dl_single_vid
2022-08-06 10:56:08.063939+00:00success = YtWrap(obs, self.config).download(youtube_id)
2022-08-06 10:56:08.063950+00:00File "/app/home/src/download/yt_dlp_base.py", line 48, in download
2022-08-06 10:56:08.063966+00:00ydl.download([url])
2022-08-06 10:56:08.063978+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
2022-08-06 10:56:08.063991+00:00self.__download_wrapper(self.extract_info)(
2022-08-06 10:56:08.064001+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
2022-08-06 10:56:08.064018+00:00res = func(*args, **kwargs)
2022-08-06 10:56:08.064030+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
2022-08-06 10:56:08.064041+00:00return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
2022-08-06 10:56:08.064058+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
2022-08-06 10:56:08.064069+00:00return func(self, *args, **kwargs)
2022-08-06 10:56:08.064079+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
2022-08-06 10:56:08.064101+00:00return self.process_ie_result(ie_result, download, extra_info)
2022-08-06 10:56:08.064112+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
2022-08-06 10:56:08.064123+00:00ie_result = self.process_video_result(ie_result, download=download)
2022-08-06 10:56:08.064134+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2661, in process_video_result
2022-08-06 10:56:08.064152+00:00self.process_info(new_info)
2022-08-06 10:56:08.064164+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
2022-08-06 10:56:08.064175+00:00replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
2022-08-06 10:56:08.064193+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3406, in post_process
2022-08-06 10:56:08.064209+00:00info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
2022-08-06 10:56:08.064220+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
2022-08-06 10:56:08.064237+00:00info = self.run_pp(pp, info)
2022-08-06 10:56:08.064248+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3367, in run_pp
2022-08-06 10:56:08.064258+00:00files_to_delete, infodict = pp.run(infodict)
2022-08-06 10:56:08.064269+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
2022-08-06 10:56:08.064287+00:00ret = func(self, info, *args, **kwargs)
2022-08-06 10:56:08.064298+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
2022-08-06 10:56:08.064312+00:00return func(self, info)
2022-08-06 10:56:08.064321+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 218, in run
2022-08-06 10:56:08.064338+00:00os.replace(temp_filename, filename)
2022-08-06 10:56:08.064350+00:00FileNotFoundError: [Errno 2] No such file or directory: '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.temp.mp4' -> '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.mp4'
2022-08-06 10:56:55.543093+00:00mIj6WZQOr2E: downloading now
2022-08-06 10:56:55.544399+00:00set task id: a7be1210-c690-41d6-868e-7d9a65b83c90
2022-08-06 10:56:55.545331+00:00[2022-08-06 12:56:55,545: INFO/MainProcess] Task home.tasks.download_single[a7be1210-c690-41d6-868e-7d9a65b83c90] received
2022-08-06 10:56:55.548110+00:00[2022-08-06 12:56:55,547: WARNING/ForkPoolWorker-4] Added to queue with priority: mIj6WZQOr2E
2022-08-06 10:56:55.549615+00:00[2022-08-06 12:56:55,549: WARNING/ForkPoolWorker-4] Download queue already running.
2022-08-06 10:56:55.549778+00:00[2022-08-06 12:56:55,549: INFO/ForkPoolWorker-4] Task home.tasks.download_single[a7be1210-c690-41d6-868e-7d9a65b83c90] succeeded in 0.003894782996212598s: None
2022-08-06 10:57:06.057653+00:00Sat Aug  6 12:57:06 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /static/img/icon-sort.ae2068e12392.svg (ip 192.168.1.40) !!!
2022-08-06 10:57:06.057731+00:00Sat Aug  6 12:57:06 2022 - uwsgi_response_sendfile_do(): Broken pipe [core/writer.c line 655] during GET /static/img/icon-sort.ae2068e12392.svg (192.168.1.40)
2022-08-06 10:57:06.057751+00:00OSError: write error
2022-08-06 10:57:10.311537+00:00searching for: RUS SUB / 1% Beatbox Skills Vs 99% Editing Skills 1
2022-08-06 10:57:10.311620+00:00query words: ['rus', 'sub', '/', '1%', 'beatbox', 'skills', 'vs', '99%', 'editing', 'skills', '1']
2022-08-06 10:57:10.311644+00:00query_map: {'index': 'ta_video,ta_channel,ta_playlist', 'term': []}
2022-08-06 10:57:10.311668+00:00es path: ta_video,ta_channel,ta_playlist/_search
2022-08-06 10:57:10.311726+00:00query: {'size': 30, 'query': {'bool': {'must': [{'multi_match': {'query': 'rus sub / 1% beatbox skills vs 99% editing skills 1', 'type': 'bool_prefix', 'fuzziness': 'auto', 'operator': 'and', 'fields': ['channel_name._2gram', 'channel_name._3gram', 'channel_name.search_as_you_type', 'playlist_name._2gram', 'playlist_name._3gram', 'playlist_name.search_as_you_type', 'title._2gram', 'title._3gram', 'title.search_as_you_type']}}]}}}
2022-08-06 10:57:17.478025+00:00mIj6WZQOr2E: downloading now
2022-08-06 10:57:17.479432+00:00set task id: 3a00c173-6084-40a8-b66e-64339f3b929c
2022-08-06 10:57:17.479912+00:00[2022-08-06 12:57:17,479: INFO/MainProcess] Task home.tasks.download_single[3a00c173-6084-40a8-b66e-64339f3b929c] received
2022-08-06 10:57:17.482092+00:00[2022-08-06 12:57:17,481: WARNING/ForkPoolWorker-4] Added to queue with priority: mIj6WZQOr2E
2022-08-06 10:57:17.483474+00:00[2022-08-06 12:57:17,483: WARNING/ForkPoolWorker-4] Download queue already running.
2022-08-06 10:57:17.483661+00:00[2022-08-06 12:57:17,483: INFO/ForkPoolWorker-4] Task home.tasks.download_single[3a00c173-6084-40a8-b66e-64339f3b929c] succeeded in 0.0032160049959202297s: None
```

Another issue it brings to the daylight is that it hangs the download queue forever and it's not possible to download any other video meanwhile until you restart the container (log say the queue is already running).

I tried a naive workaround of copying the .png file with fixed percentages, but ended up with this error:
```
2022-08-06 11:22:32.011948+00:00mIj6WZQOr2E: downloading now
2022-08-06 11:22:32.068463+00:00set task id: 94c7034e-88de-43e5-b43b-1ae424a66241
2022-08-06 11:22:32.106507+00:00[2022-08-06 13:22:32,106: INFO/MainProcess] Task home.tasks.download_single[94c7034e-88de-43e5-b43b-1ae424a66241] received
2022-08-06 11:22:32.112958+00:00[2022-08-06 13:22:32,112: WARNING/ForkPoolWorker-4] Added to queue with priority: mIj6WZQOr2E
2022-08-06 11:22:40.698540+00:00[2022-08-06 13:22:40,698: WARNING/ForkPoolWorker-4] WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.png'
2022-08-06 11:22:40.705896+00:00[2022-08-06 13:22:40,705: WARNING/ForkPoolWorker-4] WARNING: Unable to embed thumbnails using AtomicParsley; AtomicParsley error: can't open /cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.png for reading: No such file or directory
2022-08-06 11:22:40.711250+00:00[2022-08-06 13:22:40,710: ERROR/ForkPoolWorker-4] Task home.tasks.download_single[94c7034e-88de-43e5-b43b-1ae424a66241] raised unexpected: FileNotFoundError(2, 'No such file or directory')
2022-08-06 11:22:40.711315+00:00Traceback (most recent call last):
2022-08-06 11:22:40.711332+00:00File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
2022-08-06 11:22:40.711345+00:00R = retval = fun(*args, **kwargs)
2022-08-06 11:22:40.711364+00:00File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-08-06 11:22:40.711385+00:00return self.run(*args, **kwargs)
2022-08-06 11:22:40.711407+00:00File "/app/home/tasks.py", line 119, in download_single
2022-08-06 11:22:40.711421+00:00VideoDownloader().run_queue()
2022-08-06 11:22:40.711439+00:00File "/app/home/src/download/yt_dlp_handler.py", line 174, in run_queue
2022-08-06 11:22:40.711455+00:00success = self._dl_single_vid(youtube_id)
2022-08-06 11:22:40.711486+00:00File "/app/home/src/download/yt_dlp_handler.py", line 360, in _dl_single_vid
2022-08-06 11:22:40.711500+00:00success = YtWrap(obs, self.config).download(youtube_id)
2022-08-06 11:22:40.711519+00:00File "/app/home/src/download/yt_dlp_base.py", line 48, in download
2022-08-06 11:22:40.711532+00:00ydl.download([url])
2022-08-06 11:22:40.711551+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
2022-08-06 11:22:40.711571+00:00self.__download_wrapper(self.extract_info)(
2022-08-06 11:22:40.711585+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
2022-08-06 11:22:40.711598+00:00res = func(*args, **kwargs)
2022-08-06 11:22:40.711612+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
2022-08-06 11:22:40.711631+00:00return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
2022-08-06 11:22:40.711646+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
2022-08-06 11:22:40.711661+00:00return func(self, *args, **kwargs)
2022-08-06 11:22:40.711678+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
2022-08-06 11:22:40.711697+00:00return self.process_ie_result(ie_result, download, extra_info)
2022-08-06 11:22:40.711712+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
2022-08-06 11:22:40.711727+00:00ie_result = self.process_video_result(ie_result, download=download)
2022-08-06 11:22:40.711747+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2661, in process_video_result
2022-08-06 11:22:40.711760+00:00self.process_info(new_info)
2022-08-06 11:22:40.711775+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
2022-08-06 11:22:40.711796+00:00replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
2022-08-06 11:22:40.711816+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3406, in post_process
2022-08-06 11:22:40.711830+00:00info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
2022-08-06 11:22:40.711850+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
2022-08-06 11:22:40.711863+00:00info = self.run_pp(pp, info)
2022-08-06 11:22:40.711878+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3367, in run_pp
2022-08-06 11:22:40.711892+00:00files_to_delete, infodict = pp.run(infodict)
2022-08-06 11:22:40.711913+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
2022-08-06 11:22:40.711928+00:00ret = func(self, info, *args, **kwargs)
2022-08-06 11:22:40.711955+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
2022-08-06 11:22:40.711969+00:00return func(self, info)
2022-08-06 11:22:40.711981+00:00File "/root/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 218, in run
2022-08-06 11:22:40.711992+00:00os.replace(temp_filename, filename)
2022-08-06 11:22:40.712003+00:00FileNotFoundError: [Errno 2] No such file or directory: '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.temp.mp4' -> '/cache/download/mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.mp4'
```
and this directory structure:
```
# ls /cache/download
XExFzCzwJek_RUS_SUB_1%_Flute_Skills_99%_Editing_Skills.mp4               mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png
mIj6WZQOr2E_RUS_SUB_1%%_Beatbox_Skills_Vs_99%%_Editing_Skills_1.png      mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.mp4
mIj6WZQOr2E_RUS_SUB_1%%_Beatbox_Skills_Vs_99%%_Editing_Skills_1.png.png  mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.webp
mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.mp4        mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.webp
```

**Comment by bbilly1** [comment]
I thought that was fixed in v0.2? I think there was an parsing error in yt-dlp in an older version that wouldn't escape the `%`, but only for thumbnails and not for videos, hence the error you see above.

Can you verify? Are you running v0.2? Maybe these failed downloads are from the before times and that would work fine now.

**Comment by bbilly1** [comment]
Closing this due to lack of feedback. Please reopen if you can confirm the error.

**Comment by p0358** [comment]
Yes, I am on v0.2.0, and I tried removing the files from queue and then /cache/download just in case that was some old version leftover, and then readding the videos to downloads, only to end up with this:
```
2022-08-22 07:43:39.551352+00:00OSError: write error
2022-08-22 07:43:44.093451+00:00https://www.youtube.com/watch?v=mIj6WZQOr2E
2022-08-22 07:43:44.093583+00:00processing: https://www.youtube.com/watch?v=mIj6WZQOr2E
2022-08-22 07:43:44.093613+00:00ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='v=mIj6WZQOr2E', fragment='')
2022-08-22 07:43:44.093638+00:00[{'url': 'mIj6WZQOr2E', 'type': 'video'}]
2022-08-22 07:43:44.100491+00:00[2022-08-22 09:43:44,100: INFO/MainProcess] Task home.tasks.extrac_dl[a234bffc-9e0d-4a47-94ab-26a2a24517fc] received
2022-08-22 07:43:44.264509+00:00[2022-08-22 09:43:44,264: WARNING/ForkPoolWorker-4] mIj6WZQOr2E: skipped adding already indexed video to download.
2022-08-22 07:43:44.288563+00:00[2022-08-22 09:43:44,288: INFO/ForkPoolWorker-4] Task home.tasks.extrac_dl[a234bffc-9e0d-4a47-94ab-26a2a24517fc] succeeded in 0.18699878687039018s: None
```
The video is however most certainly not in the downloaded library (nor on the drive), and these files exist in /cache/download now (however I don't 100% remember if they were redownloaded or did they stay there after my renaming):
```
ls /cache/download/
XExFzCzwJek_RUS_SUB_1%_Flute_Skills_99%_Editing_Skills.mp4         mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.png.mp4
mIj6WZQOr2E_RUS_SUB_1%_Beatbox_Skills_Vs_99%_Editing_Skills_1.mp4
```
I tried renaming the beginning of these files so that they wouldn't be detected, but ended up with the same error as above that the video is already indexed

**Comment by bbilly1** [comment]
Please open a support thread on Discord.
