### ISSUE TITLE
[Bug]: Offline Import Channel Creation Error

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#312]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

## Describe the bug
Upon adding videos to the download queue that are from a removed channel, an error occurs.  Then attempted to manually create the channel as described in the [wiki](https://github.com/tubearchivist/tubearchivist/wiki/Settings#offline-import) with nothing occurring.

`UCLfbThqyvG00lzOdMyB4GkQ.info.json` - attached to support `channel.info.json`
`Black_Hat_Ethical_Hacking - 20200327 - Payloads_-_Creating_Macro_Payloads_for_Office_Documents [eYo4Bkaq0Tc].info.json` - attached as an example of a video's json

### Relevant log output

```shell
[2022-08-19 23:36:20,126: WARNING/ForkPoolWorker-1] ERROR: [youtube] eYo4Bkaq0Tc: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
[2022-08-19 23:36:20,126: WARNING/ForkPoolWorker-1] https://www.youtube.com/watch?v=eYo4Bkaq0Tc: failed to get info from youtube
[2022-08-19 23:36:20,127: WARNING/ForkPoolWorker-1] UCLfbThqyvG00lzOdMyB4GkQ: get metadata from es
[2022-08-19 23:36:20,133: WARNING/ForkPoolWorker-1] {"_index":"ta_channel","_id":"UCLfbThqyvG00lzOdMyB4GkQ","found":false}
[2022-08-19 23:36:20,133: WARNING/ForkPoolWorker-1] UCLfbThqyvG00lzOdMyB4GkQ: scrape channel data from youtube
[2022-08-19 23:36:20,376: ERROR/ForkPoolWorker-1] Task home.tasks.run_manual_import[2117d676-f58f-43d3-a1f6-80240c6fe6ec] raised unexpected: KeyError('title')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 153, in run_manual_import
    ImportFolderScanner().scan()
  File "/app/home/src/index/filesystem.py", line 189, in scan
    self.process_videos()
  File "/app/home/src/index/filesystem.py", line 264, in process_videos
    ManualImport(current_video, self.CONFIG).run()
  File "/app/home/src/index/filesystem.py", line 498, in run
    json_data = self.index_metadata()
  File "/app/home/src/index/filesystem.py", line 506, in index_metadata
    video.build_json(
  File "/app/home/src/index/video.py", line 141, in build_json
    self._add_channel()
  File "/app/home/src/index/video.py", line 195, in _add_channel
    channel.build_json(upload=True, fallback=self.youtube_meta)
  File "/app/home/src/index/channel.py", line 182, in build_json
    self.get_from_youtube(fallback)
  File "/app/home/src/index/channel.py", line 190, in get_from_youtube
    self.json_data = ChannelScraper(self.youtube_id).get_json()
  File "/app/home/src/index/channel.py", line 43, in get_json
    self._parse_channel_main()
  File "/app/home/src/index/channel.py", line 92, in _parse_channel_main
    "channel_name": main_tab["title"],
KeyError: 'title'
```

### Anything else?

[UCLfbThqyvG00lzOdMyB4GkQ.info.json.txt](https://github.com/tubearchivist/tubearchivist/files/9386232/UCLfbThqyvG00lzOdMyB4GkQ.info.json.txt)
[Black_Hat_Ethical_Hacking - 20200327 - Payloads_-_Creating_Macro_Payloads_for_Office_Documents [eYo4Bkaq0Tc].info.json.txt](https://github.com/tubearchivist/tubearchivist/files/9386234/Black_Hat_Ethical_Hacking.-.20200327.-.Payloads_-_Creating_Macro_Payloads_for_Office_Documents.eYo4Bkaq0Tc.info.json.txt)

**Comment by bbilly1** [comment]
this should now be fixed in v0.2.2, please update.
