### ISSUE TITLE
[Bug]: IndexError('list index out of range')

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#315]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

## Describe the bug
I think I may have finally broke TA/ES.  Both Manual and Pending Download imports are failing with the errors listed from the log below.

## Steps To Reproduce
Issue continued to occur no matter what video I attempt to import by either means.
I've restarted both containers and continue to have the issue with only Manual imports.  Pending appears to be working at this time.
I've also disabled indexing subtitles since that was mentioned in the error without that correcting the issue as well.

### Relevant log output

```shell
Download Pending:
[2022-08-20 22:14:05,641: ERROR/ForkPoolWorker-1] Task download_pending[8335a5df-0624-4ce5-954d-3c19a85525a9] raised unexpected: IndexError('list index out of range')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 89, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 392, in index_new_video
    video.check_subtitles()
  File "/app/home/src/index/video.py", line 354, in check_subtitles
    subtitles = handler.get_subtitles()
  File "/app/home/src/index/subtitle.py", line 45, in get_subtitles
    auto_cap = self._get_auto_caption(lang)
  File "/app/home/src/index/subtitle.py", line 65, in _get_auto_caption
    subtitle = [i for i in all_formats if i["ext"] == "json3"][0]
IndexError: list index out of range

Manual Import:
[2022-08-20 22:14:39,139: ERROR/ForkPoolWorker-32] Task home.tasks.run_manual_import[fd62fd24-9b48-4772-afec-da0f13f2380a] raised unexpected: IndexError('list index out of range')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 153, in run_manual_import
    ImportFolderScanner().scan()
  File "/app/home/src/index/filesystem.py", line 189, in scan
    self.process_videos()
  File "/app/home/src/index/filesystem.py", line 264, in process_videos
    ManualImport(current_video, self.CONFIG).run()
  File "/app/home/src/index/filesystem.py", line 498, in run
    json_data = self.index_metadata()
  File "/app/home/src/index/filesystem.py", line 514, in index_metadata
    video.check_subtitles(subtitle_files=self.current_video["subtitle"])
  File "/app/home/src/index/video.py", line 354, in check_subtitles
    subtitles = handler.get_subtitles()
  File "/app/home/src/index/subtitle.py", line 39, in get_subtitles
    user_sub = self._get_user_subtitles(lang)
  File "/app/home/src/index/subtitle.py", line 102, in _get_user_subtitles
    subtitle = [i for i in all_formats if i["ext"] == "json3"][0]
IndexError: list index out of range
```

**Comment by PhuriousGeorge** [comment]
Another restart due to a first time issue with a download that refused to be killed and everything appears to be working again?

**Comment by PhuriousGeorge** [comment]
Okay, so some additional progress.  I would guess that something was "stuck" or something, causing everything to fail.  I re-pulled the image and everything appears to be working except some of my manual imports from a particular channel.  I'm guessing something is making the json invalid; still tinkering.

**Comment by bbilly1** [comment]
Closing this for now. Please reopen if you have more details.
