### ISSUE TITLE
[Bug]: Thumbnail download fails with PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#325]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Linux

## Describe the bug
Downloading and processing a specific video thumbnail fails inexplicably. 

## Steps To Reproduce
Download video in question: https://www.youtube.com/watch?v=2JAaNllYTJ0

## Expected behavior
Needs error handling, maybe workaround to lower resolution thumbnail or fallback to TA default? 

### Relevant log output

```shell
2022-09-13T21:56:49.070408000Z [2022-09-14 00:56:49,068: ERROR/ForkPoolWorker-4] Task home.tasks.extrac_dl[3e17b6f5-9047-4558-93e9-2aba774102ba] raised unexpected: UnidentifiedImageError('cannot identify image file <_io.BytesIO object at 0x7f9d07e160>')

2022-09-13T21:56:49.070825000Z Traceback (most recent call last):

2022-09-13T21:56:49.071099000Z   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

2022-09-13T21:56:49.071410000Z     R = retval = fun(*args, **kwargs)

2022-09-13T21:56:49.071679000Z   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

2022-09-13T21:56:49.071891000Z     return self.run(*args, **kwargs)

2022-09-13T21:56:49.072076000Z   File "/app/home/tasks.py", line 134, in extrac_dl

2022-09-13T21:56:49.072262000Z     pending_handler.add_to_pending()

2022-09-13T21:56:49.072457000Z   File "/app/home/src/download/queue.py", line 209, in add_to_pending

2022-09-13T21:56:49.072646000Z     ThumbManager(youtube_id).download_video_thumb(url)

2022-09-13T21:56:49.072841000Z   File "/app/home/src/download/thumbnails.py", line 117, in download_video_thumb

2022-09-13T21:56:49.073026000Z     img_raw = self.download_raw(url)

2022-09-13T21:56:49.073258000Z   File "/app/home/src/download/thumbnails.py", line 45, in download_raw

2022-09-13T21:56:49.073482000Z     return Image.open(response.raw)

2022-09-13T21:56:49.073682000Z   File "/root/.local/lib/python3.10/site-packages/PIL/Image.py", line 3147, in open

2022-09-13T21:56:49.073880000Z     raise UnidentifiedImageError(

2022-09-13T21:56:49.074106000Z PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f9d07e160>
```

**Comment by bbilly1** [comment]
That's merged in v0.2.3.
