### ISSUE TITLE
[Bug]: TypeError bool object is not subscriptable

### ISSUE THREAD

**Issue by dyslexicjedi** [tubearchivist/tubearchivist#329]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Linux Docker

## Describe the bug
Python bug, seems to stop importing.

Edit: Perhaps it was doing a background download as part of the schedule, the trace doesn't seem to fit with the import.

## Steps To Reproduce
Attempting to import existing video

Edit: Not related to import, it's continuing. Must be related to a scan. 

## Expected behavior
Import Video

### Relevant log output

```shell
[2022-09-29 20:32:26,271: ERROR/ForkPoolWorker-32] Task download_pending[c8dc3145-3414-4f84-b1f3-e2cd10c26fe8] raised unexpected: TypeError("'bool' object is not subscriptable")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 89, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 202, in run_queue
    DownloadPostProcess(self).run()
  File "/app/home/src/download/yt_dlp_handler.py", line 41, in run
    self.validate_playlists()
  File "/app/home/src/download/yt_dlp_handler.py", line 105, in validate_playlists
    self._validate_channel_playlist(all_channel_playlist, id_c)
  File "/app/home/src/download/yt_dlp_handler.py", line 113, in _validate_channel_playlist
    playlist.build_json(scrape=True)
  File "/app/home/src/index/playlist.py", line 41, in build_json
    self.process_youtube_meta()
  File "/app/home/src/index/playlist.py", line 51, in process_youtube_meta
    "playlist_name": self.youtube_meta["title"],
TypeError: 'bool' object is not subscriptable
```

**Comment by dyslexicjedi** [comment]
Nevermind, it's related to the WL playlist. I'm betting the cookie expired.
