### ISSUE TITLE
Setting channel page to 0 breaks the download queue

### ISSUE THREAD

**Issue by erwin** [tubearchivist/tubearchivist#334]
<details>

<summary>I think this is the relevant error, but click here for the full log:

```
[INFO/MainProcess] Task update_subscribed[3c8755be-b84d-414f-b6f5-2887b94e3ac1] 
  received

[ERROR/ForkPoolWorker-16] Task update_subscribed[3c8755be-b84d-414f-b6f5-2887b94e3ac1]
  raised unexpected: ValueError("'1:False' is not a valid specification")
```

</summary>

```
[tasks]

  . check_reindex

  . download_pending

  . home.tasks.download_single

  . home.tasks.extrac_dl

  . home.tasks.index_channel_playlists

  . home.tasks.re_sync_thumbs

  . home.tasks.rescan_filesystem

  . home.tasks.run_manual_import

  . home.tasks.run_restore_backup

  . home.tasks.subscribe_to

  . run_backup

  . thumbnail_check

  . update_subscribed

[2022-10-10 10:05:01,153: INFO/MainProcess] Connected to redis://archivist-redis:6379//

[2022-10-10 10:05:01,156: INFO/MainProcess] mingle: searching for neighbors

Mon Oct 10 10:05:01 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /static/favicon/apple-touch-icon.a94db2e7a4e7.png (ip 192.168.1.15) !!!

Mon Oct 10 10:05:01 2022 - uwsgi_response_sendfile_do(): Broken pipe [core/writer.c line 655] during GET /static/favicon/apple-touch-icon.a94db2e7a4e7.png (192.168.1.15)

OSError: write error

[2022-10-10 10:05:02,162: INFO/MainProcess] mingle: all alone

[2022-10-10 10:05:02,193: INFO/MainProcess] celery@bb13ec0ab535 ready.

rescan subscribed channels

[2022-10-10 10:05:42,960: INFO/MainProcess] Task update_subscribed[3c8755be-b84d-414f-b6f5-2887b94e3ac1] received

[2022-10-10 10:05:43,997: ERROR/ForkPoolWorker-16] Task update_subscribed[3c8755be-b84d-414f-b6f5-2887b94e3ac1] raised unexpected: ValueError("'1:False' is not a valid specification")

Traceback (most recent call last):

  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/app/home/tasks.py", line 60, in update_subscribed

    missing_from_channels = channel_handler.find_missing()

  File "/app/home/src/download/subscriptions.py", line 65, in find_missing

    last_videos = self.get_last_youtube_videos(channel_id)

  File "/app/home/src/download/subscriptions.py", line 47, in get_last_youtube_videos

    channel = YtWrap(obs, self.config).extract(url)

  File "/app/home/src/download/yt_dlp_base.py", line 58, in extract

    response = yt_dlp.YoutubeDL(self.obs).extract_info(url)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info

    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper

    return func(self, *args, **kwargs)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info

    return self.process_ie_result(ie_result, download, extra_info)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1648, in process_ie_result

    return self.__process_playlist(ie_result, download)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1706, in __process_playlist

    entries = resolved_entries = list(entries)

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 768, in _iter

    for x in iterable:

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 2892, in get_requested_items

    for index in self.parse_playlist_items(playlist_items):

  File "/root/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 2874, in parse_playlist_items

    raise ValueError(f'{segment!r} is not a valid specification')

ValueError: '1:False' is not a valid specification
```

</details>

<details>
<summary>In Settings, I have:</summary>

Current page size: False

Current download limit: False

Current download speed limit in KB/s: False

Current throttled rate limit in KB/s: False

Current scraping sleep interval: 3

Rescan Subscriptions
Current rescan schedule: 30 3 */2 

Start download
Current Download schedule: 30 * * 

Refresh Metadata
Current Metadata refresh schedule: 0 12 * 

Current refresh for metadata older than x days: 90
Refresh older than x days, recommended 90:
</details>

I am running Tube Archivist in a Docker container.
For disk space:
* / is 35% free (.5T avail) 
* /data is 35% free (13T avail)

Permissions wise, I have checked a few times and I believe permissions are correct.
I am using the Docker-Compose file.

I can go to Tube Archivist > Downloads > Add to download queue and it works fine to download a video...

It appears to specifically be the subscription refresh that is failing.

**Comment by bbilly1** [comment]
I'm guessing that is only a specific channel that has issues, as it looks like the error is coming from yt-dlp and not from Tube Archivist. 

So we'll nee do know which channel fails and how that differs, as all my subscriptions work fine. You can get an indicator from the progress message or if you are comfortable, add some log output like this: https://github.com/tubearchivist/tubearchivist/commit/6eee762d3a12984f412337a2dea714fa1e2c3139

**Comment by erwin** [comment]
Thank you very much for looking into this!

I added the print statement to `subscriptions.py` per your link, and it looks like the problem channel_id is: `UCSGGjRqTLBoAH2DyxfSLCmQ`.

Looks like that translates to: youtube.com/channel/UCSGGjRqTLBoAH2DyxfSLCmQ

Or the vanity URL: https://youtube.com/c/04AMofficial/

<details>
<summary>
Here's a full excerpt of the log.
</summary>

```

[2022-10-14 15:23:06,956: INFO/MainProcess] Connected to redis://archivist-redis:6379//

[2022-10-14 15:23:06,958: INFO/MainProcess] mingle: searching for neighbors

[2022-10-14 15:23:07,965: INFO/MainProcess] mingle: all alone

[2022-10-14 15:23:08,005: INFO/MainProcess] celery@bb13ec0ab535 ready.

rescan subscribed channels

[2022-10-14 15:23:22,841: INFO/MainProcess] Task update_subscribed[d0d87a46-5fb4-4bc8-8c50-476efacf7dbf] received

[2022-10-14 15:23:22,942: WARNING/ForkPoolWorker-16] UCSGGjRqTLBoAH2DyxfSLCmQ: find missing videos.

[2022-10-14 15:23:23,806: ERROR/ForkPoolWorker-16] Task update_subscribed[d0d87a46-5fb4-4bc8-8c50-476efacf7dbf] raised unexpected: ValueError("'1:False' is not a valid specification")

```

</details>

Would love to get this working again! Thanks so much for your help!

**Comment by bbilly1** [comment]
Hmm, that works without any issue for me... So that's not a channel specific problem. 

What did you set as channel page size in the settings? https://github.com/tubearchivist/tubearchivist/wiki/Settings#subscriptions

I'm guessing you set this to `0` to deactivate it? I think that might result in an error. If so try to reset it to 50 or something.

**Comment by erwin** [comment]
Yes, you are correct. I had current page size 0.
I changed it to 50 as you advised and it is downloading now.

Is there a way I can use TubeArchivist to archive ALL EPISODES of youtube channels though? I (perhaps wrongly) thought that setting the page size to 0 was so that I could get every episode.

**Comment by bbilly1** [comment]
To download the whole channel, add the channel to the download queue: https://github.com/tubearchivist/tubearchivist/wiki/Downloads#add-to-download-queue.

But this will need some error handling.

**Comment by bbilly1** [comment]
Thanks for reporting, there is now form validation in v0.2.4 on the settings page preventing you from setting the channel page size to 0.
