### ISSUE TITLE
[Bug]:  Failed to establish a new connection: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by CasaPas** [tubearchivist/tubearchivist#335]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

## Describe the bug
I am getting the following error when trying to subscribe to a channel or do a manual import.

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UC3262qU-td2TPqiFGgCSMXQ/about?hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9d44b30d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
It appears to be a network issue, but I can ping out the container to the YouTube URL directly.

```
# ping youtube.com
PING youtube.com (74.125.193.91) 56(84) bytes of data.
64 bytes from di-in-f91.1e100.net (74.125.193.91): icmp_seq=1 ttl=57 time=30.3 ms
64 bytes from ig-in-f91.1e100.net (74.125.193.91): icmp_seq=2 ttl=57 time=29.1 ms
64 bytes from di-in-f91.1e100.net (74.125.193.91): icmp_seq=3 ttl=57 time=27.8 ms
64 bytes from ig-in-f91.1e100.net (74.125.193.91): icmp_seq=4 ttl=57 time=25.8 ms
64 bytes from di-in-f91.1e100.net (74.125.193.91): icmp_seq=5 ttl=57 time=42.5 ms
64 bytes from ig-in-f91.1e100.net (74.125.193.91): icmp_seq=6 ttl=57 time=34.7 ms
^C
--- youtube.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5008ms
rtt min/avg/max/mdev = 25.833/31.689/42.537/5.554 ms
```

```
# ping https://www.youtube.com/channel/UCyLgy4_CKmkYYktHxGSBp2w
ping: https://www.youtube.com/channel/UCyLgy4_CKmkYYktHxGSBp2w: Name or service not known
```

Any ideas?

## Steps To Reproduce
Just do a manual import or try to add a channel

## Expected behavior
It should work.

### Relevant log output

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 249, in subscribe_to
    ChannelSubscription().change_subscribe(
  File "/app/home/src/download/subscriptions.py", line 94, in change_subscribe
    channel.build_json()
  File "/app/home/src/index/channel.py", line 183, in build_json
    self.get_from_youtube(fallback)
  File "/app/home/src/index/channel.py", line 191, in get_from_youtube
    self.json_data = ChannelScraper(self.youtube_id).get_json()
  File "/app/home/src/index/channel.py", line 38, in get_json
    self.get_soup()
  File "/app/home/src/index/channel.py", line 52, in get_soup
    response = requests.get(
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCyLgy4_CKmkYYktHxGSBp2w/about?hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9d44a2410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
https://www.youtube.com/channel/UCyLgy4_CKmkYYktHxGSBp2w
[2022-10-11 16:22:44,688: INFO/MainProcess] Task home.tasks.subscribe_to[9a674281-2e74-4ba7-990d-696cb69c28ac] received
[2022-10-11 16:22:44,689: WARNING/ForkPoolWorker-32] processing: https://www.youtube.com/channel/UCyLgy4_CKmkYYktHxGSBp2w
[2022-10-11 16:22:44,689: WARNING/ForkPoolWorker-32] ParseResult(scheme='https', netloc='www.youtube.com', path='/channel/UCyLgy4_CKmkYYktHxGSBp2w', params='', query='', fragment='')
[2022-10-11 16:22:44,691: WARNING/ForkPoolWorker-32] UCyLgy4_CKmkYYktHxGSBp2w: get metadata from es
[2022-10-11 16:22:44,698: WARNING/ForkPoolWorker-32] {"_index":"ta_channel","_id":"UCyLgy4_CKmkYYktHxGSBp2w","found":false}
[2022-10-11 16:22:44,698: WARNING/ForkPoolWorker-32] UCyLgy4_CKmkYYktHxGSBp2w: scrape channel data from youtube
[2022-10-11 16:22:44,700: ERROR/ForkPoolWorker-32] Task home.tasks.subscribe_to[9a674281-2e74-4ba7-990d-696cb69c28ac] raised unexpected: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCyLgy4_CKmkYYktHxGSBp2w/about?hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9d44b3a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14f9d44b3a60>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCyLgy4_CKmkYYktHxGSBp2w/about?hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9d44b3a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 249, in subscribe_to
    ChannelSubscription().change_subscribe(
  File "/app/home/src/download/subscriptions.py", line 94, in change_subscribe
    channel.build_json()
  File "/app/home/src/index/channel.py", line 183, in build_json
    self.get_from_youtube(fallback)
  File "/app/home/src/index/channel.py", line 191, in get_from_youtube
    self.json_data = ChannelScraper(self.youtube_id).get_json()
  File "/app/home/src/index/channel.py", line 38, in get_json
    self.get_soup()
  File "/app/home/src/index/channel.py", line 52, in get_soup
    response = requests.get(
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCyLgy4_CKmkYYktHxGSBp2w/about?hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9d44b3a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by CasaPas** [comment]
So, just for the benefit of anyone else searching for the above error...

After updating to 6.11 I began to have issues with yt-dlp based containers (YouTube-DL & TubeArchivist). In case any one else started to get the [errno -2] issue after updating, I found after a lot of hair pulling and tweaking that Docker was not resolving the DNS properly to the containers (in Bridge Mode), and they were thus unable to resolve URL's.

Manually editing the **/etc/docker/daemon.json** file to include the following line of code allows the containers to again resolve URL's. You need to restart Docker after this edit for it to take effect.

`"dns": ["8.8.8.8","8.8.4.4","1.1.1.1"]`

The contents of my **daemon.json** looks like this for context;

```
{
    "runtimes": {"nvidia": {"path": "/usr/bin/nvidia-container-runtime","runtimeArgs": []}},
    "dns": ["8.8.8.8","8.8.4.4","1.1.1.1"]
}
```

I also managed to automate the code insertion due to the lack of persistence of config files in the OS, by adding the following line to my **go** file in the **/config** folder on the USB. This line should be at the start of the **go** file so it is executed BEFORE docker launches.

```
# Fix the docker DNS issue
sed -i '0,/{/a\    "dns": ["8.8.8.8","8.8.4.4","1.1.1.1"],' /etc/docker/daemon.json 
```

My entire go file looks like this for context;

```
#!/bin/bash

# Fix the docker DNS issue
sed -i '0,/{/a\    "dns": ["8.8.8.8","8.8.4.4","1.1.1.1"],' /etc/docker/daemon.json

# Start the Management Utility
/usr/local/sbin/emhttp &

# Chip drivers
modprobe jc42
modprobe k10temp
modprobe w83627ehf
modprobe fam15h_power

# Enlarge the LOG partition (because Dynamix System Stats needs at least 186Mb, default LOG is 128Mb)
mount -o remount,size=384m /var/log

# Binhex (Container update)
# curl -o '/usr/bin/runc' -L 'https://github.com/binhex/arch-packages/raw/master/static/x86-64/runc' && chmod +x '/usr/bin/runc'
```

Hope that helps somebody.​

**Comment by bbilly1** [comment]
Thanks for researching this and putting the solution together here. I'm closing the issue here for now, as this is most likely a docker related bug, that hopefully will get fixed at some point. If it comes up again, I'll add it to the wiki, but in any case, if somebody searches for it, they should be able to find this here.
