### ISSUE TITLE
[Bug]: Redis continer does not start after latest update

### ISSUE THREAD

**Issue by alphamaestro555** [tubearchivist/tubearchivist#355]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

## Describe the bug
The Tubearchivist-Redis container redislabs/rejson:latest does not start after the latest update (v2.4.0).

## Steps To Reproduce
I'm using the three TA containers from Unraid's community applications. It was running fine, then I saw there was an update for the TA-redis container. I updated it and the container does not start after that. See the logs below. 
I tried to revert to redislabs/rejson:2.2.0 without success.

### Relevant log output

```shell
1:C 30 Oct 2022 07:46:36.883 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 30 Oct 2022 07:46:36.883 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 30 Oct 2022 07:46:36.883 # Configuration loaded
1:M 30 Oct 2022 07:46:36.883 * monotonic clock: POSIX clock_gettime
1:M 30 Oct 2022 07:46:36.883 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:M 30 Oct 2022 07:46:36.883 * Running mode=standalone, port=6379.
1:M 30 Oct 2022 07:46:36.883 # Server initialized
1:M 30 Oct 2022 07:46:36.883 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 30 Oct 2022 07:46:36.895 * <ReJSON> version: 20400 git sha: e383c08 branch: HEAD
1:M 30 Oct 2022 07:46:36.895 * <ReJSON> Exported RedisJSON_V1 API
1:M 30 Oct 2022 07:46:36.895 * <ReJSON> Exported RedisJSON_V2 API
1:M 30 Oct 2022 07:46:36.895 * <ReJSON> Enabled diskless replication
1:M 30 Oct 2022 07:46:36.895 * <ReJSON> Created new data type 'ReJSON-RL'
1:M 30 Oct 2022 07:46:36.896 * Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so
1:M 30 Oct 2022 07:46:36.896 * Loading RDB produced by version 6.2.7
1:M 30 Oct 2022 07:46:36.896 * RDB age 29667 seconds
1:M 30 Oct 2022 07:46:36.896 * RDB memory usage when created 1.12 Mb
1:M 30 Oct 2022 07:46:36.897 # The RDB file contains AUX module data I can't load: no matching module 'scdtype00'
```

**Comment by alphamaestro555** [comment]
Here is the logs from TA container bbilly1/tubearchivist:latest

```
  File "/app/./home/src/ta/config.py", line 78, in get_config_redis
    config = RedisArchivist().get_message("config")
  File "/app/./home/src/ta/ta_redis.py", line 52, in get_message
    reply = self.conn.execute_command("JSON.GET", self.NAME_SPACE + key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.1.2:6380. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
    raise err
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
    callback = resolver.resolve_error_handler(500)
  File "/root/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 729, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
  File "/root/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/./config/urls.py", line 20, in <module>
    path("", include("home.urls")),
  File "/root/.local/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/./home/urls.py", line 7, in <module>
    from home.views import (
  File "/app/./home/views.py", line 11, in <module>
    from api.src.search_processor import SearchProcess
  File "/app/api/src/search_processor.py", line 14, in <module>
    class SearchProcess:
  File "/app/api/src/search_processor.py", line 17, in SearchProcess
    CONFIG = AppConfig().config
  File "/app/./home/src/ta/config.py", line 20, in __init__
    self.config = self.get_config()
  File "/app/./home/src/ta/config.py", line 25, in get_config
    config = self.get_config_redis()
  File "/app/./home/src/ta/config.py", line 78, in get_config_redis
    config = RedisArchivist().get_message("config")
  File "/app/./home/src/ta/ta_redis.py", line 52, in get_message
    reply = self.conn.execute_command("JSON.GET", self.NAME_SPACE + key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.1.2:6380. Connection refused.
[pid: 38|app: 0|req: 2/2] 172.18.0.5 () {52 vars in 1009 bytes} [Sun Oct 30 04:48:32 2022] GET / => generated 0 bytes in 46 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by bbilly1** [comment]
duplicate from here: #354
