### ISSUE TITLE
[Bug]: Queue post-processing KeyError

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#371]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Unraid

## Describe the bug
Seems similar to #101 Once download queue completes, the referenced error occurs and post-processing does not complete 

### Relevant log output

```shell
[2022-11-29 23:10:06,859: WARNING/ForkPoolWorker-32] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"value cannot be null"}],"type":"illegal_argument_exception","reason":"value cannot be null"},"status":400}
[2022-11-29 23:10:06,866: ERROR/ForkPoolWorker-32] Task download_pending[cd421b82-2cbb-45de-8a17-acb7701d109b] raised unexpected: KeyError('hits')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 90, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 240, in run_queue
    DownloadPostProcess(self).run()
  File "/app/home/src/download/yt_dlp_handler.py", line 42, in run
    self.validate_playlists()
  File "/app/home/src/download/yt_dlp_handler.py", line 105, in validate_playlists
    playlists = channel.get_indexed_playlists()
  File "/app/home/src/index/channel.py", line 400, in get_indexed_playlists
    all_playlists = IndexPaginate("ta_playlist", data).get_results()
  File "/app/home/src/es/connect.py", line 115, in get_results
    all_results = self.run_loop()
  File "/app/home/src/es/connect.py", line 140, in run_loop
    all_hits = response["hits"]["hits"]
KeyError: 'hits'
```

**Comment by PhuriousGeorge** [comment]
Resolved by removing playlists and re-adding per instructions in #364
