### ISSUE TITLE
[Bug]: Download process breaks down at the end

### ISSUE THREAD

**Issue by hellofaduck** [tubearchivist/tubearchivist#376]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

latest docker inside debian lxc

## Describe the bug
I cant download video, it shows the downloading progress, after 100% it still in queue.
## Steps To Reproduce
Download this video https://www.youtube.com/watch?v=0DyqgGWWpzI
### Relevant log output

```shell
-12-03 14:21:05,026: INFO/MainProcess] Task home.tasks.download_single[6f5085bc-0cb3-4994-9c1a-a5d131fe6bc7] received
[2022-12-03 14:21:05,028: WARNING/ForkPoolWorker-8] Added to queue with priority: 0DyqgGWWpzI
[2022-12-03 14:21:06,455: WARNING/ForkPoolWorker-8] 0DyqgGWWpzI: get metadata from youtube
[2022-12-03 14:21:07,814: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: get metadata from es
[2022-12-03 14:21:07,818: WARNING/ForkPoolWorker-8] {"_index":"ta_channel","_id":"UCPMaKKHTJjzChrjCVx4z4Mg","found":false}
[2022-12-03 14:21:07,818: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: scrape channel data from youtube
[2022-12-03 14:21:07,985: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: download channel thumbnail
[2022-12-03 14:21:08,166: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: retry thumbnail download https://yt3.ggpht.com/EUNDYjI4prdSxIG8ll8orZkNrtRJemfvdPRvgugsl6KtfaU-JNYX9gx90hI7IeHqT_4RYDgceA=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
[2022-12-03 14:21:09,213: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: retry thumbnail download https://yt3.ggpht.com/EUNDYjI4prdSxIG8ll8orZkNrtRJemfvdPRvgugsl6KtfaU-JNYX9gx90hI7IeHqT_4RYDgceA=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
[2022-12-03 14:21:11,263: WARNING/ForkPoolWorker-8] UCPMaKKHTJjzChrjCVx4z4Mg: retry thumbnail download https://yt3.ggpht.com/EUNDYjI4prdSxIG8ll8orZkNrtRJemfvdPRvgugsl6KtfaU-JNYX9gx90hI7IeHqT_4RYDgceA=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
[2022-12-03 14:21:20,272: ERROR/ForkPoolWorker-8] Task home.tasks.download_single[6f5085bc-0cb3-4994-9c1a-a5d131fe6bc7] raised unexpected: AttributeError("'bool' object has no attribute 'convert'")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 120, in download_single
    VideoDownloader().run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 210, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 405, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 150, in build_json
    self._add_channel()
  File "/app/home/src/index/video.py", line 204, in _add_channel
    channel.build_json(upload=True, fallback=self.youtube_meta)
  File "/app/home/src/index/channel.py", line 183, in build_json
    self.get_from_youtube(fallback)
  File "/app/home/src/index/channel.py", line 199, in get_from_youtube
    self.get_channel_art()
  File "/app/home/src/index/channel.py", line 245, in get_channel_art
    ThumbManager(self.youtube_id, item_type="channel").download(urls)
  File "/app/home/src/download/thumbnails.py", line 99, in download
    self.download_channel_art(url)
  File "/app/home/src/download/thumbnails.py", line 150, in download_channel_art
    self._download_channel_banner(channel_banner, skip_existing)
  File "/app/home/src/download/thumbnails.py", line 177, in _download_channel_banner
    img_raw.convert("RGB").save(banner_path)
AttributeError: 'bool' object has no attribute 'convert'
```

### Anything else?
*UPDATE*
Tried another video on another channel - same problem, it seems program cant download channel thumbnail for some strange reason..

**Comment by hellofaduck** [comment]
Uhmmm, it seems that i found a problem source. It's my goverment watchdog blocking google QUIC protocol, so youtube is working but some services around it blocked. When i route this container through vpn in another country all works fine.
So because of this problem is there is a way to add an option to use a proxy for downloading purposes?

**Comment by bbilly1** [comment]
There are a lot of different approaches you can take, I'm sure you are familiar with the workarounds. :-) 

Sometimes just changing the DNS to a none filtered one is enough, sometimes you need a proxy or VPN, also see here: #366. At the end of the day, there are too many variations and approaches to deal with that, but solutions are readily available. Probably not a lot of benefit to re-implement those again in this project.
