### ISSUE TITLE
[Bug]: HTTP 500 and KeyError: 'snapshot_name' after updated to v0.3.0 from v0.2.4 and set 'Snapshot' to enabled

### ISSUE THREAD

**Issue by grantterra** [tubearchivist/tubearchivist#377]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Unraid 6.11.5

## Describe the bug
After updated to v0.3.0 from v0.2.4 and set 'Snapshot' to enabled, then restart the container.
I was no longer able to access Web UI, and the console outputs lots of errors.

## Steps To Reproduce
I use templates from Unraid Apps:
- TubeArchivist
- TubeArchivist-ES
- TubeArchivist-RedisJSON
All settings are default, except the repo of 'TubeArchivist-RedisJSON' is changed to 'redislabs/rejson:2.0.11' to get it works.

Updated to v0.3.0 from v0.2.4, at first, I was able to access Web UI.

Then I changed some settings, here's what I remembered:
- Enabled the 'Snapshot'.
- Changed comment setting.
- Re-sync cookies via browser extension

Because the TA's behavior is not what I expected at that time (trying to rescan subscribe, but nothing got.), I was restarting the container to see if helps.

After restart, I was no longer able to access Web UI.

## Expected behavior
Able to access Web UI.

### Relevant log output

```shell
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 123181
your memory page size is 4096 bytes
detected max file descriptor number: 40960
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.8 (main, Nov 15 2022, 21:06:05) [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55da189c7d70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 154032 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/root/.local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/root/.local/lib/python3.10/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/bin/beat.py", line 72, in beat
    return beat().run()
  File "/root/.local/lib/python3.10/site-packages/celery/apps/beat.py", line 75, in run
    self.init_loader()
  File "/root/.local/lib/python3.10/site-packages/celery/apps/beat.py", line 124, in init_loader
    self.app.loader.init_worker()
  File "/root/.local/lib/python3.10/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/root/.local/lib/python3.10/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/root/.local/lib/python3.10/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/home/apps.py", line 135, in ready
    startup.run()
  File "/app/home/apps.py", line 33, in run
    ElasitIndexWrap().setup()
  File "/app/home/src/es/index_setup.py", line 160, in setup
    self._check_backup()
  File "/app/home/src/es/index_setup.py", line 205, in _check_backup
    ElasticSnapshot().take_snapshot_now(wait=True)
  File "/app/home/src/es/snapshot.py", line 154, in take_snapshot_now
    self._wait_for_snapshot(response["snapshot_name"])
KeyError: 'snapshot_name'
run startup checks
elasticsearch version check passed
celery beat v5.2.7 (dawn-chorus) is starting.
run startup checks
elasticsearch version check passed
sync redis
detected mapping change: channel_last_refresh, {'type': 'date'}
run startup checks
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400}
elasticsearch version check passed
sync redis
detected mapping change: channel_last_refresh, {'type': 'date'}
sync redis
detected mapping change: channel_last_refresh, {'type': 'date'}
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400}
Traceback (most recent call last):
  File "/root/.local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/root/.local/lib/python3.10/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
  File "/root/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/root/.local/lib/python3.10/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/root/.local/lib/python3.10/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/root/.local/lib/python3.10/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/root/.local/lib/python3.10/site-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/home/apps.py", line 135, in ready
    startup.run()
  File "/app/home/apps.py", line 33, in run
    ElasitIndexWrap().setup()
  File "/app/home/src/es/index_setup.py", line 160, in setup
    self._check_backup()
  File "/app/home/src/es/index_setup.py", line 205, in _check_backup
    ElasticSnapshot().take_snapshot_now(wait=True)
  File "/app/home/src/es/snapshot.py", line 154, in take_snapshot_now
    self._wait_for_snapshot(response["snapshot_name"])
KeyError: 'snapshot_name'
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400}
Traceback (most recent call last):
  File "/app/./config/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/root/.local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/./home/apps.py", line 135, in ready
    startup.run()
  File "/app/./home/apps.py", line 33, in run
    ElasitIndexWrap().setup()
  File "/app/./home/src/es/index_setup.py", line 160, in setup
    self._check_backup()
  File "/app/./home/src/es/index_setup.py", line 205, in _check_backup
    ElasticSnapshot().take_snapshot_now(wait=True)
  File "/app/./home/src/es/snapshot.py", line 154, in take_snapshot_now
    self._wait_for_snapshot(response["snapshot_name"])
KeyError: 'snapshot_name'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 34, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 34|app: -1|req: -1/1] 192.168.50.3 () {46 vars in 1103 bytes} [Sun Dec  4 12:25:32 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

**Comment by bbilly1** [comment]
Indicating by `no such snapshot lifecycle policy [ta_daily]` I'm guessing that when you activated snapshots on v0.2.4 that didn't really work. Did you set the [required env var](https://github.com/tubearchivist/tubearchivist/wiki/Settings#snapshots)? Any permission issues there? 

I'd suggest, go back to v0.2.4, activate that and make sure it works, when in doubt post the logs from that here, then the update should complete without any issue.

**Comment by grantterra** [comment]
> Indicating by `no such snapshot lifecycle policy [ta_daily]` I'm guessing that when you activated snapshots on v0.2.4 that didn't really work. Did you set the [required env var](https://github.com/tubearchivist/tubearchivist/wiki/Settings#snapshots)? Any permission issues there?
> 
> I'd suggest, go back to v0.2.4, activate that and make sure it works, when in doubt post the logs from that here, then the update should complete without any issue.

I was activated snapshots after updated to v0.3.0.

That was my fault, I didn't set the required env var before I enabled it, but set it after enabled.

Downgrade to v0.2.4 and disable it, then upgrade to v0.3.0 again. TA works again.

I appreciate it.
