### ISSUE TITLE
Server Error (500) Following Fresh Install following Failed Update

### ISSUE THREAD

**Issue by WillScott73** [tubearchivist/tubearchivist#379]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

## Describe the bug

After updating to the latest version I now get a Server Error (500) message on logging in. 

## Steps To Reproduce
Log in!

## Expected behavior
To see the TA interface

After first encountering the issue I deleted all containers and volumes, and started from scratch, I still get the error.

### Relevant log output

```shell
startup checks run in other thread
231 static files copied to '/app/staticfiles', 971 post-processed.
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Mon Dec  5 09:19:30 2022] ***
compiled with version: 10.2.1 20210110 on 27 November 2022 11:28:57
os: Linux-5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
nodename: 1d037dfa64ae
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.8 (main, Nov 15 2022, 21:06:05) [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5626000d3c20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 154032 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
celery beat v5.2.7 (dawn-chorus) is starting.
startup checks run in other thread
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5626000d3c20 pid: 24 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24)
spawned uWSGI worker 1 (pid: 41, cores: 1)
startup checks run in other thread
startup checks run in other thread
__    -    ... __   -        _
LocalTime -> 2022-12-05 09:19:31
Configuration ->
    . broker -> redis://archivist-redis:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /cache/celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2022-12-05 09:19:31,115: INFO/MainProcess] beat: Starting...
/root/.local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!
Please specify a different user using the --uid option.
User information: uid=0 euid=0 gid=0 egid=0
  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@1d037dfa64ae v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.15.0-56-generic-x86_64-with-glibc2.31 2022-12-05 09:19:31
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f977c13fc40
- ** ---------- .> transport:   redis://archivist-redis:6379//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                
[tasks]
  . check_reindex
  . download_pending
  . home.tasks.download_single
  . home.tasks.extrac_dl
  . home.tasks.index_channel_playlists
  . home.tasks.re_sync_thumbs
  . home.tasks.rescan_filesystem
  . home.tasks.run_manual_import
  . home.tasks.run_restore_backup
  . home.tasks.subscribe_to
  . run_backup
  . thumbnail_check
  . update_subscribed
[2022-12-05 09:19:31,671: INFO/MainProcess] Connected to redis://archivist-redis:6379//
[2022-12-05 09:19:31,674: INFO/MainProcess] mingle: searching for neighbors
[2022-12-05 09:19:32,681: INFO/MainProcess] mingle: all alone
[2022-12-05 09:19:32,692: INFO/MainProcess] celery@1d037dfa64ae ready.
error=[object Object] error=[object Object] status=503
[pid: 41|app: 0|req: 1/1] 172.23.0.1 () {74 vars in 1397 bytes} [Mon Dec  5 09:20:10 2022] GET / => generated 145 bytes in 147 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)
error=[object Object] error=[object Object] status=503
[pid: 41|app: 0|req: 2/2] 172.23.0.1 () {76 vars in 1428 bytes} [Mon Dec  5 09:20:14 2022] GET / => generated 145 bytes in 43 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)




This is the only error I can see for es

2022-12-05T08:36:12.983680878Z exception during geoip databases update | @timestamp=2022-12-05T08:36:12.982Z log.level=ERROR ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[7c5fd01eb72a][generic][T#4] log.logger=org.elasticsearch.ingest.geoip.GeoIpDownloader elasticsearch.cluster.uuid=3JFW3XgxQua_UI3NHXkv4g elasticsearch.node.id=1R090K0sSMi6fgrN7slPKg elasticsearch.node.name=7c5fd01eb72a elasticsearch.cluster.name=docker-cluster error.type=org.elasticsearch.ElasticsearchException error.message=not all primary shards of [.geoip_databases] index are active error.stack_trace=org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
	at org.elasticsearch.ingest.geoip@8.5.1/org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:134)
	at org.elasticsearch.ingest.geoip@8.5.1/org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:274)
	at org.elasticsearch.ingest.geoip@8.5.1/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:102)
	at org.elasticsearch.ingest.geoip@8.5.1/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:48)
	at org.elasticsearch.server@8.5.1/org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42)
	at org.elasticsearch.server@8.5.1/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892)
	at org.elasticsearch.server@8.5.1/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2022-12-05T08:36:13.003725610Z Cluster health status changed from [YELLOW] to [RED] (reason: [state recovered]). | @timestamp=2022-12-05T08:36:13.002Z log.level=INFO current.health=RED previous.health=YELLOW reason=state recovered ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[7c5fd01eb72a][masterService#updateTask][T#1] log.logger=org.elasticsearch.cluster.routing.allocation.AllocationService elasticsearch.cluster.uuid=3JFW3XgxQua_UI3NHXkv4g elasticsearch.node.id=1R090K0sSMi6fgrN7slPKg elasticsearch.node.name=7c5fd01eb72a elasticsearch.cluster.name=docker-cluster
```

### Anything else?

[_archivist-es_logs.txt](https://github.com/tubearchivist/tubearchivist/files/10152716/_archivist-es_logs.txt)

**Comment by bbilly1** [comment]
Yeah, your ES is down. Your log output is not readable. Something wrong with the encoding? Maybe not enough storage on the ES volume?

**Comment by bbilly1** [comment]
You *say* you have read through the common errors, but a quick search for *watermark* revealed your problem pretty quickly.

**Comment by WillScott73** [comment]
> You _say_ you have read through the common errors, but a quick search for _watermark_ revealed your problem pretty quickly.

Apologies. As a web developer since 1991, I'm used to issues that cause internal server errors being logged as FATAL or ERROR, not WARN. I filtered the log lines for ERROR and didn't see any that mentioned a watermark. 

Thanks for your help though. I'll go figure out why 573Gb free space isn't sufficient now.
