### ISSUE TITLE
[Bug]: Thumbnail downloading error blocks video downloading

### ISSUE THREAD

**Issue by AlekseyLobanov** [tubearchivist/tubearchivist#396]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Docker in Ubuntu 20, kernel 5.4.0-125-generic

## Describe the bug
Unable to download single video. Now messages/errors in UI. 

## Steps To Reproduce
1. Add video with alias `BFOSuMc3hDc`
2. Press "Download now"

## Expected behavior
Video downloading succeeded

### Relevant log output

```shell
[2022-12-30 23:39:39,829: INFO/MainProcess] Task home.tasks.download_single[5a4e8959-d092-4ccd-88f8-79d1ff21089c] received
[2022-12-30 23:39:39,833: WARNING/ForkPoolWorker-4] Added to queue with priority: BFOSuMc3hDc
[2022-12-30 23:39:46,558: WARNING/ForkPoolWorker-4] BFOSuMc3hDc: get metadata from youtube
[2022-12-30 23:39:47,511: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: get metadata from es
[2022-12-30 23:39:47,521: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UCd_sTwKqVrweTt4oAKY5y4w","found":false}
[2022-12-30 23:39:47,522: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: scrape channel data from youtube
[2022-12-30 23:39:47,708: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: download channel thumbnail
[2022-12-30 23:39:52,755: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: retry thumbnail download https://yt3.ggpht.com/3ZWqY8gwuMEl6e2oV6WPMmJyPCAG3i_lL4malTRk8xUWtwGU54wLLJT4H6QdP8bB13ybkAuRVbM=s900-c-k-c0x00ffffff-no-rj
[2022-12-30 23:39:58,804: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: retry thumbnail download https://yt3.ggpht.com/3ZWqY8gwuMEl6e2oV6WPMmJyPCAG3i_lL4malTRk8xUWtwGU54wLLJT4H6QdP8bB13ybkAuRVbM=s900-c-k-c0x00ffffff-no-rj
[2022-12-30 23:40:05,843: WARNING/ForkPoolWorker-4] UCd_sTwKqVrweTt4oAKY5y4w: retry thumbnail download https://yt3.ggpht.com/3ZWqY8gwuMEl6e2oV6WPMmJyPCAG3i_lL4malTRk8xUWtwGU54wLLJT4H6QdP8bB13ybkAuRVbM=s900-c-k-c0x00ffffff-no-rj
[2022-12-30 23:40:14,854: ERROR/ForkPoolWorker-4] Task home.tasks.download_single[5a4e8959-d092-4ccd-88f8-79d1ff21089c] raised unexpected: AttributeError("'bool' object has no attribute 'convert'")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 120, in download_single
    VideoDownloader().run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 210, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 405, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 150, in build_json
    self._add_channel()
  File "/app/home/src/index/video.py", line 204, in _add_channel
    channel.build_json(upload=True, fallback=self.youtube_meta)
  File "/app/home/src/index/channel.py", line 183, in build_json
    self.get_from_youtube(fallback)
  File "/app/home/src/index/channel.py", line 199, in get_from_youtube
    self.get_channel_art()
  File "/app/home/src/index/channel.py", line 245, in get_channel_art
    ThumbManager(self.youtube_id, item_type="channel").download(urls)
  File "/app/home/src/download/thumbnails.py", line 99, in download
    self.download_channel_art(url)
  File "/app/home/src/download/thumbnails.py", line 149, in download_channel_art
    self._download_channel_thumb(channel_thumb, skip_existing)
  File "/app/home/src/download/thumbnails.py", line 164, in _download_channel_thumb
    img_raw.convert("RGB").save(thumb_path)
AttributeError: 'bool' object has no attribute 'convert'
```

**Comment by pairofcrocs** [comment]
Is it possible that you're having a networking issue? I'm able to download that channel with no issue.

Can you also confirm that these links work in your browser? [Channel](https://www.youtube.com/channel/UCd_sTwKqVrweTt4oAKY5y4w)and [Thumbnail](https://yt3.ggpht.com/3ZWqY8gwuMEl6e2oV6WPMmJyPCAG3i_lL4malTRk8xUWtwGU54wLLJT4H6QdP8bB13ybkAuRVbM=s900-c-k-c0x00ffffff-no-rj)

**Comment by AlekseyLobanov** [comment]
Channel is working, but thumbnail is unable to load.

I believe that video should be processed even if thumbnail or some channel information are not available.

Even if this resources are required for video to be processed, some useful error in Web UI is nice to see.

**Comment by bbilly1** [comment]
We've had it before with people from Russia. Most likely you are getting blocked either by your government or by YouTube... You can try to access the thumbnail url you posted in the log above to confirm. Use a proxy, VPN or anything similar to get around that. I think you'd rather want to fix this instead of setting all your artwork to the defaults.

**Comment by AlekseyLobanov** [comment]
>Most likely you are getting blocked either by your government or by YouTube...

I believe that this is correct reason. I do not have stable enough VPN to rely on.

Can it be a feature request: ignore/replace with placeholder problematic images?

**Comment by pairofcrocs** [comment]
I do agree that would be a better solution. Then on metadata refreshes it would try again for the correct thumbnail.

**Comment by hellofaduck** [comment]
I am from Russia too, and i can confirm that problem. Root of the problem in our goverment, they are blocking yt3.ggpht.com, where youtube static content is hosted. 
I use next solution to avoid this problem, as tubearchivist dont have a proxy option, i use my mikrotik router with complex firewall/routing rules to route all traffic to yt3.ggpht.com through vpn tunnel, and all other traffic to youtube videos directly through ISP (videos not blocked here). It's not a "turnkey" option to implement, but i hope it can direct you to similar solution that suites your setup.

**Comment by bbilly1** [comment]
I think Tube Archivist should fail here. The point of having a nice frontend for yt-dlp like Tube Archivist, is so you can get the artwork and all that related stuff. If external factors block you from accessing that, you should fix that first before using this project. 

The fix is not difficult, if you are living in a country that blocks some of the internet, I'm sure you'll be familiar with the workarounds.
