### ISSUE TITLE
[Bug]: Unable to launch after loss of power

### ISSUE THREAD

**Issue by matiasvc** [tubearchivist/tubearchivist#399]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Synology

## Describe the bug

I am running Tube Archivist on a Synology server. I recently had a power loss which forced the Synology NAS to reboot. Now I cannot launch the `tubearchivist` docker container properly because of a python error. As shown in the log I have attached below.

## Steps To Reproduce

Not sure. But this started happening after the Synology NAS had a power loss.

## Expected behavior

I would expect the docker container to launch without error as it used to before the power loss.

### Relevant log output

```shell
{
  "name" : "tubearchivist-es",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "6xOBuh-PSXyN7ZjsOyonyg",
  "version" : {
    "number" : "8.5.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "c1310c45fc534583afe2c1c03046491efba2bba2",
    "build_date" : "2022-11-09T21:02:20.169855900Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.1",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
run startup checks
elasticsearch version check passed
sync redis
ta_channel index is created and up to date...
ta_video index is created and up to date...
ta_download index is created and up to date...
ta_playlist index is created and up to date...
ta_subtitle index is created and up to date...
ta_comment index is created and up to date...
clear download cache
snapshot: run setup
{"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"},"status":404}
snapshot: setup repo ta_snapshot config {'compress': 'true', 'chunk_size': '1g', 'location': '/usr/share/elasticsearch/data/snapshot'}
{"error":{"root_cause":[{"type":"repository_exception","reason":"[ta_snapshot] location [/usr/share/elasticsearch/data/snapshot] doesn't match any of the locations specified by path.repo because this setting is empty"}],"type":"repository_exception","reason":"[ta_snapshot] failed to create repository","caused_by":{"type":"repository_exception","reason":"[ta_snapshot] location [/usr/share/elasticsearch/data/snapshot] doesn't match any of the locations specified by path.repo because this setting is empty"}},"status":500}
{"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"},"status":404}
snapshot: create policy ta_daily {'schedule': '0 0 11 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such repository [ta_snapshot]"}],"type":"illegal_argument_exception","reason":"no such repository [ta_snapshot]"},"status":400}
{'schedule': '0 0 11 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/home/apps.py", line 135, in ready
    startup.run()
  File "/app/home/apps.py", line 36, in run
    self.snapshot_check()
  File "/app/home/apps.py", line 94, in snapshot_check
    ElasticSnapshot().setup()
  File "/app/home/src/es/snapshot.py", line 45, in setup
    self.create_policy()
  File "/app/home/src/es/snapshot.py", line 105, in create_policy
    response, statuscode = ElasticWrap(path).put(data)
  File "/app/home/src/es/connect.py", line 74, in put
    raise ValueError("failed to add item to index")
ValueError: failed to add item to index
```

**Comment by bbilly1** [comment]
This might not be related to the power loss.

`"[ta_snapshot] failed to create repository"` this suggests that you might have activated snapshots on the settings page without configuring the required env var first? [wiki](https://github.com/tubearchivist/tubearchivist/wiki/Settings#snapshots).

Also make sure you actually pulled the newest image, maybe after the reboot you encountered an update and ran into this #372?

**Comment by matiasvc** [comment]
Thanks. That did the trick. Added the `path.repo` environment variable to the es container and rebuilt. Now everything works again.
