### ISSUE TITLE
[Bug]: Thumbnail "decoder object" hard error

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#430]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

## Describe the bug
I was running into a similar error to the below when running a channel scan and could not diagnose the culprit, so manually downloaded the channel and during import, identified that the webp image produced apeares to be malformed.  When this issue occurs during channel scan or manual import, the task is killed with the error below.

## Steps To Reproduce
Ref the above.  Github does not support webp, so image can't be attached for reference.

## Expected behavior
Perhaps make a 2nd attempt, then throw away the malformed image and apply the default TA image and continue with next item in queue

### Relevant log output

```shell
[2023-02-13 23:24:52,096: ERROR/ForkPoolWorker-33] Task home.tasks.run_manual_import[afa3e61a-1385-47e9-96d6-decd461b1e2f] raised unexpected: OSError('could not create decoder object')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 188, in run_manual_import
    ImportFolderScanner().scan()
  File "/app/home/src/index/filesystem.py", line 188, in scan
    self.process_videos()
  File "/app/home/src/index/filesystem.py", line 271, in process_videos
    self._convert_thumb(current_video)
  File "/app/home/src/index/filesystem.py", line 397, in _convert_thumb
    img_raw = Image.open(thumb_path)
  File "/root/.local/lib/python3.10/site-packages/PIL/Image.py", line 3268, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/root/.local/lib/python3.10/site-packages/PIL/Image.py", line 3254, in _open_core
    im = factory(fp, filename)
  File "/root/.local/lib/python3.10/site-packages/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/root/.local/lib/python3.10/site-packages/PIL/WebPImagePlugin.py", line 63, in _open
    self._decoder = _webp.WebPAnimDecoder(self.fp.read())
OSError: could not create decoder object
```

**Comment by PhuriousGeorge** [comment]
I probably should have added this to #425 .  Different error but should be handled the same.

**Comment by bbilly1** [comment]
Ay, manual import. :-( So am I seeing this right, the thumbnail throwing the error is added manually by you? That's not the one from YT?

**Comment by PhuriousGeorge** [comment]
Nope I don't manually add anything (other than offline imports), it's the thumbnail that was downloaded by yt-dlp.  Might have been the same one from #425 when I gave up and manually downloaded.  I can confirm the thumbnail was corrupted.  Windows couldn't even view it.

**Comment by PhuriousGeorge** [comment]
Adding that videos affected are `Dh0XFpQ-OVk` & `A6lzI016npA` that I've found so far

**Comment by bbilly1** [comment]
Thanks for reporting, v0.3.3 will now use the fallback thumbnails in these cases.
