### ISSUE TITLE
[Bug]: Immediate errors for new deployment with unstable `73da59f`

### ISSUE THREAD

**Issue by lamusmaser** [tubearchivist/tubearchivist#434]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Synology/Docker-Compose

## Describe the bug
When starting a new instance, there are immediate errors coming through.

## Steps To Reproduce
Pull unstable release associated to [73da59f](https://github.com/tubearchivist/tubearchivist/commit/73da59ffbfd42aa331dc56798a369a4e04f89d6e).
Deploy as new instance.

## Expected behavior
Errors should either be remediated or caught-and-handled appropriately.

### Relevant log output

```shell
root@<system>:<dir># ./ytdl-test-repave.sh
Network TubeArchivist-backend is external, skipping
Removing network TubeArchivist-test-frontend
Pulling tubearchivist-test-es    ... done
Pulling tubearchivist-test-redis ... done
Pulling tubearchivist-test-ws    ... done
Creating network "TubeArchivist-test-frontend" with the default driver
Creating tubearchivist-test-es ... done
Creating tubearchivist-test-redis ... done
Creating tubearchivist-test       ... done
root@<system>:<dir># docker logs -f tubearchivist-test
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 317, in <module>
    app.conf.beat_schedule = ScheduleBuilder().build_schedule()
  File "/app/home/src/ta/config.py", line 281, in build_schedule
    minute=item_conf["minute"],
TypeError: string indices must be integers
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying home.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK

231 static files copied to '/app/staticfiles', 971 post-processed.


    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    ✓ new superuser with name tubearchivist created


    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
    ... waiting for ES [1/24]
    ... waiting for ES [2/24]
    ✓ ES connection established
[4] Elastic Search version check
    ✓ ES version check passed
[5] check ES path.repo env var
    ✓ path.repo env var is set


[1] set new config.json values
    no new config values
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover locks in redis
    no locks found
[4] clear leftover files from dl cache
clear download cache
    no files found
[5] check for first run after update
    no new update found
[MIGRATION] validate index mappings
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"}],"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"},"status":404}
create new blank index with name ta_channel...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"}],"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"},"status":404}
create new blank index with name ta_video...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"}],"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"},"status":404}
create new blank index with name ta_download...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"}],"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"},"status":404}
create new blank index with name ta_playlist...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"}],"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"},"status":404}
create new blank index with name ta_subtitle...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"}],"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"},"status":404}
create new blank index with name ta_comment...
[MIGRATION] setup snapshots
snapshot: run setup
{"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"},"status":404}
snapshot: setup repo ta_snapshot config {'compress': 'true', 'chunk_size': '1g', 'location': '/usr/share/elasticsearch/data/snapshot'}
snapshot: repo setup correctly: {'acknowledged': True}
{"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"},"status":404}
snapshot: create policy ta_daily {'schedule': '0 0 19 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
snapshot: policy setup correctly: {'acknowledged': True}
snapshots: no snapshots found
snapshot: create initial snapshot
snapshot: executing now: {'snapshot_name': 'ta_daily_-1tekdtporsqkqdcnc20iyw'}
[MIGRATION] set default vid_type
    no videos needed updating in ta_video
    no videos needed updating in ta_download
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Fri Feb 17 10:20:55 2023] ***
nodename: 86fb34ec6feb
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
detected max file descriptor number: 524288
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
Python version: 3.10.9 (main, Feb  4 2023, 11:55:23) [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x564138cf1d30
mapped 154032 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
celery beat v5.2.7 (dawn-chorus) is starting.
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x564138cf1d30 pid: 20 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
spawned uWSGI worker 1 (pid: 29, cores: 1)
/root/.local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

 -------------- celery@86fb34ec6feb v5.2.7 (dawn-chorus)
__    -    ... __   -        _
LocalTime -> 2023-02-17 10:20:59
    . maxinterval -> 5.00 minutes (300s)
[2023-02-17 10:20:59,484: INFO/MainProcess] beat: Starting...
[2023-02-17 10:20:59,918: INFO/MainProcess] Connected to redis://tubearchivist-test-redis:6379//
[2023-02-17 10:20:59,929: INFO/MainProcess] mingle: searching for neighbors
[2023-02-17 10:21:00,949: INFO/MainProcess] mingle: all alone
[2023-02-17 10:21:00,991: INFO/MainProcess] celery@86fb34ec6feb ready.
```

### Anything else?

This might be able to be ignored, however posting as part of the manual testing for unstable builds. Looking into reasons for the error to determine if this can be safely ignored, can be updated to be caught appropriately, or if there is a larger issue for new instances that is causing this.

Additional note: `redislabs/rejson` caused this error and had an immediate fatal error for TA. Could not move forward after receiving this error. Required to be on `redis/redis-stack-server` going forward for new builds.

**Comment by lamusmaser** [comment]
For reference, here is the log where TA just died, when it was using `redislabs/json`. No additional logs, did not attempt to restart. sat at this point for over five minutes and did not progress.

```
root@<system>:<dir># ./ytdl-test-repave.sh
Stopping tubearchivist-test       ... done
Stopping tubearchivist-test-redis ... done
Stopping tubearchivist-test-es    ... done
Removing tubearchivist-test       ... done
Removing tubearchivist-test-redis ... done
Removing tubearchivist-test-es    ... done
Network TubeArchivist-backend is external, skipping
Removing network TubeArchivist-test-frontend
Pulling tubearchivist-test-es    ... done
Pulling tubearchivist-test-redis ... done
Pulling tubearchivist-test-ws    ... done
Creating network "TubeArchivist-test-frontend" with the default driver
Creating tubearchivist-test-es ... done
Creating tubearchivist-test-redis ... done
Creating tubearchivist-test       ... done
root@<system>:<dir># docker logs -f tubearchivist-test
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unl
```

**Comment by lamusmaser** [comment]
New build now runs without errors.

```
root@<system>:<dir># ./ytdl-test-repave.sh
Stopping tubearchivist-test       ... done
Stopping tubearchivist-test-redis ... done
Stopping tubearchivist-test-es    ... done
Removing tubearchivist-test       ... done
Removing tubearchivist-test-redis ... done
Removing tubearchivist-test-es    ... done
Network TubeArchivist-backend is external, skipping
Removing network TubeArchivist-test-frontend
Pulling tubearchivist-test-es    ... done
Pulling tubearchivist-test-redis ... done
Pulling tubearchivist-test-ws    ... done
Creating network "TubeArchivist-test-frontend" with the default driver
Creating tubearchivist-test-es ... done
Creating tubearchivist-test-redis ... done
root@<system>:<dir># docker logs -f tubearchivist-test
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying home.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK

231 static files copied to '/app/staticfiles', 971 post-processed.


    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
    TA_PORT is not set
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    ✓ new superuser with name tubearchivist created


#######################
#  Connection check   #
#######################

[1] connect to Redis
    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
    ... waiting for ES [1/24]
    ✓ ES connection established
[4] Elastic Search version check
    ✓ ES version check passed
[5] check ES path.repo env var
    ✓ path.repo env var is set


#######################
#######################

[1] set new config.json values
    no new config values
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover locks in redis
    no locks found
[4] clear leftover files from dl cache
clear download cache
    no files found
[5] check for first run after update
    no new update found
[MIGRATION] validate index mappings
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"}],"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"},"status":404}
create new blank index with name ta_channel...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"}],"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"},"status":404}
create new blank index with name ta_video...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"}],"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"},"status":404}
create new blank index with name ta_download...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"}],"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"},"status":404}
create new blank index with name ta_playlist...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"}],"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"},"status":404}
create new blank index with name ta_subtitle...
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"}],"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"},"status":404}
create new blank index with name ta_comment...
[MIGRATION] setup snapshots
snapshot: run setup
{"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"},"status":404}
snapshot: setup repo ta_snapshot config {'compress': 'true', 'chunk_size': '1g', 'location': '/usr/share/elasticsearch/data/snapshot'}
snapshot: repo setup correctly: {'acknowledged': True}
{"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"},"status":404}
snapshot: create policy ta_daily {'schedule': '0 0 19 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
snapshot: policy setup correctly: {'acknowledged': True}
snapshots: no snapshots found
snapshot: create initial snapshot
snapshot: executing now: {'snapshot_name': 'ta_daily_-eib2gsawtiiw6uwzssdxrw'}
[MIGRATION] set default vid_type
    no videos needed updating in ta_video
    no videos needed updating in ta_download
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Fri Feb 17 20:17:59 2023] ***
compiled with version: 10.2.1 20210110 on 17 February 2023 14:00:04
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55e395b00d30
mapped 154032 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
celery beat v5.2.7 (dawn-chorus) is starting.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55e395b00d30 pid: 20 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
spawned uWSGI worker 1 (pid: 29, cores: 1)
/root/.local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
__    -    ... __   -        _
LocalTime -> 2023-02-17 20:18:02
[2023-02-17 20:18:02,077: INFO/MainProcess] beat: Starting...
Configuration ->
    . broker -> redis://tubearchivist-test-redis:6379//
    . loader -> celery.loaders.app.AppLoader
    . db -> /celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)

 -------------- celery@24a2e969aeeb v5.2.7 (dawn-chorus)
--- ***** -----
-- ******* ---- Linux-4.4.59+-x86_64-with-glibc2.31 2023-02-17 20:18:02
- *** --- * ---
- ** ---------- .> app:         tasks:0x7fd92907c9a0
- ** ---------- .> transport:   redis://tubearchivist-test-redis:6379//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . check_reindex
  . download_pending
  . home.tasks.download_single
  . home.tasks.extrac_dl
  . home.tasks.index_channel_playlists
  . home.tasks.re_sync_thumbs
  . home.tasks.rescan_filesystem
  . home.tasks.run_manual_import
  . home.tasks.run_restore_backup
  . home.tasks.subscribe_to
  . run_backup
  . thumbnail_check
  . update_subscribed
  . version_check

[2023-02-17 20:18:02,530: INFO/MainProcess] Connected to redis://tubearchivist-test-redis:6379//
[2023-02-17 20:18:02,535: INFO/MainProcess] mingle: searching for neighbors
[2023-02-17 20:18:03,554: INFO/MainProcess] mingle: all alone
[2023-02-17 20:18:03,585: INFO/MainProcess] celery@24a2e969aeeb ready.
```

**Comment by lamusmaser** [comment]
Looks like we are good to close out this issue. No additional errors or concern found with latest unstable build.
