### ISSUE TITLE
[Bug]: Subtitle error during download or manual import

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#435]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

## Describe the bug
Had a similar to the below error during a download queue, so manually downloaded the videos missing from my archive and decided to address later.  Same issue occurs during manual import.  Appears to be another subtitle error?

## Steps To Reproduce
Ref video id `21X5lGlDOfg` or `nA9UZF-SZoQ`

### Relevant log output

```shell
[2023-02-18 04:40:47,649: WARNING/ForkPoolWorker-32] 21X5lGlDOfg: get metadata from youtube
[2023-02-18 04:40:50,339: WARNING/ForkPoolWorker-32] UCLA_DiR1FfKNvjuUpBHmylQ: get metadata from es
[2023-02-18 04:40:50,495: WARNING/ForkPoolWorker-32] 21X5lGlDOfg: get ryd stats
[2023-02-18 04:40:50,739: WARNING/ForkPoolWorker-32] 21X5lGlDOfg: get sponsorblock timestamps
[2023-02-18 04:40:50,885: WARNING/ForkPoolWorker-32] 21X5lGlDOfg: sponsorblock failed: 404
[2023-02-18 04:40:50,886: WARNING/ForkPoolWorker-32] 21X5lGlDOfg-en: get user uploaded subtitles
[2023-02-18 04:40:50,886: WARNING/ForkPoolWorker-32] 21X5lGlDOfg-en: get auto generated subtitles
[2023-02-18 04:40:50,889: ERROR/ForkPoolWorker-32] Task home.tasks.run_manual_import[55c85b4d-80b5-4110-893a-4fa20d56355c] raised unexpected: IndexError('list index out of range')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 188, in run_manual_import
    ImportFolderScanner().scan()
  File "/app/home/src/index/filesystem.py", line 188, in scan
    self.process_videos()
  File "/app/home/src/index/filesystem.py", line 276, in process_videos
    ManualImport(current_video, self.CONFIG).run()
  File "/app/home/src/index/filesystem.py", line 508, in run
    json_data = self.index_metadata()
  File "/app/home/src/index/filesystem.py", line 524, in index_metadata
    video.check_subtitles(subtitle_files=self.current_video["subtitle"])
  File "/app/home/src/index/video.py", line 377, in check_subtitles
    subtitles = handler.get_subtitles()
  File "/app/home/src/index/subtitle.py", line 45, in get_subtitles
    auto_cap = self._get_auto_caption(lang)
  File "/app/home/src/index/subtitle.py", line 65, in _get_auto_caption
    subtitle = [i for i in all_formats if i["ext"] == "json3"][0]
IndexError: list index out of range
```

**Comment by PhuriousGeorge** [comment]
Thought I remembered this.  Now I've got more info from the more detailed logs than I did when reporting #315

**Comment by bbilly1** [comment]
So these two videos are live streams currently streaming. You shouldn't have been able to add these to the download queue. Are you subscribed to the NASA channel and a refresh added these to the queue?

**Comment by PhuriousGeorge** [comment]
They can't be currently streaming... they started 2018-12-28 & 2019-02-14 respectively...

After digging in, these appear to be some kind of video rotating continuous stream (TV channel-esque)... I didn't know that was a thing.

Anywho, to your question - no, my TA queue was over 10k when I was re-scanning my whole library, so I exported the queue and manually downloaded (in this case, I think it was easier to export what was downloaded and use that to exclude from a full pull with yt-dlp).  This is probably what I've experienced before as well, as I tend to do this a lot, especially when archiving large channels.

**Comment by bbilly1** [comment]
They are currently streaming at least for yt-dlp, yes, that's since 2018:
![2023-02-20_10-47-45-screenshot](https://user-images.githubusercontent.com/35427372/220005484-10db748c-c555-4986-ac3d-e965cdbff643.png)

Indicated on the *live* status there. Also indicated that this video doesn't have a duration.

Past streams are different:
![2023-02-20_10-49-22-screenshot](https://user-images.githubusercontent.com/35427372/220005666-9bf0fd87-5488-411d-83e0-b25272ac97f7.png)

They have a date when completed, and have a duration.

Tube Archivist can't deal with live streams that are currently streaming, so they are filtered out in the add to download queue task. They will get added once the stream is completed and becomes a *regular* video.

> so I exported the queue and manually downloaded

If you want to do something like that, you'll have to filter out these streams.

Something like `--match-filters '!is_live'` might do that.
