### ISSUE TITLE
[Bug]: Redis Connection String does not work for FQDNS

### ISSUE THREAD

**Issue by mitchross** [tubearchivist/tubearchivist#438]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux / K8s 

### Your Bug Report

It appears that passing a DNS address to the redis host variable causes redis python client  to not connect.

 REDIS_HOST: redis-lb.default.svc.cluster.local
 
 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1474, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 13, in <module>
    from home.src.download.queue import PendingList
  File "/app/home/src/download/queue.py", line 10, in <module>
    from home.src.download.subscriptions import (
  File "/app/home/src/download/subscriptions.py", line 8, in <module>
    from home.src.download.thumbnails import ThumbManager
  File "/app/home/src/download/thumbnails.py", line 22, in <module>
    class ThumbManagerBase:
  File "/app/home/src/download/thumbnails.py", line 25, in ThumbManagerBase
    CONFIG = AppConfig().config
  File "/app/home/src/ta/config.py", line 23, in __init__
    self.config = self.get_config()
  File "/app/home/src/ta/config.py", line 28, in get_config
    config = self.get_config_redis()
  File "/app/home/src/ta/config.py", line 70, in get_config_redis
    config = RedisArchivist().get_message("config")
  File "/app/home/src/ta/ta_redis.py", line 52, in get_message
    reply = self.conn.execute_command("JSON.GET", self.NAME_SPACE + key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1476, in get_connection
    connection = self.make_connection()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1516, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 633, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'tcp://10.43.2.213:6379'
```

**Comment by bbilly1** [comment]
I don't see why this wouldn't work. I tried to recreate it with docker compose:

For Tube Archivist:
```
REDIS_HOST=redis-lb.default.svc.cluster.local
```

For Redis: 
```yml
archivist-redis:
  image: redis/redis-stack-server
  container_name: redis-lb.default.svc.cluster.local
  restart: unless-stopped
  expose:
    - "6379"
  volumes:
    - ./volume/tubearchivist/redis:/data
```

And everything comes up fine:
```
tubearchivist  | [1] connect to Redis
tubearchivist  |     ✓ Redis connection verified
tubearchivist  | [2] set Redis config
tubearchivist  |     ✓ Redis config set
tubearchivist  | [3] connect to Elastic Search
tubearchivist  |     ... waiting for ES [0/24]
tubearchivist  |     ✓ ES connection established
tubearchivist  | [4] Elastic Search version check
tubearchivist  |     ✓ ES version check passed
tubearchivist  | [5] check ES path.repo env var
tubearchivist  |     ✓ path.repo env var is set
```
Same Celery connects fine:
```
tubearchivist  |  -------------- celery@784c9b3a3d7b v5.2.7 (dawn-chorus)
tubearchivist  | --- ***** -----
tubearchivist  | -- ******* ---- Linux-5.15.0-60-generic-x86_64-with-glibc2.31 2023-02-20 09:40:22
tubearchivist  | - *** --- * ---
tubearchivist  | - ** ---------- [config]
tubearchivist  | - ** ---------- .> app:         tasks:0x7f7abac9a8f0
tubearchivist  | - ** ---------- .> transport:   redis://redis-lb.default.svc.cluster.local:6379//
tubearchivist  | - ** ---------- .> results:     disabled://
tubearchivist  | - *** --- * --- .> concurrency: 4 (prefork)
tubearchivist  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
tubearchivist  | --- ***** -----
tubearchivist  |  -------------- [queues]
tubearchivist  |                 .> celery           exchange=celery(direct) key=celery

```

As well the worker too:
```
tubearchivist  | [2023-02-20 09:40:23,261: INFO/MainProcess] Connected to redis://redis-lb.default.svc.cluster.local:6379//
```

The traceback suggests some issue with the port? Not sure what you have it set to, but Tube Archivist will fallback to the default `6379` if you didn't set `REDIS_PORT`.

**Comment by mitchross** [comment]
Yup, I have redis on port 6379, so the fallback should have also worked regardless, right?

**Comment by bbilly1** [comment]
Fallback only gets applied, if you don't set anything yourself.

I don't think I can be of any further help here. I'd suggest to either use the chart provided by @insuusvenerati, if you encounter any problems, report them there. 

Discord is the better place for these discussions and for learning the inner workings of Kubernetes networking, let's keep these issues here relevant to Tube Archivist.
