### ISSUE TITLE
[Bug]: Previously failed migration left ta_video_backup, now failing update

### ISSUE THREAD

**Issue by Jay4242** [tubearchivist/tubearchivist#439]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux, docker-compose

## Describe the bug
Starting v0.3.3 results in an error for me.
## Steps To Reproduce
I simply ran sudo docker-compose pull && sudo docker-compose down && sudo docker-compose up -d; to upgrade the server.
## Expected behavior
Tubearchivist to start completely.

### Relevant log output

```shell
ESC[32mtubearchivist      |ESC[0m backup: export in progress for comment
ESC[32mtubearchivist      |ESC[0m applying new mappings to index ta_video...
ESC[32mtubearchivist      |ESC[0m create new blank index with name ta_video...
ESC[32mtubearchivist      |ESC[0m {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [ta_video_backup/NFWlHPCiS5K4tOHTORwjHQ] already exists","index_uuid":"NFW
lHPCiS5K4tOHTORwjHQ","index":"ta_video_backup"}],"type":"resource_already_exists_exception","reason":"index [ta_video_backup/NFWlHPCiS5K4tOHTORwjHQ] already exists","index_uuid":"NFWlHPCiS5K4t
OHTORwjHQ","index":"ta_video_backup"},"status":400}
ESC[32mtubearchivist      |ESC[0m {'settings': {'analysis': {'normalizer': {'to_lower': {'type': 'custom', 'filter': ['lowercase']}}}, 'number_of_replicas': '0'}, 'mappings': {'properties': {'
vid_thumb_url': {'type': 'text', 'index': False}, 'vid_thumb_base64': {'type': 'text', 'index': False}, 'date_downloaded': {'type': 'date'}, 'channel': {'properties': {'channel_id': {'type': '
keyword'}, 'channel_name': {'type': 'text', 'analyzer': 'english', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256, 'normalizer': 'to_lower'}, 'search_as_you_type': {'type': 'sea
rch_as_you_type', 'doc_values': False, 'max_shingle_size': 3}}}, 'channel_banner_url': {'type': 'keyword', 'index': False}, 'channel_tvart_url': {'type': 'keyword', 'index': False}, 'channel_t
humb_url': {'type': 'keyword', 'index': False}, 'channel_description': {'type': 'text'}, 'channel_last_refresh': {'type': 'date'}, 'channel_overwrites': {'properties': {'download_format': {'ty
pe': 'text'}, 'autodelete_days': {'type': 'long'}, 'index_playlists': {'type': 'boolean'}, 'integrate_sponsorblock': {'type': 'boolean'}}}}}, 'description': {'type': 'text'}, 'media_url': {'ty
pe': 'keyword', 'index': False}, 'tags': {'type': 'text', 'analyzer': 'english', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256}}}, 'title': {'type': 'text', 'analyzer': 'englis
h', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256, 'normalizer': 'to_lower'}, 'search_as_you_type': {'type': 'search_as_you_type', 'doc_values': False, 'max_shingle_size': 3}}}
, 'vid_last_refresh': {'type': 'date'}, 'youtube_id': {'type': 'keyword'}, 'vid_type': {'type': 'keyword'}, 'published': {'type': 'date'}, 'playlist': {'type': 'text', 'fields': {'keyword': {'
type': 'keyword', 'ignore_above': 256, 'normalizer': 'to_lower'}}}, 'comment_count': {'type': 'long'}, 'stats': {'properties': {'average_rating': {'type': 'float'}, 'dislike_count': {'type': '
long'}, 'like_count': {'type': 'long'}, 'view_count': {'type': 'long'}}}, 'subtitles': {'properties': {'ext': {'type': 'keyword', 'index': False}, 'lang': {'type': 'keyword', 'index': False},
'media_url': {'type': 'keyword', 'index': False}, 'name': {'type': 'keyword'}, 'source': {'type': 'keyword'}, 'url': {'type': 'keyword', 'index': False}}}, 'sponsorblock': {'properties': {'last_refresh': {'type': 'date'}, 'has_unlocked': {'type': 'boolean'}, 'is_enabled': {'type': 'boolean'}, 'segments': {'properties': {'UUID': {'type': 'keyword'}, 'actionType': {'type': 'keyword'}, 'category': {'type': 'keyword'}, 'locked': {'type': 'short'}, 'segment': {'type': 'float'}, 'videoDuration': {'type': 'float'}, 'votes': {'type': 'long'}}}}}}}}
ESC[32mtubearchivist      |ESC[0m Traceback (most recent call last):
ESC[32mtubearchivist      |ESC[0m   File "/app/manage.py", line 23, in <module>
ESC[32mtubearchivist      |ESC[0m     main()
ESC[32mtubearchivist      |ESC[0m   File "/app/manage.py", line 19, in main
ESC[32mtubearchivist      |ESC[0m     execute_from_command_line(sys.argv)
ESC[32mtubearchivist      |ESC[0m   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
ESC[32mtubearchivist      |ESC[0m     utility.execute()
ESC[32mtubearchivist      |ESC[0m   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
ESC[32mtubearchivist      |ESC[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
ESC[32mtubearchivist      |ESC[0m   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
ESC[32mtubearchivist      |ESC[0m     self.execute(*args, **cmd_options)
ESC[32mtubearchivist      |ESC[0m   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
ESC[32mtubearchivist      |ESC[0m     output = self.handle(*args, **options)
ESC[32mtubearchivist      |ESC[0m   File "/app/config/management/commands/ta_startup.py", line 39, in handle
ESC[32mtubearchivist      |ESC[0m     self._mig_index_setup()
ESC[32mtubearchivist      |ESC[0m   File "/app/config/management/commands/ta_startup.py", line 124, in _mig_index_setup
ESC[32mtubearchivist      |ESC[0m     ElasitIndexWrap().setup()
ESC[32mtubearchivist      |ESC[0m   File "/app/home/src/es/index_setup.py", line 161, in setup
ESC[32mtubearchivist      |ESC[0m     handler.rebuild_index()
ESC[32mtubearchivist      |ESC[0m   File "/app/home/src/es/index_setup.py", line 99, in rebuild_index
ESC[32mtubearchivist      |ESC[0m     self.create_blank(for_backup=True)
ESC[32mtubearchivist      |ESC[0m   File "/app/home/src/es/index_setup.py", line 139, in create_blank
ESC[32mtubearchivist      |ESC[0m     _, _ = ElasticWrap(path).put(data)
ESC[32mtubearchivist      |ESC[0m   File "/app/home/src/es/connect.py", line 77, in put
ESC[32mtubearchivist      |ESC[0m     raise ValueError("failed to add item to index")
ESC[32mtubearchivist      |ESC[0m ValueError: failed to add item to index
ESC[35mtubearchivist      |ESC[0m Operations to perform:
ESC[35mtubearchivist      |ESC[0m   Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
ESC[35mtubearchivist      |ESC[0m Running migrations:
ESC[35mtubearchivist      |ESC[0m   No migrations to apply.
ESC[35mtubearchivist      |ESC[0m Deleting 'script.js.gz'
ESC[35mtubearchivist      |ESC[0m Deleting 'progress.288ea0da34d8.js'
```

**Comment by bbilly1** [comment]
> {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [ta_video_backup/NFWlHPCiS5K4tOHTORwjHQ] already exists","index_uuid":"NFW
lHPCiS5K4tOHTORwjHQ","index":"ta_video_backup"}]

You see, that's why we need to switch to snapshots, finally! So we don't need to mess with that any more. An old migration failed, keeping the *ta_video_backup* index around. So basically, stop the TA container, open a bash shell into your Elastic Search container and run:

```bash
curl -XDELETE -u elastic:verysecret localhost:9200/ta_video_backup
```

Then you should be able to start the TA container again. Make sure you have set the path.repo env var and after starting, activate snapshot on your settings page.

don't forget to change the *verysecret* password there to your real ES password.

**Comment by Jay4242** [comment]
Yay!  Thanks!  That worked.
```
sudo docker exec -it archivist-es /bin/bash
curl -XDELETE -u elastic:verysecret localhost:9200/ta_video_backup
```
Cleared it up and everything restarted.
