### ISSUE TITLE
[Bug]: Rescan filesystem crashes if video made private or not found

### ISSUE THREAD

**Issue by DeaeLunae** [tubearchivist/tubearchivist#440]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux (arch, using docker)

## Describe the bug

Re-scanned filesystem from deleted ES data. Every time it ran into a video no longer available on YT, it crashed entirely, failing not just the video in question, but also halting the remaining scan.

## Steps To Reproduce

Sample file available on request. Simply have a file in your media volume previously downloaded from TA. Tested with a file that did not originate from TA as well but name formatted like TA. Either file can be make available.

## Expected behavior

Error log or ability to manually add missing data would be ideal, but at the very least should not abort the remainder of the scan.

### Relevant log output

```shell
[2023-02-22 22:47:35,986: WARNING/ForkPoolWorker-4] index new videos
[2023-02-22 22:47:35,990: WARNING/ForkPoolWorker-4] B5IbSOo4o5o: get metadata from youtube
[2023-02-22 22:47:36,461: WARNING/ForkPoolWorker-4] ERROR: [youtube] B5IbSOo4o5o: Private video. Sign in if you've been granted access to this video
[2023-02-22 22:47:36,461: WARNING/ForkPoolWorker-4] https://www.youtube.com/watch?v=B5IbSOo4o5o: failed to get info from youtube
[2023-02-22 22:47:36,462: ERROR/ForkPoolWorker-4] Task home.tasks.rescan_filesystem[e1bfe6bc-a0bf-4cb3-b7a1-84df5d153853] raised unexpected: ValueError('failed to get metadata for B5IbSOo4o5o')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 246, in rescan_filesystem
    scan_filesystem()
  File "/app/home/src/index/filesystem.py", line 607, in scan_filesystem
    index_new_video(youtube_id)
  File "/app/home/src/index/video.py", line 417, in index_new_video
    raise ValueError("failed to get metadata for " + youtube_id)
ValueError: failed to get metadata for B5IbSOo4o5o
```

**Comment by bbilly1** [comment]
*Crashing* is a bit harsh. It fails as expected.

I think it makes more sense to let you know, that there is an unsolvable problem than just ignoring it and continue. This way you don't have to go back and see what exactly got imported or go through some potentially huge log file. Additionally, it will fail again next time you run the rescan.

So this is working as intended, you'll have to either take out the video file, or add the metadata separately with manual import.

I'll add a mention in the docs about that.
