### ISSUE TITLE
[Installation]: ElasticSearch Doesnt work with tubearchivist

### ISSUE THREAD

**Issue by ArnoldLaynee** [tubearchivist/tubearchivist#472]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux

### Your installation or setup question

ElasticSearch Doesnt work i Double Checked my docker-compose file I changed permissons I just dont know what to do 

### Relevant log output

```shell
Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false]. error.stack_trace=org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:960)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.lambda$new$16(Node.java:722)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.plugins.PluginsService.lambda$flatMap$0(PluginsService.java:254)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.<init>(Node.java:737)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.<init>(Node.java:324)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)
	at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)

ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log

ERROR: Elasticsearch exited unexpectedly




version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8050:8000
    volumes:
      - /media/500gb/basedtube/media:/youtube
      - /media/500gb/basedtube/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.local         # set your host name
      - TA_USERNAME=PlaceHolder            # your initial TA credentials
      - TA_PASSWORD=PlaceHolder              # your initial TA credentials
      - ELASTIC_PASSWORD=PlaceHolder         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /media/500gb/basedtube/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=PlaceHolder"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /media/500gb/basedtube/data:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
```

**Comment by lamusmaser** [comment]
Can you give us some details of your system? What hardware is this running on, what is the operating system, what architecture is it running on? `uname` can give some of those details.

**Comment by ArnoldLaynee** [comment]
> Can you give us some details of your system? What hardware is this running on, what is the operating system, what architecture is it running on? `uname` can give some of those details.

Sure I am running Ubuntu Server This Error Comes from the docker container My plan was to use this on my home server so my Hardware isnt the that good but it should be enough I have 4gb of ram My Cpu is Amd Athleon 2 X2 260

And uname -a command gave me this info 
`Linux knscp 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by lamusmaser** [comment]
Thank you. Can you also provide the full ES logs?

**Comment by ArnoldLaynee** [comment]
[_archivist-es_logs(1).txt](https://github.com/tubearchivist/tubearchivist/files/11360389/_archivist-es_logs.1.txt)
Here you go

**Comment by lamusmaser** [comment]
We can confirm with @bbilly1, but I think we are good to disable the Machine Learning module.

As noted [here](https://www.codegravity.com/blog/elasticsearchexception-native-code-unsupported-os), we can add `- xpack.ml.enabled=false` as an environment variable to the ES definition within the Docker Compose file.

Add that, then rebuild, and finally let us know if that works. If that doesn't work, please let us know and provided updated logs.

**Comment by ArnoldLaynee** [comment]
> We can confirm with @bbilly1, but I think we are good to disable the Machine Learning module.
> 
> As noted [here](https://www.codegravity.com/blog/elasticsearchexception-native-code-unsupported-os), we can add `- xpack.ml.enabled=false` as an environment variable to the ES definition within the Docker Compose file.
> 
> Add that, then rebuild, and finally let us know if that works. If that doesn't work, please let us know and provided updated logs.

Thank You
