### ISSUE TITLE
Unable to access Tube Archivist login page getting ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ammadmaf** [tubearchivist/tubearchivist#475]
Installed via docker stack on ubuntu20

I used 2 different machines one is ubuntu 22 one is 20 both giving same problem

I have set TA_HOST = 192.168.x.xxx

These are the logs of tube archivist container
logs

#######################

# Environment Setup #

#######################

[1] checking expected env vars

✓ all expected env vars are set

[2] set default ES user

✓ ES user is set to elastic

[3] check TA_PORT overwrite

TA_PORT is not set

[4] check TA_UWSGI_PORT overwrite

TA_UWSGI_PORT is not set

[5] check ENABLE_CAST overwrite

ENABLE_CAST is not set

[6] create superuser

superuser already created

#######################

# Connection check #

#######################

[1] connect to Redis

✓ Redis connection verified

[2] set Redis config

✓ Redis config set

[3] connect to Elastic Search

... waiting for ES [0/24]

✓ ES connection established

[4] Elastic Search version check

✓ ES version check passed

[5] check ES path.repo env var

✓ path.repo env var is set

#######################

# Application Start #

#######################

[1] set new config.json values

no new config values

[2] create expected cache folders

✓ expected folders created

[3] clear leftover locks in redis

no locks found

[4] clear task leftovers

[5] clear leftover files from dl cache

clear download cache

no files found

[6] check for first run after update

no new update found

[MIGRATION] validate index mappings

ta_channel index is created and up to date...

ta_video index is created and up to date...

ta_download index is created and up to date...

ta_playlist index is created and up to date...

ta_subtitle index is created and up to date...

ta_comment index is created and up to date...

[MIGRATION] setup snapshots

snapshot: run setup

snapshot: repo ta_snapshot already created

snapshot: policy is set.

snapshots: no snapshots found

snapshot: create initial snapshot

snapshot: executing now: {'snapshot_name': 'ta_daily_-sqv7s_mysdmj4mxkcdivjw'}

[MIGRATION] set default vid_type

error=[object Object] error=[object Object] status=503

🗙 ta_video retry failed migration.

Traceback (most recent call last):

File "/app/manage.py", line 23, in <module>

main()

File "/app/manage.py", line 19, in main

execute_from_command_line(sys.argv)

File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line

utility.execute()

File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute

self.fetch_command(subcommand).run_from_argv(self.argv)

File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv

self.execute(*args, **cmd_options)

File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute

output = self.handle(*args, **options)

File "/app/config/management/commands/ta_startup.py", line 44, in handle

self._mig_set_vid_type()

File "/app/config/management/commands/ta_startup.py", line 193, in _mig_set_vid_type

self.stdout.write(response)

File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 177, in write

if ending and not msg.endswith(ending):

AttributeError: 'dict' object has no attribute 'endswith'

Deleting 'img/icon-gridview.svg.gz'

Deleting 'img/icon-gear.3b8c10795a9c.svg.gz'

Deleting 'img/icon-star-empty.bbc34604bbe4.svg.br'

Deleting 'img/icon-rescan.4d903b41a4f8.svg'

Deleting 'img/icon-rescan.svg.br'

Deleting 'img/icon-star-half.d3ed31895745.svg.gz'

Deleting 'img/default-channel-icon.jpg'

Deleting 'img/icon-exit.svg.gz'

Deleting 'img/icon-substract.svg'

Deleting 'img/icon-seen.svg.br'

Deleting 'img/icon-gear.3b8c10795a9c.svg.br'

Deleting 'img/icon-eye.888f7ab973f0.svg'

Deleting 'img/icon-close.a5eddcaf77c7.svg'

Deleting 'img/icon-stop.svg.gz'

Deleting 'img/icon-substract.9dfc21ab59d9.svg.br'

Deleting 'img/icon-stop.svg'

Deleting 'img/icon-star-half.svg.gz'

Deleting 'img/icon-listview.svg'

Deleting 'img/default-channel-icon.bc4db58c0ee2.jpg'

Deleting 'img/icon-star-full.42cf627959e7.svg.br'

Deleting 'img/logo-tube-archivist-light.2dc6a254ac5f.png'

Deleting 'img/icon-seen.svg'

Deleting 'img/icon-close.svg'

Deleting 'img/icon-sort.ae2068e12392.svg.gz'

Deleting 'img/icon-search.svg.gz'

Deleting 'img/icon-eye.svg.br'

Deleting 'img/banner-tube-archivist-light.20fedee5b908.png'

Deleting 'img/icon-download.ab2a56dc6336.svg.br'

Deleting 'img/icon-gear.svg.gz'

Deleting 'img/icon-sort.ae2068e12392.svg.br'

Deleting 'img/icon-gridview.0c117ea41097.svg'

Deleting 'img/icon-play.svg'

Deleting 'img/icon-listview.svg.gz'

Deleting 'img/icon-unseen.svg.gz'

Deleting 'img/icon-star-empty.svg.gz'

Deleting 'img/icon-unseen.svg.br'

Deleting 'img/icon-listview.svg.br'

Deleting 'img/icon-exit.e97184c64d20.svg.gz'

Deleting 'img/icon-stop.eb4fffc46845.svg'

Deleting 'img/icon-gridview.svg'

Deleting 'img/default-video-thumb.jpg'

Deleting 'img/icon-add.19182e5c4ca3.svg.gz'

Deleting 'img/icon-rescan.4d903b41a4f8.svg.br'

Deleting 'img/icon-thumb.aa2ef184cb24.svg'

Deleting 'img/logo-tube-archivist-light.png'

Deleting 'img/icon-seen.svg.gz'

Deleting 'img/icon-heart.svg.gz'

Deleting 'img/icon-exit.e97184c64d20.svg'

Deleting 'img/icon-eye.svg'

Deleting 'img/icon-gridview.svg.br'

Deleting 'img/icon-seen.5f695ffb5071.svg'

Deleting 'img/icon-rescan.4d903b41a4f8.svg.gz'

Deleting 'img/icon-download.svg.gz'

Deleting 'img/icon-seen.5f695ffb5071.svg.gz'

Deleting 'img/icon-heart.4f8879abdf93.svg.br'

Deleting 'img/icon-eye.svg.gz'

Deleting 'img/icon-close.svg.gz'

Deleting 'img/icon-download.ab2a56dc6336.svg.gz'

Deleting 'img/icon-download.svg'

Deleting 'img/icon-gear.3b8c10795a9c.svg'

Deleting 'img/icon-play.428be32c575f.svg.br'

Deleting 'img/default-channel-banner.jpg'

Deleting 'img/icon-heart.4f8879abdf93.svg'

Deleting 'img/icon-stop.svg.br'

Deleting 'img/icon-star-half.d3ed31895745.svg'

Deleting 'img/icon-exit.svg'

Deleting 'img/icon-star-empty.bbc34604bbe4.svg'

Deleting 'img/icon-sort.svg.gz'

Deleting 'img/icon-seen.5f695ffb5071.svg.br'

Deleting 'img/icon-download.svg.br'

Deleting 'img/icon-search.fd22f6656b26.svg.br'

Deleting 'img/icon-gridview.0c117ea41097.svg.br'

Deleting 'font/OFL_License.txt.br'

Deleting 'font/OFL_License.892a31e70578.txt.gz'

Deleting 'font/Sen-Bold.30638046ccc5.woff'

Deleting 'font/OFL_License.892a31e70578.txt'

Deleting 'font/Sen-Regular.woff'

Deleting 'font/Sen-Bold.woff'

Deleting 'font/OFL_License.txt'

Deleting 'font/Sen-Regular.c58467dee557.woff'

Deleting 'font/OFL_License.892a31e70578.txt.br'

Deleting 'font/OFL_License.txt.gz'

Deleting 'css/light.css.br'

Deleting 'css/dark.css'

Deleting 'css/style.45dd4bb03fa8.css'

Deleting 'css/light.css'

Deleting 'css/dark.5677a82ea72c.css.gz'

Deleting 'css/light.fee0c400dbc6.css'

Deleting 'css/style.css.br'

Deleting 'css/light.fee0c400dbc6.css.br'

Deleting 'css/light.fee0c400dbc6.css.gz'

Deleting 'css/style.45dd4bb03fa8.css.br'

Deleting 'css/style.css'

Deleting 'css/dark.css.br'

Deleting 'css/dark.5677a82ea72c.css'

Deleting 'css/light.css.gz'

Deleting 'css/style.css.gz'

Deleting 'css/dark.5677a82ea72c.css.br'

Deleting 'css/style.45dd4bb03fa8.css.gz'

Deleting 'css/dark.css.gz'

**Comment by ammadmaf** [comment]
**Stack I used**

version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8200:8000
    volumes:
      - /srv/dev-disk-by-uuid-3403e52b-27c2-49d3-abf4-12f3fc87aa10/Deluge downloads/TubeArchivist/Youtube:/youtube
      - /srv/dev-disk-by-uuid-3403e52b-27c2-49d3-abf4-12f3fc87aa10/Deluge downloads/TubeArchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.1.200        # set your host name
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=Asia/Karachi                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /srv/dev-disk-by-uuid-3403e52b-27c2-49d3-abf4-12f3fc87aa10/Deluge downloads/TubeArchivist/redisdata:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.6.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/dev-disk-by-uuid-3403e52b-27c2-49d3-abf4-12f3fc87aa10/Deluge downloads/TubeArchivist/esdata:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:

**Comment by bbilly1** [comment]
Don't create duplicates. See subreddit rules.
