### ISSUE TITLE
[Bug]: Channels without tv art fail on rescan process

### ISSUE THREAD

**Issue by krazedkat** [tubearchivist/tubearchivist#479]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
I'm running 0.3.5 currently. I tried to delete a channel and it deleted the video files, but left the channel in the index (as well as all of the videos). Just now I tried to do a rescan of the filesystem and it seems to be breaking on that channel.

After a while, the rescan completes but the channel remains. Based on billy's suggestion on discord, I was able to readd the channel in order to get the tv art added to it and then I could delete the channel.

### Relevant log output

```shell
WARNING/ForkPoolWorker-1] ta_video: processing page 285
[2023-05-22 17:04:48,112: WARNING/ForkPoolWorker-1] ta_channel: validate artwork
[2023-05-22 17:04:49,115: WARNING/ForkPoolWorker-1] UCOUPnkYQnpc_YSnBhZH3K3Q: failed to extract thumbnail, use fallback
[2023-05-22 17:04:52,597: WARNING/ForkPoolWorker-1] 5ab7d963-287d-4394-8434-b9bfdc077810 Failed callback
[2023-05-22 17:04:52,599: ERROR/ForkPoolWorker-1] Task thumbnail_check[5ab7d963-287d-4394-8434-b9bfdc077810] raised unexpected: KeyError('channel_tvart_url')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 299, in thumbnail_check
    ThumbValidator(task=self).validate()
  File "/app/home/src/download/thumbnails.py", line 333, in validate
    _ = paginate.get_results()
  File "/app/home/src/es/connect.py", line 118, in get_results
    all_results = self.run_loop()
  File "/app/home/src/es/connect.py", line 153, in run_loop
    self.kwargs.get("callback")(all_hits, self.index_name).run()
  File "/app/home/src/download/thumbnails.py", line 256, in run
    self._validate_channels()
  File "/app/home/src/download/thumbnails.py", line 273, in _validate_channels
    channel["_source"]["channel_tvart_url"],
KeyError: 'channel_tvart_url'
```

### Anything else?

Discussion was had on discord regarding this issue, billy knows where this went wrong.

**Comment by bbilly1** [comment]
that's now handled in v0.4.0, thanks for reporting.
