### ISSUE TITLE
[Installation]: Continuous loop after installation

### ISSUE THREAD

**Issue by GL-Doses** [tubearchivist/tubearchivist#481]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Synology DS720+

### Your installation or setup question

Three weeks ago I installed Tube Archivist for the first time on my Synology NAS DS720+ using docker-compose in Portainer, and everything worked as expected and I started to use it.

This was TA v0.3.5 and some days later came v0.3.6., I tried to upgrade it but I was getting a snapshot error every time.

As I did not have much yet on it, I deleted the mounted volumes and started from zero. I did as the first time but with v0.3.6 instead, but it did not work.

Then after several times trying this I desisted and decided to go back to v0.3.5. To my surprise, now I cannot install the same version that worked for me for the first time, It keeps restarting in a continuous loop.

My docker compose:

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8770:8000
    volumes:
      - /volume1/docker/tubearchivist/media:/youtube
      - /volume1/docker/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1026
      - HOST_GID=100
      - TA_HOST=XXXXXXX    		    # set your host name
      - TA_USERNAME=XXXXXXX		    # your initial TA credentials
      - TA_PASSWORD=XXXXXXX  	            # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /volume1/docker/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /volume1/docker/tubearchivist/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
```

I am adding the TA docker logs until the point that loops.

### Relevant log output

```shell
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying home.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK
227 static files copied to '/app/staticfiles', 959 post-processed.
                         ....  .....
                  ...'',;:cc,. .;::;;,'...
               ..,;:cccllclc,  .:ccllllcc;,..
            ..,:cllcc:;,'.',.  ....'',;ccllc:,..
          ..;cllc:,'..                ...,:cccc:'.
         .;cccc;..                        ..,:ccc:'.
       .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
      .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
     .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
     .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
   .......     .xMMMNl           .dWMMXdOMMMO'   ........
   .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
   .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
   .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
   .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
   .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
   .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
    .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
    .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
     .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
      .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
       .':lcc:'.....      .  ..            ..,;cllc,.
         .,cclc,....                     ....;clc;..
          ..,:,..,c:'..              ...';:,..,:,.
            ....:lcccc:;,'''.....'',;;:clllc,....
               .'',;:cllllllccccclllllcc:,'..
                   ...'',,;;;;;;;;;,''...
                            .....
#######################
#  Environment Setup  #
#######################
[1] checking expected env vars
    ✓ all expected env vars are set
[2] set default ES user
    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
    TA_PORT is not set
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    ✓ new superuser with name tubearchivist created
#######################
#  Connection check   #
#######################
[1] connect to Redis
    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
    ... waiting for ES [1/24]
    ... waiting for ES [2/24]
    ✓ ES connection established
[4] Elastic Search version check
    ✓ ES version check passed
[5] check ES path.repo env var
    ✓ path.repo env var is set
#######################
#  Application Start  #
#######################
[1] set new config.json values
    no new config values
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover locks in redis
    no locks found
[4] clear task leftovers
[5] clear leftover files from dl cache
clear download cache
    no files found
[6] check for first run after update
    no new update found
[MIGRATION] validate index mappings
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"}],"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"}],"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"} status=404
create new blank index with name ta_channel...
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"}],"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"}],"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"} status=404
create new blank index with name ta_video...
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"}],"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"}],"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"} status=404
create new blank index with name ta_download...
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"}],"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"}],"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"} status=404
create new blank index with name ta_playlist...
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"}],"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"}],"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"} status=404
create new blank index with name ta_subtitle...
error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"}],"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"} error={"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"}],"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"} status=404
create new blank index with name ta_comment...
[MIGRATION] setup snapshots
snapshot: run setup
error={"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"} error={"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"} status=404
snapshot: setup repo ta_snapshot config {'compress': 'true', 'chunk_size': '1g', 'location': '/usr/share/elasticsearch/data/snapshot'}
snapshot: repo setup correctly: {'acknowledged': True}
error={"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"} error={"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"} status=404
snapshot: create policy ta_daily {'schedule': '0 0 15 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
snapshot: policy setup correctly: {'acknowledged': True}
snapshots: no snapshots found
snapshot: create initial snapshot
snapshot: executing now: {'snapshot_name': 'ta_daily_-irvuipf6qeanvu33wt0z3a'}
[MIGRATION] index streams and media size
error={"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"open_search_context","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[ta_video][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"open_search_context","grouped":true,"failed_shards":[]}} error={"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"open_search_context","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[ta_video][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"open_search_context","grouped":true,"failed_shards":[]}} status=503
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/app/config/management/commands/ta_startup.py", line 45, in handle
    self._mig_set_streams()
  File "/app/config/management/commands/ta_startup.py", line 160, in _mig_set_streams
    all_missing = IndexPaginate("ta_video", data).get_results()
  File "/app/home/src/es/connect.py", line 116, in get_results
    self.get_pit()
  File "/app/home/src/es/connect.py", line 126, in get_pit
    self.pit_id = response["id"]
KeyError: 'id'
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
Running migrations:
  No migrations to apply.
Deleting 'cast-videos.js'
Deleting 'progress.js'
Deleting 'script.js'
.
.
.
Deleting 'rest_framework/js/jquery-3.5.1.min.dc5e7f18c8d3.js.gz'
Deleting 'rest_framework/js/bootstrap.min.js.br'
Deleting 'rest_framework/js/bootstrap.min.js.gz'
227 static files copied to '/app/staticfiles', 959 post-processed.
                         ....  .....
                  ...'',;:cc,. .;::;;,'...
               ..,;:cccllclc,  .:ccllllcc;,..
            ..,:cllcc:;,'.',.  ....'',;ccllc:,..
          ..;cllc:,'..                ...,:cccc:'.
         .;cccc;..                        ..,:ccc:'.
       .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
      .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
     .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
     .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
   .......     .xMMMNl           .dWMMXdOMMMO'   ........
   .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
   .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
   .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
   .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
   .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
   .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
    .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
    .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
     .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
      .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
       .':lcc:'.....      .  ..            ..,;cllc,.
         .,cclc,....                     ....;clc;..
          ..,:,..,c:'..              ...';:,..,:,.
            ....:lcccc:;,'''.....'',;;:clllc,....
               .'',;:cllllllccccclllllcc:,'..
                   ...'',,;;;;;;;;;,''...
                            .....
#######################
#  Environment Setup  #
#######################
[1] checking expected env vars
    ✓ all expected env vars are set
[2] set default ES user
    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
    TA_PORT is not set
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    superuser already created
#######################
#  Connection check   #
#######################
[1] connect to Redis
    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
    ✓ ES connection established
[4] Elastic Search version check
    ✓ ES version check passed
[5] check ES path.repo env var
    ✓ path.repo env var is set
#######################
#  Application Start  #
#######################
[1] set new config.json values
    no new config values
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover locks in redis
    no locks found
[4] clear task leftovers
[5] clear leftover files from dl cache
clear download cache
    no files found
[6] check for first run after update
    no new update found
[MIGRATION] validate index mappings
ta_channel index is created and up to date...
ta_video index is created and up to date...
ta_download index is created and up to date...
ta_playlist index is created and up to date...
ta_subtitle index is created and up to date...
ta_comment index is created and up to date...
[MIGRATION] setup snapshots
snapshot: run setup
snapshot: repo ta_snapshot already created
snapshot: policy is set.
snapshots: no snapshots found
snapshot: create initial snapshot
snapshot: executing now: {'snapshot_name': 'ta_daily_-hgd-ongqthe4ipc_kkc6ng'}
[MIGRATION] index streams and media size
error={"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"open_search_context","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[ta_video][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"open_search_context","grouped":true,"failed_shards":[]}} error={"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"open_search_context","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[ta_video][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"open_search_context","grouped":true,"failed_shards":[]}} status=503
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/app/config/management/commands/ta_startup.py", line 45, in handle
    self._mig_set_streams()
  File "/app/config/management/commands/ta_startup.py", line 160, in _mig_set_streams
    all_missing = IndexPaginate("ta_video", data).get_results()
  File "/app/home/src/es/connect.py", line 116, in get_results
    self.get_pit()
  File "/app/home/src/es/connect.py", line 126, in get_pit
    self.pit_id = response["id"]
KeyError: 'id'
```

**Comment by lamusmaser** [comment]
This is something we have seen previously, but this might be a newer representation of it within TA. Just to check - how much space (actual and percent, please) is remaining on the disk that the ES data is residing on? Alternatively, you can provide the ES logs for review.

**Comment by GL-Doses** [comment]
It was the remaining free space as you thought.

I deleted some files and then it was possible to install the TA again as normal.
As I had an external backup from before I also tried to update my previous install from v0.3.5 to v0.3.6. This time it also worked.
The only thing that really changed from my first install without any problem was the free space, because the videos started to take more space than I thought.

So, everything is running fine again. 

In the case that it can be of any help to someone in the future, here is my numbers:
—Before (not working): 120 GB (4%)
—After (working): 150 (4%)

Thanks for the help, and this can be closed now.

**Comment by lamusmaser** [comment]
I assume the second percentage is actually around 20%, not 4% again. Glad to hear it!

As a note, this is included as part of the project README [here](https://github.com/tubearchivist/tubearchivist#disk-usage).

As you said, we'll go ahead and close this out.

**Comment by lamusmaser** [comment]
Hmm... interesting. ElasticSearch has a waterlevel marker to go green status after 10%+ is available to it. The easiest answer for ES management is to put it on its own drive that won't really see changes (such as one partitioned out specifically for ES). Otherwise, more space is always better!
