### ISSUE TITLE
[Bug]: Tubearchivist crashed when trying to add specific channel (Max retries exceeded with url)

### ISSUE THREAD

**Issue by thimplicity** [tubearchivist/tubearchivist#482]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker on Ubuntu

## Describe the bug

I am trying to subscribe to one of my favorite channels. It works for all other channels I tried.

## Steps To Reproduce

Add URL (https://www.youtube.com/@Bourbonmoth) and click on subscribe

## Expected behavior

Adding channel to subscriptions

When I try to add the channel above, TA crashes and it not available for a few seconds (error 500). Then comes back up automatically. I can add other channels, but not this one.

### Relevant log output

```shell
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archivist-es', port=9200): Max retries exceeded with url: /ta_download/_doc/pmaHb8AQS9U?refresh=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2871a5960>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by lamusmaser** [comment]
That's interesting. So, first, to just confirm that the channel is subscribable, I was able to allow it to subscribe successfully:

```
https://www.youtube.com/@Bourbonmoth
[2023-06-03 13:26:03,141: INFO/MainProcess] Task subscribe_to[6ef34c3a-881f-4e6f-a957-c284ce94cb3d] received
Sat Jun  3 13:26:03 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /channel/ (ip 172.18.0.1) !!!
[2023-06-03 13:26:03,147: WARNING/ForkPoolWorker-4] subscribe_to create callback
[2023-06-03 13:26:04,141: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: get metadata from es
[2023-06-03 13:26:04,169: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UCQ_bmgSrYsQS0LboA_tZpEw","found":false}
[2023-06-03 13:26:04,170: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: get metadata from youtube
[2023-06-03 13:26:04,556: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: download channel thumbnail
[2023-06-03 13:26:09,977: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: retry thumbnail download https://yt3.googleusercontent.com/in1WJ_1Binrcly0luiEV_eCUdnN44OY4hh_dv8FFIojk11m05Df1x9XJObJHgP8GckfNjzOTP0U=s0
[2023-06-03 13:26:16,031: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: retry thumbnail download https://yt3.googleusercontent.com/in1WJ_1Binrcly0luiEV_eCUdnN44OY4hh_dv8FFIojk11m05Df1x9XJObJHgP8GckfNjzOTP0U=s0
[2023-06-03 13:26:18,352: WARNING/ForkPoolWorker-4] /root/.local/lib/python3.10/site-packages/PIL/Image.py:3176: DecompressionBombWarning: Image size (103286569 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[2023-06-03 13:26:22,421: WARNING/ForkPoolWorker-4] 6ef34c3a-881f-4e6f-a957-c284ce94cb3d success callback
[2023-06-03 13:26:22,425: INFO/ForkPoolWorker-4] Task subscribe_to[6ef34c3a-881f-4e6f-a957-c284ce94cb3d] succeeded in 19.274393104948103s: None
```

Since that succeeded on my side, that meant we had something else occurring. Looking back at the log output, we have the following segments:
```
requests.exceptions.ConnectionError:
HTTPConnectionPool(host='archivist-es',port=9200):
Max retries exceeded with url:
/ta_download/_doc/pmaHb8AQS9U?refresh=true
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2871a5960>:
Failed to establish a new connection:
[Errno 111] Connection refused'))
```

This is saying there is an issue with connecting to ElasticSearch for the duration of the subscription attempt. So, what'll need to do two things:
1. Get the full subscription event log set (you can see in my example where it has the channel name through the `subscribe_to` call closure).
2. Attempt to subscribe to two channels at the same time (doesn't matter about the second channel).

This will allow us to see if it is just the channel or if there is something else occurring. Let us know what you can find and we'll review it with you further to determine what is happening.

**Comment by thimplicity** [comment]
Hi,
I have tried two channels and added the log below:

`2023-06-04T13:22:51.456755255Z https://www.youtube.com/@Bourbonmoth
2023-06-04T13:22:51.458414673Z https://www.youtube.com/@mkbhd
2023-06-04T13:22:51.458429204Z 
2023-06-04T13:22:52.105799358Z [2023-06-04 09:22:52,081: INFO/MainProcess] Task subscribe_to[4df1e147-7a37-468d-bac1-b1fcd5210aa4] received
2023-06-04T13:22:52.396254789Z [2023-06-04 09:22:52,367: WARNING/ForkPoolWorker-4] subscribe_to create callback
2023-06-04T13:22:56.035196300Z [2023-06-04 09:22:56,032: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: get metadata from es
2023-06-04T13:22:56.239095875Z [2023-06-04 09:22:56,238: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UCQ_bmgSrYsQS0LboA_tZpEw","found":false}
2023-06-04T13:22:56.240836682Z [2023-06-04 09:22:56,240: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: get metadata from youtube
2023-06-04T13:22:56.600467503Z [2023-06-04 09:22:56,599: WARNING/ForkPoolWorker-4] UCQ_bmgSrYsQS0LboA_tZpEw: download channel thumbnail
2023-06-04T13:22:58.074475223Z [2023-06-04 09:22:58,073: WARNING/ForkPoolWorker-4] /root/.local/lib/python3.10/site-packages/PIL/Image.py:3176: DecompressionBombWarning: Image size (103286569 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
2023-06-04T13:22:58.074537615Z   warnings.warn(
2023-06-04T13:22:58.074548338Z 
2023-06-04T13:23:12.239726325Z [2023-06-04 09:23:12,229: WARNING/ForkPoolWorker-4] 4df1e147-7a37-468d-bac1-b1fcd5210aa4 Failed callback
2023-06-04T13:23:12.257581804Z [2023-06-04 09:23:12,254: ERROR/ForkPoolWorker-4] Task subscribe_to[4df1e147-7a37-468d-bac1-b1fcd5210aa4] raised unexpected: ConnectionError(MaxRetryError("HTTPConnectionPool(host='archivist-es', port=9200): Max retries exceeded with url: /ta_channel/_doc/UCQ_bmgSrYsQS0LboA_tZpEw/?refresh=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d0568ea10>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2023-06-04T13:23:12.257639464Z Traceback (most recent call last):
2023-06-04T13:23:12.257649215Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 200, in _new_conn
2023-06-04T13:23:12.257656882Z     sock = connection.create_connection(
2023-06-04T13:23:12.257663705Z   File "/root/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
2023-06-04T13:23:12.257670903Z     raise err
2023-06-04T13:23:12.257677793Z   File "/root/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
2023-06-04T13:23:12.257684925Z     sock.connect(sa)
2023-06-04T13:23:12.257691682Z ConnectionRefusedError: [Errno 111] Connection refused
2023-06-04T13:23:12.257698625Z 
2023-06-04T13:23:12.257705364Z The above exception was the direct cause of the following exception:
2023-06-04T13:23:12.257712430Z 
2023-06-04T13:23:12.257719329Z Traceback (most recent call last):
2023-06-04T13:23:12.257726680Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2023-06-04T13:23:12.257734008Z     response = self._make_request(
2023-06-04T13:23:12.257740934Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
2023-06-04T13:23:12.257748037Z     conn.request(
2023-06-04T13:23:12.257754920Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 388, in request
2023-06-04T13:23:12.257762063Z     self.endheaders()
2023-06-04T13:23:12.257768910Z   File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
2023-06-04T13:23:12.257775906Z     self._send_output(message_body, encode_chunked=encode_chunked)
2023-06-04T13:23:12.257782952Z   File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
2023-06-04T13:23:12.257790059Z     self.send(msg)
2023-06-04T13:23:12.257797043Z   File "/usr/local/lib/python3.10/http/client.py", line 975, in send
2023-06-04T13:23:12.257804039Z     self.connect()
2023-06-04T13:23:12.257810793Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 236, in connect
2023-06-04T13:23:12.257817937Z     self.sock = self._new_conn()
2023-06-04T13:23:12.257824965Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connection.py", line 215, in _new_conn
2023-06-04T13:23:12.257880420Z     raise NewConnectionError(
2023-06-04T13:23:12.257891560Z urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9d0568ea10>: Failed to establish a new connection: [Errno 111] Connection refused
2023-06-04T13:23:12.258032535Z 
2023-06-04T13:23:12.258041334Z The above exception was the direct cause of the following exception:
2023-06-04T13:23:12.258056563Z 
2023-06-04T13:23:12.258064210Z Traceback (most recent call last):
2023-06-04T13:23:12.258071175Z   File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2023-06-04T13:23:12.258078318Z     resp = conn.urlopen(
2023-06-04T13:23:12.258085078Z   File "/root/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-06-04T13:23:12.258092087Z     retries = retries.increment(
2023-06-04T13:23:12.258098984Z   File "/root/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
2023-06-04T13:23:12.258105998Z     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-06-04T13:23:12.258130207Z urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archivist-es', port=9200): Max retries exceeded with url: /ta_channel/_doc/UCQ_bmgSrYsQS0LboA_tZpEw/?refresh=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d0568ea10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-06-04T13:23:12.258138157Z 
2023-06-04T13:23:12.258144947Z During handling of the above exception, another exception occurred:
2023-06-04T13:23:12.258151865Z 
2023-06-04T13:23:12.258158573Z Traceback (most recent call last):
2023-06-04T13:23:12.258165658Z   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
2023-06-04T13:23:12.258172823Z     R = retval = fun(*args, **kwargs)
2023-06-04T13:23:12.258179858Z   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
2023-06-04T13:23:12.258187266Z     return self.run(*args, **kwargs)
2023-06-04T13:23:12.258194072Z   File "/app/home/tasks.py", line 326, in subscribe_to
2023-06-04T13:23:12.258201082Z     SubscriptionHandler(url_str, task=self).subscribe()
2023-06-04T13:23:12.258208072Z   File "/app/home/src/download/subscriptions.py", line 346, in subscribe
2023-06-04T13:23:12.258215049Z     self.subscribe_type(item)
2023-06-04T13:23:12.258221869Z   File "/app/home/src/download/subscriptions.py", line 363, in subscribe_type
2023-06-04T13:23:12.258228812Z     self._subscribe(channel_id)
2023-06-04T13:23:12.258235667Z   File "/app/home/src/download/subscriptions.py", line 367, in _subscribe
2023-06-04T13:23:12.258242667Z     ChannelSubscription().change_subscribe(
2023-06-04T13:23:12.258249620Z   File "/app/home/src/download/subscriptions.py", line 147, in change_subscribe
2023-06-04T13:23:12.258256583Z     channel.upload_to_es()
2023-06-04T13:23:12.258263344Z   File "/app/home/src/index/generic.py", line 58, in upload_to_es
2023-06-04T13:23:12.258271914Z     _, _ = ElasticWrap(self.es_path).put(self.json_data, refresh=True)
2023-06-04T13:23:12.258279150Z   File "/app/home/src/es/connect.py", line 73, in put
2023-06-04T13:23:12.258292050Z     response = requests.put(f"{self.url}", json=data, auth=self.auth)
2023-06-04T13:23:12.258299754Z   File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 130, in put
2023-06-04T13:23:12.258306736Z     return request("put", url, data=data, **kwargs)
2023-06-04T13:23:12.258313688Z   File "/root/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2023-06-04T13:23:12.258320863Z     return session.request(method=method, url=url, **kwargs)
2023-06-04T13:23:12.258327783Z   File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
2023-06-04T13:23:12.258334840Z     resp = self.send(prep, **send_kwargs)
2023-06-04T13:23:12.258341803Z   File "/root/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
2023-06-04T13:23:12.258348809Z     r = adapter.send(request, **kwargs)
2023-06-04T13:23:12.258355739Z   File "/root/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
2023-06-04T13:23:12.258362780Z     raise ConnectionError(e, request=request)
2023-06-04T13:23:12.258369732Z requests.exceptions.ConnectionError: HTTPConnectionPool(host='archivist-es', port=9200): Max retries exceeded with url: /ta_channel/_doc/UCQ_bmgSrYsQS0LboA_tZpEw/?refresh=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d0568ea10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-06-04T13:23:21.839782854Z [pid: 37|app: 0|req: 147/147] 10.23.20.110 () {46 vars in 885 bytes} [Sun Jun  4 09:23:21 2023] GET / => generated 145 bytes in 458 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)`

After this I tried to add the MKBHD channel along and it worked fine:

`2023-06-04T13:24:55.305469704Z https://www.youtube.com/@mkbhd
2023-06-04T13:24:55.420854636Z [2023-06-04 09:24:55,404: INFO/MainProcess] Task subscribe_to[88ff2faa-d49b-457a-9e84-26413e758108] received
2023-06-04T13:24:55.465789803Z [2023-06-04 09:24:55,464: WARNING/ForkPoolWorker-4] subscribe_to create callback
2023-06-04T13:24:57.078950934Z [2023-06-04 09:24:57,077: WARNING/ForkPoolWorker-4] UCBJycsmduvYEL83R_U4JriQ: get metadata from es
2023-06-04T13:24:57.150018174Z [2023-06-04 09:24:57,149: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UCBJycsmduvYEL83R_U4JriQ","found":false}
2023-06-04T13:24:57.150974392Z [2023-06-04 09:24:57,150: WARNING/ForkPoolWorker-4] UCBJycsmduvYEL83R_U4JriQ: get metadata from youtube
2023-06-04T13:24:57.467303260Z [2023-06-04 09:24:57,466: WARNING/ForkPoolWorker-4] UCBJycsmduvYEL83R_U4JriQ: download channel thumbnail
2023-06-04T13:24:59.141287518Z [2023-06-04 09:24:59,139: WARNING/ForkPoolWorker-4] 88ff2faa-d49b-457a-9e84-26413e758108 success callback
2023-06-04T13:24:59.145555151Z [2023-06-04 09:24:59,145: INFO/ForkPoolWorker-4] Task subscribe_to[88ff2faa-d49b-457a-9e84-26413e758108] succeeded in 3.682876765727997s: None`

**Comment by lamusmaser** [comment]
Still reviewing, haven't had time to specifically troubleshoot and look at logs.

**Comment by bbilly1** [comment]
I can't reproduce that either, I doubt this has anything to do with that particular channel, although strange, that it only failed on that one. Usually things like that is docker DNS related. Some times a rebuild of the container can help, sometimes specifying the DNS manually can help. Either way, this is a problem with docker networking, unlikely with Tube Archivist.
