### ISSUE TITLE
[Feature Request]: Retry connecting to Redis and ElasticSearch on startup

### ISSUE THREAD

**Issue by dmynerd78** [tubearchivist/tubearchivist#485]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
When starting all the containers at the same time **without** `docker-compose` (ie `docker start TubeArchivist TubeArchivist-RedisJSON TubeArchivist-ES`), the main tubearchivist container fails to start as it's unable to connect to the Redis and Elasticsearch containers (since they're still starting up)

## Describe the solution you'd like
On startup only, attempt to connect to Redis and ElasticSearch three(?) times before failing. This should give enough time for Redis and Elasticsearch to start so that the main container can connect to them.

## Additional context
I'm running tubearchivist on unRAID and I have a plugin (CA Backup) which powers down all containers, takes a backup, and then starts all the containers back up again. However, the plugin doesn't stagger container startup like `docker-compose` so the main TubeArchivist container fails to start because of the above issue.

This could also help make the first startup for new users more forgiving if they're not too familiar with docker.

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
During startup there are already additional retries. If it doesn't detect during that time period, the TA container should restart, which then allows, in most cases, enough time for the other containers to start up.

**Comment by bbilly1** [comment]
What @lamusmaser is referring to is the retry logic for redis here: 

https://github.com/tubearchivist/tubearchivist/blob/testing/tubearchivist/config/management/commands/ta_connection.py#L41-L62

Then for the ES connection there in deed was a hiccup, latest release removed some additional error handling wait statement when ES is reachable but no shards are ready. That is fixed and even improved from the previous approach in testing here: https://github.com/tubearchivist/tubearchivist/commit/c4e2332b831e6545308ceefc66fdb073f42dad4b.

What's the traceback you are seeing? 

But yeah, docker compose handles that much better and mostly automatic.

**Comment by dmynerd78** [comment]
Apologies I thought I looked through the code somewhat thoroughly but completely missed that part you linked. I've been running into Redis getting a `Connection reset by peer` error. If I wait a few moments before starting the main container, it comes up normally.

```bash
root@Tower:~# docker start TubeArchivist TubeArchivist-RedisJSON TubeArchivist-ES
TubeArchivist
TubeArchivist-RedisJSON
TubeArchivist-ES
root@Tower:~# docker ps -a | grep TubeArchivist
6bcc70f98764   bbilly1/tubearchivist:latest           "./run.sh"               4 weeks ago     Exited (1) 5 seconds ago                                                                                                                                        TubeArchivist
dc67d3b92dd5   redis/redis-stack-server               "/entrypoint.sh"         6 weeks ago     Up 5 seconds                0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                           TubeArchivist-RedisJSON
b31ea70394bf   bbilly1/tubearchivist-es:latest        "/bin/tini -- /usr/l…"   8 weeks ago     Up 5 seconds                0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9300/tcp                                                                                 TubeArchivist-ES
root@Tower:~# docker logs --tail 200 TubeArchivist
    return conn.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1509, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1496, in _disconnect_raise_connect
    raise error
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1508, in <lambda>
    lambda: command(*args, **kwargs),
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1529, in try_read
    return conn.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 356, in _read_response
    raw = self._buffer.readline()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 259, in readline
    self._read_from_socket()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 212, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-06-13 20:45:50,584: WARNING/MainProcess] /root/.local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning:
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-06-13 20:45:50,588: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.78.200:6379//: Error while reading from 192.168.78.200:6379 : (104, 'Connection reset by peer').
Trying again in 2.00 seconds... (1/100)

[2023-06-13 20:45:52,591: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.78.200:6379//: Error 111 connecting to 192.168.78.200:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2023-06-13 20:45:56,597: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.78.200:6379//: Error 111 connecting to 192.168.78.200:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 356, in _read_response
    raw = self._buffer.readline()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 259, in readline
    self._read_from_socket()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 209, in _read_from_socket
    data = self._sock.recv(socket_read_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 12, in <module>
    from home.src.download.queue import PendingList
  File "/app/home/src/download/queue.py", line 10, in <module>
    from home.src.download.subscriptions import (
  File "/app/home/src/download/subscriptions.py", line 8, in <module>
    from home.src.download.thumbnails import ThumbManager
  File "/app/home/src/download/thumbnails.py", line 21, in <module>
    class ThumbManagerBase:
  File "/app/home/src/download/thumbnails.py", line 24, in ThumbManagerBase
    CONFIG = AppConfig().config
  File "/app/home/src/ta/config.py", line 23, in __init__
    self.config = self.get_config()
  File "/app/home/src/ta/config.py", line 28, in get_config
    config = self.get_config_redis()
  File "/app/home/src/ta/config.py", line 70, in get_config_redis
    config = RedisArchivist().get_message("config")
  File "/app/home/src/ta/ta_redis.py", line 59, in get_message
    reply = self.conn.execute_command("JSON.GET", self.NAME_SPACE + key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1258, in execute_command
    return conn.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1262, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1248, in _disconnect_raise
    raise error
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1259, in <lambda>
    lambda: self._send_command_parse_response(
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1275, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 871, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 192.168.78.200:6379 : (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 356, in _read_response
    raw = self._buffer.readline()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 259, in readline
    self._read_from_socket()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 209, in _read_from_socket
    data = self._sock.recv(socket_read_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 12, in <module>
    from home.src.download.queue import PendingList
  File "/app/home/src/download/queue.py", line 10, in <module>
    from home.src.download.subscriptions import (
  File "/app/home/src/download/subscriptions.py", line 8, in <module>
    from home.src.download.thumbnails import ThumbManager
  File "/app/home/src/download/thumbnails.py", line 21, in <module>
    class ThumbManagerBase:
  File "/app/home/src/download/thumbnails.py", line 24, in ThumbManagerBase
    CONFIG = AppConfig().config
  File "/app/home/src/ta/config.py", line 23, in __init__
    self.config = self.get_config()
  File "/app/home/src/ta/config.py", line 28, in get_config
    config = self.get_config_redis()
  File "/app/home/src/ta/config.py", line 70, in get_config_redis
    config = RedisArchivist().get_message("config")
  File "/app/home/src/ta/ta_redis.py", line 59, in get_message
    reply = self.conn.execute_command("JSON.GET", self.NAME_SPACE + key)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1258, in execute_command
    return conn.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1262, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1248, in _disconnect_raise
    raise error
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1259, in <lambda>
    lambda: self._send_command_parse_response(
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1275, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 871, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 192.168.78.200:6379 : (104, 'Connection reset by peer')
```

**Comment by lamusmaser** [comment]
Ah, yeah, this is presenting a different issue. You can see in the middle that the container does attempt to connect and gets failed connections, so it retries with exponentially longer periods of waiting time. 

What is happening later is that the redis container gets to a point where the port is open but not listening properly (so, establishing the internal listener), which then causes it to throw an error, which is not properly caught and handled by TA. This wouldn't happen in most circumstances with an appropriate dependency tree,  like docker compose, since they will want until the container is up before attempting to bring up TA, which bypasses this potential conflict.

**Comment by dmynerd78** [comment]
Yeah annoyingly, unraid doesn't have the best setup for docker-compose. I can get around it, but it'd be nice to resolve the issue so other less experienced people don't have to worry about it. I'm not too familiar with the code environment yet, but I'd definitely be willing to help resolve this in any way I can.

**Comment by bbilly1** [comment]
If you find a better way how to deal with that, I'm open for a PR. But for your testing, please also test your solution against the default recommended docker compose installation to make sure this doesn't have unintended side effects.

**Comment by bbilly1** [comment]
OK, looks like the redis connection check django management command doesn't actually do anything, at that point the connection already needs to be established, as django needs redis at application bootstrap. But with this additional check and delay, this should cover that.

I tested it by removing the depends_on key in compose and just starting tubearchivist, let it hit the retry, then start redis, let it continue the startup then finally start ES.

Can you verify this works?

**Comment by dmynerd78** [comment]
I can verify this works! Thank you so much for all your help! Sorry for not responding sooner work has been extremely busy this week and I haven't been able to check GH.
