### ISSUE TITLE
[Bug]: Broken update, no such snapshot lifecycle policy

### ISSUE THREAD

**Issue by JJGO** [tubearchivist/tubearchivist#487]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian 10 buster Kernel 4.19

## Describe the bug

I've recently upgraded my tube archivist docker image and now I'm stuck in an error that prevent TA from starting

## Steps To Reproduce

Upgrading Tube Archivist to latest Docker Image

## Expected behavior

Working startup

### Relevant log output

```shell
231 static files copied to '/app/staticfiles', 971 post-processed.

                          ....  .....
                   ...'',;:cc,. .;::;;,'...
                ..,;:cccllclc,  .:ccllllcc;,..
             ..,:cllcc:;,'.',.  ....'',;ccllc:,..
           ..;cllc:,'..                ...,:cccc:'.
          .;cccc;..                        ..,:ccc:'.
        .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
       .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
      .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
      .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
    .......     .xMMMNl           .dWMMXdOMMMO'   ........
    .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
    .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
    .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
    .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
    .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
    .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
     .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
     .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
      .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
       .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
        .':lcc:'.....      .  ..            ..,;cllc,.
          .,cclc,....                     ....;clc;..
           ..,:,..,c:'..              ...';:,..,:,.
             ....:lcccc:;,'''.....'',;;:clllc,....
                .'',;:cllllllccccclllllcc:,'..
                    ...'',,;;;;;;;;;,''...
                             .....

 #######################
 #  Environment Setup  #
 #######################

 [1] checking expected env vars
     ✓ all expected env vars are set
 [2] set default ES user
     ✓ ES user is set to elastic
 [3] check TA_PORT overwrite
     TA_PORT is not set
 [4] check TA_UWSGI_PORT overwrite
     TA_UWSGI_PORT is not set
 [5] check ENABLE_CAST overwrite
     ENABLE_CAST is not set
 [6] create superuser
     superuser already created

 #######################
 #  Connection check   #
 #######################

 [1] connect to Redis
     ✓ Redis connection verified
 [2] set Redis config
     ✓ Redis config set
 [3] connect to Elastic Search
     ... waiting for ES [0/24]
     ✓ ES connection established
 [4] Elastic Search version check
     ✓ ES version check passed
 [5] check ES path.repo env var
     ✓ path.repo env var is set

 #######################
 #  Application Start  #
 #######################

 [1] set new config.json values
     no new config values
 [2] create expected cache folders
     ✓ expected folders created
 [3] clear leftover locks in redis
     no locks found
 [4] clear leftover files from dl cache
 clear download cache
     no files found
 [5] check for first run after update
     no new update found
 [MIGRATION] validate index mappings
 detected mapping change: channel_last_refresh, {'type': 'date'}
 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400}
 Traceback (most recent call last):
   File "/app/manage.py", line 23, in <module>
     main()
   File "/app/manage.py", line 19, in main
     execute_from_command_line(sys.argv)
   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
     utility.execute()
   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
     output = self.handle(*args, **options)
   File "/app/config/management/commands/ta_startup.py", line 39, in handle
     self._mig_index_setup()
   File "/app/config/management/commands/ta_startup.py", line 124, in _mig_index_setup
     ElasitIndexWrap().setup()
   File "/app/home/src/es/index_setup.py", line 160, in setup
     self._check_backup()
   File "/app/home/src/es/index_setup.py", line 205, in _check_backup
     ElasticSnapshot().take_snapshot_now(wait=True)
   File "/app/home/src/es/snapshot.py", line 154, in take_snapshot_now
     self._wait_for_snapshot(response["snapshot_name"])
 KeyError: 'snapshot_name'
```

### Anything else?

An existing issue #443 seems to report the same issue but the recommended fix of first upgrading to v3.0.0 and then to latest is not viable anymore as the v3.0.0 Docker image is not available anymore (https://hub.docker.com/r/bbilly1/tubearchivist/tags)

**Comment by JJGO** [comment]
Following up, I managed to build `v3.0.0` using the source code & Dockerfile from the releases and I am now facing a different error

```
waiting for elastic search to start
waiting for elastic search to start
{
  "name" : "1ec398ac79f7",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "0irtsG7qQQuGwR3ayy8jjw",
  "version" : {
    "number" : "8.6.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "f67ef2df40237445caa70e2fef79471cc608d70d",
    "build_date" : "2023-01-04T09:35:21.782467981Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
run startup checks
elasticsearch version check passed
detected mapping change: channel_last_refresh, {'type': 
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/
    app_config.ready()
  File "/app/home/apps.py", line 135, in ready
    startup.run()
  File "/app/home/apps.py", line 31, in run
    ElasitIndexWrap().setup()
  File "/app/home/src/es/index_setup.py", line 160, in setup
    self._check_backup()
  File "/app/home/src/es/index_setup.py", line 203, in 
    if config["application"]["enable_snapshot"]:
KeyError: 'enable_snapshot'
```

**Comment by lamusmaser** [comment]
What version are you originally coming from?

**Comment by JJGO** [comment]
Not sure, is there any way to check the volumes for this info?

**Comment by lamusmaser** [comment]
Probably not at this point.

Let's assume you are coming from an extremely old version, then. Can you build and go to v0.2.4? The instructions in the Release Notes contain details about the extra steps needed to enable snapshots.

**Comment by JJGO** [comment]
Ok, built an image using v2.4.0, added the `path.repo` envvar and I'm getting the following error trace
```
waiting for elastic search to start
{
  "name" : "ca9f1b04f5eb",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "0irtsG7qQQuGwR3ayy8jjw",
  "version" : {
    "number" : "8.7.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "09520b59b6bc1057340b55750186466ea715e30e",
    "build_date" : "2023-03-27T16:31:09.816451435Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
run startup checks
elasticsearch version check passed
detected mapping change: channel_last_refresh, {'type': 'date'}
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/home/apps.py", line 135, in ready
    startup.run()
  File "/app/home/apps.py", line 31, in run
    ElasitIndexWrap().setup()
  File "/app/home/src/es/index_setup.py", line 160, in setup
    self._check_backup()
  File "/app/home/src/es/index_setup.py", line 203, in _check_backup
    if config["application"]["enable_snapshot"]:
KeyError: 'enable_snapshot'
```

**Comment by bbilly1** [comment]
I suggest to delete the redis volume to reset your configuration to the default. This will fix a bunch of your problems. You'll have to go through the settings page after that and restore your configs there.

Then please also take the update section in the readme to heart, defining the update compatibility to two versions back: https://github.com/tubearchivist/tubearchivist#update

This project is in it's infancy, lot's of changes are happening, requiring you to update it regularly, at least until we reach a version 1.0.

**Comment by bbilly1** [comment]
watchtower has it's own problems... you'll want to read the release notes before updating as there have been breaking changes before.

since a few versions now, you will get a convenient update notification in the footer with a link to the release page.
