### ISSUE TITLE
[Bug]: Reindex after upgrade to 0.4.0

### ISSUE THREAD

**Issue by dyslexicjedi** [tubearchivist/tubearchivist#514]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux Docker

## Describe the bug
Not all videos updated to the new file format, I've had to manually update some videos. I've moved it correctly. 

`
admin@truenas[...ubeArchivist/UCtI0Hodo5o5dUb67FeUjDeA]$ ls 1sGWUunA2mM*
1sGWUunA2mM.mp4
`

But a reindex call will fail and crash on the old location. 

## Steps To Reproduce

Manually move a video to the new folder structure in 0.4.0 then do a reindex.

## Expected behavior

Reindex the video at the new location.

### Relevant log output

```shell
[2023-08-08 20:45:00,007: INFO/MainProcess] Task check_reindex[496a00ca-bf33-4213-b363-697ebf61bead] received
[2023-08-08 20:45:00,008: WARNING/ForkPoolWorker-8] check_reindex create callback
[2023-08-08 20:45:00,014: WARNING/ForkPoolWorker-8] [task][check_reindex] reindex outdated documents
[2023-08-08 20:45:00,049: WARNING/ForkPoolWorker-8] validating cookie
[2023-08-08 20:45:00,143: WARNING/ForkPoolWorker-8] 1sGWUunA2mM: get metadata from es
[2023-08-08 20:45:00,147: WARNING/ForkPoolWorker-8] 1sGWUunA2mM: get metadata from youtube
[2023-08-08 20:45:03,260: WARNING/ForkPoolWorker-8] UCtI0Hodo5o5dUb67FeUjDeA: get metadata from es
[2023-08-08 20:45:03,274: WARNING/ForkPoolWorker-8] 496a00ca-bf33-4213-b363-697ebf61bead Failed callback
[2023-08-08 20:45:03,275: ERROR/ForkPoolWorker-8] Task check_reindex[496a00ca-bf33-4213-b363-697ebf61bead] raised unexpected: CalledProcessError(1, ['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/youtube/SpaceX/20230806_1sGWUunA2mM_Starlink Mission.mp4'])
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 256, in check_reindex
    handler.reindex_all()
  File "/app/home/src/index/reindex.py", line 248, in reindex_all
    has_next = self.reindex_index(name, index_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/index/reindex.py", line 259, in reindex_index
    reindex(youtube_id)
  File "/app/home/src/index/reindex.py", line 298, in _reindex_single_video
    video.build_json(media_path=media_url)
  File "/app/home/src/index/video.py", line 157, in build_json
    self.add_player(media_path)
  File "/app/home/src/index/video.py", line 254, in add_player
    duration = duration_handler.get_sec(vid_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/index/video_streams.py", line 16, in get_sec
    duration = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/youtube/SpaceX/20230806_1sGWUunA2mM_Starlink Mission.mp4']' returned non-zero exit status 1.
[2023-08-08 20:45:03,276: WARNING/ForkPoolWorker-8] 496a00ca-bf33-4213-b363-697ebf61bead return callback
```

**Comment by bbilly1** [comment]
Filesystem rescan from the settings page should fix that. Double check it's at the expected location, then this should fix the wrong `media_url` in the index.

**Comment by dyslexicjedi** [comment]
That's the action it's trying to perform. I hit Filesystem rescan and that's the output log from it.

**Comment by bbilly1** [comment]
The log and the error above is indicating that you are running the reindex task aka metadata refresh, to get the newest metadata from youtube: `[task][check_reindex] reindex outdated documents`.

What you are looking for is [Rescan Filesystem](https://docs.tubearchivist.com/settings/#rescan-filesystem). You can trigger that from the settings page. That should fix any wrong media urls in the index. After that the reindex task should work fine.

**Comment by drifter75** [comment]
having the same issue after mistakenly deleting the cache folder. Manual Reindex doesn't work, even though the video is available in YT.

What worked for me is to move the files to cache/download, with filename as youtubeid.mp4 and download them after adding the youtube id's into the queue.

**Comment by lamusmaser** [comment]
As noted [here](https://github.com/tubearchivist/tubearchivist/issues/514#issuecomment-1671222625), you are looking for the Rescan Filesystem, not the Manual Reindex.

**Comment by bbilly1** [comment]
I hope this is resolved by now. Closing this for now.
