### ISSUE TITLE
[Bug]:  Downloading modified Queue stops with a FileNotFoundError

### ISSUE THREAD

**Issue by danieljue** [tubearchivist/tubearchivist#525]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker

## Describe the bug
Downloading Queue stops with a FileNotFoundError.  The queue was modified only through the UI, using "ignore" and "add to queue" buttons.  ("Ignore" button was used on videos that were not in the process of being downloaded.)

## Steps To Reproduce
Have a queue of downloads. (I had ~7500)
Start moving some videos in the queue that aren't downloading yet into "Ignore" (I clicked about 4000 times)
Switched to "view only ignored videos"
Move a handful of those ignored files back into the Queue

It sometimes prioritizes one that I've just added back in the queue, sometimes not.  It continues to download videos, then crashed when I wasn't looking.

This crash stopped the automatic processing of the items in the queue (about 3000 items)

Clicking "download now" on one of the items in the queue does cause it to start downloading, and restarts the queue processing.

## Expected behavior
I expect going from ignored back to the queue would just put certain videos back in the queue, somewhere, and that the queue would not stop processing for an error like this.

Note: I was doing this because I can't get the "download now" button to change the queue, because I needed it to start downloading things that were deeper in the queue.

### Relevant log output

```shell
2023-08-25 06:07:15 tubearchivist    | DarB7p5upBo: change status to pending
2023-08-25 06:07:22 tubearchivist    | mNSpPgynH6Q: change status to pending
2023-08-25 06:07:29 tubearchivist    | SXA-NG1UFas: change status to pending
2023-08-25 06:07:34 tubearchivist    | _j9zo1uthU0: change status to pending
2023-08-25 06:07:36 tubearchivist    | iuPpZb_l8_0: change status to pending
2023-08-25 06:07:40 tubearchivist    | og250HPuIVQ: change status to pending
2023-08-25 06:07:46 tubearchivist    | arksvNTfkV4: change status to pending
2023-08-25 06:07:54 tubearchivist    | XdBT3zfS3PU: change status to pending
2023-08-25 06:07:59 tubearchivist    | MDRctfAejH4: change status to pending
2023-08-25 06:08:03 tubearchivist    | BzbhXnLQ22s: change status to pending
2023-08-25 06:08:22 tubearchivist    | 3x6a95qZpJ4: change status to pending
2023-08-25 06:09:28 tubearchivist    | ER2dmhbdR88: change status to pending
2023-08-25 06:10:02 tubearchivist    | Filter download view ignored only: False
2023-08-25 06:12:13 archivist-redis  | 8:M 25 Aug 2023 10:12:13.078 * 100 changes in 300 seconds. Saving...
2023-08-25 06:12:13 archivist-redis  | 8:M 25 Aug 2023 10:12:13.079 * Background saving started by pid 151
2023-08-25 06:12:13 archivist-redis  | 151:C 25 Aug 2023 10:12:13.098 * DB saved on disk
2023-08-25 06:12:13 archivist-redis  | 151:C 25 Aug 2023 10:12:13.099 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:12:13 archivist-redis  | 8:M 25 Aug 2023 10:12:13.181 * Background saving terminated with success
2023-08-25 06:17:14 archivist-redis  | 8:M 25 Aug 2023 10:17:14.062 * 100 changes in 300 seconds. Saving...
2023-08-25 06:17:14 archivist-redis  | 8:M 25 Aug 2023 10:17:14.063 * Background saving started by pid 152
2023-08-25 06:17:14 archivist-redis  | 152:C 25 Aug 2023 10:17:14.082 * DB saved on disk
2023-08-25 06:17:14 archivist-redis  | 152:C 25 Aug 2023 10:17:14.083 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:17:14 archivist-redis  | 8:M 25 Aug 2023 10:17:14.163 * Background saving terminated with success
2023-08-25 06:22:15 archivist-redis  | 8:M 25 Aug 2023 10:22:15.057 * 100 changes in 300 seconds. Saving...
2023-08-25 06:22:15 archivist-redis  | 8:M 25 Aug 2023 10:22:15.058 * Background saving started by pid 153
2023-08-25 06:22:15 archivist-redis  | 153:C 25 Aug 2023 10:22:15.070 * DB saved on disk
2023-08-25 06:22:15 archivist-redis  | 153:C 25 Aug 2023 10:22:15.071 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:22:15 archivist-redis  | 8:M 25 Aug 2023 10:22:15.159 * Background saving terminated with success
2023-08-25 06:24:13 tubearchivist    | [2023-08-25 06:24:13,134: WARNING/ForkPoolWorker-64] Lx__y_OIPd4: get metadata from youtube
2023-08-25 06:24:15 tubearchivist    | [2023-08-25 06:24:15,228: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:24:44 tubearchivist    | [2023-08-25 06:24:44,642: WARNING/ForkPoolWorker-64] 4NX5K-FUB-k: Downloading video
2023-08-25 06:27:16 archivist-redis  | 8:M 25 Aug 2023 10:27:16.067 * 100 changes in 300 seconds. Saving...
2023-08-25 06:27:16 archivist-redis  | 8:M 25 Aug 2023 10:27:16.068 * Background saving started by pid 154
2023-08-25 06:27:16 archivist-redis  | 154:C 25 Aug 2023 10:27:16.086 * DB saved on disk
2023-08-25 06:27:16 archivist-redis  | 154:C 25 Aug 2023 10:27:16.088 * RDB: 1 MB of memory used by copy-on-write
2023-08-25 06:27:16 archivist-redis  | 8:M 25 Aug 2023 10:27:16.169 * Background saving terminated with success
2023-08-25 06:32:17 archivist-redis  | 8:M 25 Aug 2023 10:32:17.019 * 100 changes in 300 seconds. Saving...
2023-08-25 06:32:17 archivist-redis  | 8:M 25 Aug 2023 10:32:17.020 * Background saving started by pid 155
2023-08-25 06:32:17 archivist-redis  | 155:C 25 Aug 2023 10:32:17.034 * DB saved on disk
2023-08-25 06:32:17 archivist-redis  | 155:C 25 Aug 2023 10:32:17.036 * RDB: 1 MB of memory used by copy-on-write
2023-08-25 06:32:17 archivist-redis  | 8:M 25 Aug 2023 10:32:17.121 * Background saving terminated with success
2023-08-25 06:37:18 archivist-redis  | 8:M 25 Aug 2023 10:37:18.030 * 100 changes in 300 seconds. Saving...
2023-08-25 06:37:18 archivist-redis  | 8:M 25 Aug 2023 10:37:18.031 * Background saving started by pid 156
2023-08-25 06:37:18 archivist-redis  | 156:C 25 Aug 2023 10:37:18.049 * DB saved on disk
2023-08-25 06:37:18 archivist-redis  | 156:C 25 Aug 2023 10:37:18.050 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:37:18 archivist-redis  | 8:M 25 Aug 2023 10:37:18.132 * Background saving terminated with success
2023-08-25 06:38:33 tubearchivist    | [2023-08-25 06:38:33,081: WARNING/ForkPoolWorker-64] 4NX5K-FUB-k: get metadata from youtube
2023-08-25 06:38:35 tubearchivist    | [2023-08-25 06:38:35,360: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:38:59 tubearchivist    | [2023-08-25 06:38:59,332: WARNING/ForkPoolWorker-64] 5eHK9kazvyM: Downloading video
2023-08-25 06:42:19 archivist-redis  | 8:M 25 Aug 2023 10:42:19.069 * 100 changes in 300 seconds. Saving...
2023-08-25 06:42:19 archivist-redis  | 8:M 25 Aug 2023 10:42:19.069 * Background saving started by pid 157
2023-08-25 06:42:19 archivist-redis  | 157:C 25 Aug 2023 10:42:19.089 * DB saved on disk
2023-08-25 06:42:19 archivist-redis  | 157:C 25 Aug 2023 10:42:19.091 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:42:19 archivist-redis  | 8:M 25 Aug 2023 10:42:19.170 * Background saving terminated with success
2023-08-25 06:46:15 tubearchivist    | [2023-08-25 06:46:15,833: WARNING/ForkPoolWorker-64] 5eHK9kazvyM: get metadata from youtube
2023-08-25 06:46:18 tubearchivist    | [2023-08-25 06:46:18,158: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:46:56 tubearchivist    | [2023-08-25 06:46:56,110: WARNING/ForkPoolWorker-64] z5zUzYBF_Yk: Downloading video
2023-08-25 06:47:20 archivist-redis  | 8:M 25 Aug 2023 10:47:20.011 * 100 changes in 300 seconds. Saving...
2023-08-25 06:47:20 archivist-redis  | 8:M 25 Aug 2023 10:47:20.013 * Background saving started by pid 158
2023-08-25 06:47:20 archivist-redis  | 158:C 25 Aug 2023 10:47:20.032 * DB saved on disk
2023-08-25 06:47:20 archivist-redis  | 158:C 25 Aug 2023 10:47:20.033 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:47:20 archivist-redis  | 8:M 25 Aug 2023 10:47:20.113 * Background saving terminated with success
2023-08-25 06:47:39 tubearchivist    | [2023-08-25 06:47:39,718: WARNING/ForkPoolWorker-64] z5zUzYBF_Yk: get metadata from youtube
2023-08-25 06:47:44 tubearchivist    | [2023-08-25 06:47:44,497: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:47:52 tubearchivist    | [2023-08-25 06:47:52,882: WARNING/ForkPoolWorker-64] -Cx6vUi2dq8: Downloading video
2023-08-25 06:48:03 tubearchivist    | [2023-08-25 06:48:03,971: WARNING/ForkPoolWorker-64] -Cx6vUi2dq8: get metadata from youtube
2023-08-25 06:48:06 tubearchivist    | [2023-08-25 06:48:06,044: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:48:07 tubearchivist    | [2023-08-25 06:48:07,115: WARNING/ForkPoolWorker-64] YbkdkBKhlgY: Downloading video
2023-08-25 06:52:21 archivist-redis  | 8:M 25 Aug 2023 10:52:21.095 * 100 changes in 300 seconds. Saving...
2023-08-25 06:52:21 archivist-redis  | 8:M 25 Aug 2023 10:52:21.097 * Background saving started by pid 159
2023-08-25 06:52:21 archivist-redis  | 159:C 25 Aug 2023 10:52:21.114 * DB saved on disk
2023-08-25 06:52:21 archivist-redis  | 159:C 25 Aug 2023 10:52:21.117 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:52:21 archivist-redis  | 8:M 25 Aug 2023 10:52:21.197 * Background saving terminated with success
2023-08-25 06:52:59 tubearchivist    | [2023-08-25 06:52:59,584: WARNING/ForkPoolWorker-64] YbkdkBKhlgY: get metadata from youtube
2023-08-25 06:53:01 tubearchivist    | [2023-08-25 06:53:01,633: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 06:53:09 tubearchivist    | [2023-08-25 06:53:09,286: WARNING/ForkPoolWorker-64] qtIdkYr8nKE: Downloading video
2023-08-25 06:57:22 archivist-redis  | 8:M 25 Aug 2023 10:57:22.043 * 100 changes in 300 seconds. Saving...
2023-08-25 06:57:22 archivist-redis  | 8:M 25 Aug 2023 10:57:22.045 * Background saving started by pid 160
2023-08-25 06:57:22 archivist-redis  | 160:C 25 Aug 2023 10:57:22.056 * DB saved on disk
2023-08-25 06:57:22 archivist-redis  | 160:C 25 Aug 2023 10:57:22.058 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 06:57:22 archivist-redis  | 8:M 25 Aug 2023 10:57:22.145 * Background saving terminated with success
2023-08-25 07:02:23 archivist-redis  | 8:M 25 Aug 2023 11:02:23.009 * 100 changes in 300 seconds. Saving...
2023-08-25 07:02:23 archivist-redis  | 8:M 25 Aug 2023 11:02:23.011 * Background saving started by pid 161
2023-08-25 07:02:23 archivist-redis  | 161:C 25 Aug 2023 11:02:23.032 * DB saved on disk
2023-08-25 07:02:23 archivist-redis  | 161:C 25 Aug 2023 11:02:23.035 * RDB: 1 MB of memory used by copy-on-write
2023-08-25 07:02:23 archivist-redis  | 8:M 25 Aug 2023 11:02:23.112 * Background saving terminated with success
2023-08-25 07:06:27 tubearchivist    | [2023-08-25 07:06:27,983: WARNING/ForkPoolWorker-64] qtIdkYr8nKE: get metadata from youtube
2023-08-25 07:06:30 tubearchivist    | [2023-08-25 07:06:30,218: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 07:06:54 tubearchivist    | [2023-08-25 07:06:54,115: WARNING/ForkPoolWorker-64] ykb6ItOBrpU: Downloading video
2023-08-25 07:07:24 archivist-redis  | 8:M 25 Aug 2023 11:07:24.097 * 100 changes in 300 seconds. Saving...
2023-08-25 07:07:24 archivist-redis  | 8:M 25 Aug 2023 11:07:24.099 * Background saving started by pid 162
2023-08-25 07:07:24 archivist-redis  | 162:C 25 Aug 2023 11:07:24.118 * DB saved on disk
2023-08-25 07:07:24 archivist-redis  | 162:C 25 Aug 2023 11:07:24.119 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 07:07:24 archivist-redis  | 8:M 25 Aug 2023 11:07:24.201 * Background saving terminated with success
2023-08-25 07:09:10 tubearchivist    | [2023-08-25 07:09:10,282: WARNING/Fo[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
2023-08-25 07:09:10 tubearchivist    | [2023-08-25 07:09:10,282: WARNING/Fo[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
2023-08-25 07:09:10 tubearchivist    | [2023-08-25 07:09:10,317: WARNING/ForkPoolWorker-64] ykb6ItOBrpU: Downloading video
2023-08-25 07:09:17 tubearchivist    | [2023-08-25 07:09:17,929: WARNING/ForkPoolWorker-64] ykb6ItOBrpU: get metadata from youtube
2023-08-25 07:09:20 tubearchivist    | [2023-08-25 07:09:20,118: WARNING/ForkPoolWorker-64] UCW1C2xOfXsIzPgjXyuhkw9g: get metadata from es
2023-08-25 07:09:20 tubearchivist    | [2023-08-25 07:09:20,133: WARNING/ForkPoolWorker-64] 05731d8e-63d7-4ce0-a8af-adebe82b005c Failed callback
2023-08-25 07:09:20 tubearchivist    | [2023-08-25 07:09:20,136: ERROR/ForkPoolWorker-64] Task download_pending[05731d8e-63d7-4ce0-a8af-adebe82b005c] raised unexpected: FileNotFoundError()
2023-08-25 07:09:20 tubearchivist    | Traceback (most recent call last):
2023-08-25 07:09:20 tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2023-08-25 07:09:20 tubearchivist    |     R = retval = fun(*args, **kwargs)
2023-08-25 07:09:20 tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^
2023-08-25 07:09:20 tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023-08-25 07:09:20 tubearchivist    |     return self.run(*args, **kwargs)
2023-08-25 07:09:20 tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/tasks.py", line 205, in download_pending
2023-08-25 07:09:20 tubearchivist    |     videos_downloaded = downloader.run_queue(auto_only=auto_only)
2023-08-25 07:09:20 tubearchivist    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
2023-08-25 07:09:20 tubearchivist    |     vid_dict = index_new_video(
2023-08-25 07:09:20 tubearchivist    |                ^^^^^^^^^^^^^^^^
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/src/index/video.py", line 405, in index_new_video
2023-08-25 07:09:20 tubearchivist    |     video.build_json()
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/src/index/video.py", line 157, in build_json
2023-08-25 07:09:20 tubearchivist    |     self.add_player(media_path)
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/src/index/video.py", line 251, in add_player
2023-08-25 07:09:20 tubearchivist    |     vid_path = media_path or self.build_dl_cache_path()
2023-08-25 07:09:20 tubearchivist    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25 07:09:20 tubearchivist    |   File "/app/home/src/index/video.py", line 247, in build_dl_cache_path
2023-08-25 07:09:20 tubearchivist    |     raise FileNotFoundError
2023-08-25 07:09:20 tubearchivist    | FileNotFoundError
2023-08-25 07:09:20 tubearchivist    | [2023-08-25 07:09:20,138: WARNING/ForkPoolWorker-64] 05731d8e-63d7-4ce0-a8af-adebe82b005c return callback
2023-08-25 07:12:25 archivist-redis  | 8:M 25 Aug 2023 11:12:25.019 * 100 changes in 300 seconds. Saving...
2023-08-25 07:12:25 archivist-redis  | 8:M 25 Aug 2023 11:12:25.021 * Background saving started by pid 163
2023-08-25 07:12:25 archivist-redis  | 163:C 25 Aug 2023 11:12:25.042 * DB saved on disk
2023-08-25 07:12:25 archivist-redis  | 163:C 25 Aug 2023 11:12:25.043 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 07:12:25 archivist-redis  | 8:M 25 Aug 2023 11:12:25.122 * Background saving terminated with success
2023-08-25 08:12:26 archivist-redis  | 8:M 25 Aug 2023 12:12:26.070 * 1 changes in 3600 seconds. Saving...
2023-08-25 08:12:26 archivist-redis  | 8:M 25 Aug 2023 12:12:26.071 * Background saving started by pid 164
2023-08-25 08:12:26 archivist-redis  | 164:C 25 Aug 2023 12:12:26.093 * DB saved on disk
2023-08-25 08:12:26 archivist-redis  | 164:C 25 Aug 2023 12:12:26.094 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 08:12:26 archivist-redis  | 8:M 25 Aug 2023 12:12:26.172 * Background saving terminated with success
2023-08-25 09:12:27 archivist-redis  | 8:M 25 Aug 2023 13:12:27.016 * 1 changes in 3600 seconds. Saving...
2023-08-25 09:12:27 archivist-redis  | 8:M 25 Aug 2023 13:12:27.017 * Background saving started by pid 165
2023-08-25 09:12:27 archivist-redis  | 165:C 25 Aug 2023 13:12:27.038 * DB saved on disk
2023-08-25 09:12:27 archivist-redis  | 165:C 25 Aug 2023 13:12:27.039 * RDB: 0 MB of memory used by copy-on-write
2023-08-25 09:12:27 archivist-redis  | 8:M 25 Aug 2023 13:12:27.118 * Background saving terminated with success
```

**Comment by bbilly1** [comment]
Can't reproduce that, that's all working fine for me, e.g.: 
```
tubearchivist  | [2023-08-26 20:26:21,758: INFO/MainProcess] Task download_pending[57a61839-8d89-46f0-a706-06fc0ee44efe] received
tubearchivist  | [2023-08-26 20:26:21,759: WARNING/ForkPoolWorker-4] download_pending create callback
tubearchivist  | [2023-08-26 20:26:21,801: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: Downloading video
tubearchivist  | akBpQ-A7mCQ: change status to ignore
tubearchivist  | U7qF0_SyFAY: change status to ignore
tubearchivist  | [2023-08-26 20:26:39,317: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: get metadata from youtube
tubearchivist  | [2023-08-26 20:26:41,517: WARNING/ForkPoolWorker-4] UCH4BNI0-FOK2dMXoFtViWHw: get metadata from es
tubearchivist  | [2023-08-26 20:26:41,554: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: get ryd stats
tubearchivist  | [2023-08-26 20:26:42,058: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: get sponsorblock timestamps
tubearchivist  | [2023-08-26 20:26:42,583: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: sponsorblock failed: 404
tubearchivist  | [2023-08-26 20:26:42,585: WARNING/ForkPoolWorker-4] I6As7KhrFQ4-en: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:26:42,586: WARNING/ForkPoolWorker-4] I6As7KhrFQ4-de: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:26:42,586: WARNING/ForkPoolWorker-4] I6As7KhrFQ4-de: get auto generated subtitles
tubearchivist  | [2023-08-26 20:26:43,456: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: Downloading video
tubearchivist  | [2023-08-26 20:26:58,093: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: get metadata from youtube
tubearchivist  | [2023-08-26 20:26:59,586: WARNING/ForkPoolWorker-4] UCH4BNI0-FOK2dMXoFtViWHw: get metadata from es
tubearchivist  | [2023-08-26 20:26:59,631: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: get ryd stats
tubearchivist  | [2023-08-26 20:27:00,083: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: get sponsorblock timestamps
tubearchivist  | [2023-08-26 20:27:00,696: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU-en: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:27:00,696: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU-de: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:27:00,697: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU-de: get auto generated subtitles
tubearchivist  | [2023-08-26 20:27:01,413: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: Downloading video
tubearchivist  | Filter download view ignored only: True
tubearchivist  | akBpQ-A7mCQ: change status to pending
tubearchivist  | U7qF0_SyFAY: change status to pending
tubearchivist  | Filter download view ignored only: False
tubearchivist  | [2023-08-26 20:27:20,037: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: get metadata from youtube
tubearchivist  | [2023-08-26 20:27:21,602: WARNING/ForkPoolWorker-4] UCH4BNI0-FOK2dMXoFtViWHw: get metadata from es
tubearchivist  | [2023-08-26 20:27:21,649: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: get ryd stats
tubearchivist  | [2023-08-26 20:27:22,099: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: get sponsorblock timestamps
tubearchivist  | [2023-08-26 20:27:22,609: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: sponsorblock failed: 404
tubearchivist  | [2023-08-26 20:27:22,611: WARNING/ForkPoolWorker-4] DlGQDGR1FFk-en: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:27:22,612: WARNING/ForkPoolWorker-4] DlGQDGR1FFk-de: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:27:22,612: WARNING/ForkPoolWorker-4] DlGQDGR1FFk-de: get auto generated subtitles
tubearchivist  | [2023-08-26 20:27:23,491: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: Downloading video
tubearchivist  | [2023-08-26 20:27:38,217: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: get metadata from youtube
tubearchivist  | [task][57a61839-8d89-46f0-a706-06fc0ee44efe]: received STOP signal.
tubearchivist  | [2023-08-26 20:27:59,958: WARNING/ForkPoolWorker-4] UCH4BNI0-FOK2dMXoFtViWHw: get metadata from es
tubearchivist  | [2023-08-26 20:27:59,998: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: get ryd stats
tubearchivist  | [2023-08-26 20:28:00,396: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: get sponsorblock timestamps
tubearchivist  | [2023-08-26 20:28:00,909: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ-en: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:28:00,910: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ-de: get user uploaded subtitles
tubearchivist  | [2023-08-26 20:28:00,910: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ-de: get auto generated subtitles
tubearchivist  | [2023-08-26 20:28:01,749: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: get comments
tubearchivist  | [2023-08-26 20:28:08,012: WARNING/ForkPoolWorker-4] akBpQ-A7mCQ: upload comments
tubearchivist  | [2023-08-26 20:28:08,055: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: get comments
tubearchivist  | [2023-08-26 20:28:16,055: WARNING/ForkPoolWorker-4] DlGQDGR1FFk: upload comments
tubearchivist  | [2023-08-26 20:28:16,102: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: get comments
tubearchivist  | [2023-08-26 20:28:23,628: WARNING/ForkPoolWorker-4] 0ZhbURd6xvU: upload comments
tubearchivist  | [2023-08-26 20:28:23,675: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: get comments
tubearchivist  | [2023-08-26 20:29:01,040: WARNING/ForkPoolWorker-4] I6As7KhrFQ4: upload comments
tubearchivist  | [2023-08-26 20:29:01,070: WARNING/ForkPoolWorker-4] 57a61839-8d89-46f0-a706-06fc0ee44efe success callback
tubearchivist  | [2023-08-26 20:29:01,071: INFO/ForkPoolWorker-4] Task download_pending[57a61839-8d89-46f0-a706-06fc0ee44efe] succeeded in 159.31118122199996s: 'downloaded 4 videos.'
tubearchivist  | [2023-08-26 20:29:01,071: WARNING/ForkPoolWorker-4] 57a61839-8d89-46f0-a706-06fc0ee44efe return callback
```
Ignoring the next in line, then unignoring, aka set status to pending again and it will download that next.

I'm assuming this problem came from the 500 error above:
```
[2023-08-25 07:09:10,282: WARNING/Fo[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
```
That resulted in a corrupted file somehow?

At least you know which video failed, so you can add it again if you want to. But ultimately, can't reproduce it, probably not worth spending too much time figuring out what exactly happened here. Except if you want to and want to provide a fix for that... Otherwise, probably best to restart and try again.

At the end of the day, a small amount of instability is to be expected, you are using YouTube in an unintended way, yt-dlp in the mix, then TA on top of that, you can see how things can be wonky if any of these things in the chain don't behave as expected.
