### ISSUE TITLE
[Bug]: Information about channels is not loaded

### ISSUE THREAD

**Issue by Druidblack** [tubearchivist/tubearchivist#540]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux (docker)

### Your Bug Report

Information about channels is not loaded.  I tried deleting the cache folder. At the first video downloads, the channel information is loaded, after a few videos, the channel information stops loading.

### Relevant log output

```shell
: INFO/MainProcess] Task extract_download[b6aa366c-f7c5-41f9-b739-d2e1191c6801] received
[2023-09-05 11:48:21,459: WARNING/ForkPoolWorker-16] extract_download create callback
[2023-09-05 11:48:21,530: WARNING/ForkPoolWorker-16] 87uPNMugld0: [1/1]: add to queue
[2023-09-05 11:48:23,524: WARNING/ForkPoolWorker-16] b6aa366c-f7c5-41f9-b739-d2e1191c6801 success callback
[2023-09-05 11:48:23,525: INFO/MainProcess] Task download_pending[dcb4ec84-ff51-4cf0-a2b1-2b72bfee8138] received
[2023-09-05 11:48:23,526: WARNING/ForkPoolWorker-1] download_pending create callback
[2023-09-05 11:48:23,526: INFO/ForkPoolWorker-16] Task extract_download[b6aa366c-f7c5-41f9-b739-d2e1191c6801] succeeded in 2.066020165999362s: None
[2023-09-05 11:48:23,526: WARNING/ForkPoolWorker-16] b6aa366c-f7c5-41f9-b739-d2e1191c6801 return callback
[2023-09-05 11:48:23,597: WARNING/ForkPoolWorker-1] 87uPNMugld0: Downloading video
[2023-09-05 11:48:53,297: WARNING/ForkPoolWorker-1] 87uPNMugld0: get metadata from youtube
[2023-09-05 11:48:54,950: WARNING/ForkPoolWorker-1] UCpFl6cp4SeUeSOpUp5o01OA: get metadata from es
[2023-09-05 11:48:54,955: WARNING/ForkPoolWorker-1] {"_index":"ta_channel","_id":"UCpFl6cp4SeUeSOpUp5o01OA","found":false}
[2023-09-05 11:48:54,955: WARNING/ForkPoolWorker-1] UCpFl6cp4SeUeSOpUp5o01OA: get metadata from youtube
[2023-09-05 11:48:55,520: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:48:55,520: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-09-05 11:48:56,027: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:48:56,027: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-09-05 11:48:56,632: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:48:56,633: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-09-05 11:48:57,138: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:48:57,138: WARNING/ForkPoolWorker-1] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-09-05 11:48:57,141: WARNING/ForkPoolWorker-1] ERROR: [youtube:tab] UCpFl6cp4SeUeSOpUp5o01OA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-05 11:48:57,141: WARNING/ForkPoolWorker-1] https://www.youtube.com/channel/UCpFl6cp4SeUeSOpUp5o01OA/about: failed to get info from youtube with message ERROR: [youtube:tab] UCpFl6cp4SeUeSOpUp5o01OA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-05 11:48:57,141: WARNING/ForkPoolWorker-1] UCpFl6cp4SeUeSOpUp5o01OA: fallback to video metadata
[2023-09-05 11:48:57,309: WARNING/ForkPoolWorker-1] 87uPNMugld0: get ryd stats
[2023-09-05 11:48:57,516: WARNING/ForkPoolWorker-1] 87uPNMugld0: get sponsorblock timestamps
[2023-09-05 11:48:57,775: WARNING/ForkPoolWorker-1] 87uPNMugld0: sponsorblock failed: 404
[2023-09-05 11:48:57,776: WARNING/ForkPoolWorker-1] 87uPNMugld0-ru: get user uploaded subtitles
[2023-09-05 11:48:57,777: WARNING/ForkPoolWorker-1] 87uPNMugld0-ru: get auto generated subtitles
[2023-09-05 11:48:58,989: WARNING/ForkPoolWorker-1] 87uPNMugld0: get comments
[2023-09-05 11:48:59,551: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:49:01,323: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 11:49:01,323: WARNING/ForkPoolWorker-1] WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[2023-09-05 11:49:03,084: WARNING/ForkPoolWorker-1] 87uPNMugld0: upload comments
[2023-09-05 11:49:03,112: WARNING/ForkPoolWorker-1] dcb4ec84-ff51-4cf0-a2b1-2b72bfee8138 success callback
[2023-09-05 11:49:03,114: INFO/ForkPoolWorker-1] Task download_pending[dcb4ec84-ff51-4cf0-a2b1-2b72bfee8138] succeeded in 39.585822305001784s: 'downloaded 1 videos.'
[2023-09-05 11:49:03,114: WARNING/ForkPoolWorker-1] dcb4ec84-ff51-4cf0-a2b1-2b72bfee8138 return callback
```

### Anything else?

<a href="https://fastpic.org/view/122/2023/0905/48cf9a56c620bdd0c4f66385d1f954eb.jpg.html" target="_blank"><img src="https://i122.fastpic.org/thumb/2023/0905/eb/48cf9a56c620bdd0c4f66385d1f954eb.jpeg" border="0"></a>

<a href="https://fastpic.org/view/122/2023/0905/6cecd62c56bac9f5f78aab3b6f4988e4.jpg.html" target="_blank"><img src="https://i122.fastpic.org/thumb/2023/0905/e4/6cecd62c56bac9f5f78aab3b6f4988e4.jpeg" border="0"></a>

**Comment by neonmaus** [comment]
Operating System
Linux (docker)
TubeArchivist v0.4.1

Your Bug Report
I think I have the same error when I try to subscribe to a new channel

It is about this channel
https://www.youtube.com/@kaisackmann

![image](https://github.com/tubearchivist/tubearchivist/assets/11020494/8f169593-ccdb-46ef-85e0-a385d9f3a753)

Relevant log output

```
[2023-09-05 20:51:38,159: INFO/MainProcess] Task subscribe_to[39b9fa8f-fcdf-4be1-9b1b-641176e7192a] received
[2023-09-05 20:51:38,160: WARNING/ForkPoolWorker-8] subscribe_to create callback
[2023-09-05 20:51:38,518: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:38,519: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-09-05 20:51:38,742: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:38,743: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-09-05 20:51:38,959: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:38,960: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-09-05 20:51:39,182: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:39,183: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-09-05 20:51:39,755: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:39,756: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-09-05 20:51:40,004: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:40,004: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-09-05 20:51:40,227: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:40,227: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-09-05 20:51:40,558: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:40,558: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-09-05 20:51:40,926: WARNING/ForkPoolWorker-8] UCjqqRC_Y-7acAEjKyo23e4A: get metadata from es
[2023-09-05 20:51:40,934: WARNING/ForkPoolWorker-8] {"_index":"ta_channel","_id":"UCjqqRC_Y-7acAEjKyo23e4A","found":false}
[2023-09-05 20:51:40,934: WARNING/ForkPoolWorker-8] UCjqqRC_Y-7acAEjKyo23e4A: get metadata from youtube
[2023-09-05 20:51:41,335: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:41,335: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-09-05 20:51:41,569: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:41,570: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-09-05 20:51:41,805: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:41,806: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-09-05 20:51:42,024: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-05 20:51:42,024: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-09-05 20:51:42,026: WARNING/ForkPoolWorker-8] ERROR: [youtube:tab] UCjqqRC_Y-7acAEjKyo23e4A: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-05 20:51:42,026: WARNING/ForkPoolWorker-8] https://www.youtube.com/channel/UCjqqRC_Y-7acAEjKyo23e4A/about: failed to get info from youtube with message ERROR: [youtube:tab] UCjqqRC_Y-7acAEjKyo23e4A: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-05 20:51:42,030: WARNING/ForkPoolWorker-8] 39b9fa8f-fcdf-4be1-9b1b-641176e7192a Failed callback
[2023-09-05 20:51:42,032: ERROR/ForkPoolWorker-8] Task subscribe_to[39b9fa8f-fcdf-4be1-9b1b-641176e7192a] raised unexpected: TypeError("'bool' object is not subscriptable")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 351, in subscribe_to
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
  File "/app/home/src/download/subscriptions.py", line 342, in subscribe
    self.subscribe_type(item, expected_type=expected_type)
  File "/app/home/src/download/subscriptions.py", line 369, in subscribe_type
    self._subscribe(channel_id)
  File "/app/home/src/download/subscriptions.py", line 373, in _subscribe
    ChannelSubscription().change_subscribe(
  File "/app/home/src/download/subscriptions.py", line 144, in change_subscribe
    channel.build_json()
  File "/app/home/src/index/channel.py", line 49, in build_json
    self.process_youtube_meta()
  File "/app/home/src/index/channel.py", line 57, in process_youtube_meta
    self.youtube_meta["thumbnails"].reverse()
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
[2023-09-05 20:51:42,033: WARNING/ForkPoolWorker-8] 39b9fa8f-fcdf-4be1-9b1b-641176e7192a return callback
```

**Comment by Druidblack** [comment]
I found a solution to my problem. If the channel data has not loaded, then you need to turn off Sync YouTube cookies in the chrome extension (version 0.1.4) and turn it on again. After that, you can click the reindexer and the data will load. Perhaps there is no such problem in the extension version 0.2.0, but it is not yet available for chrome.

**Comment by neonmaus** [comment]
I have now also tested this, but according to the log the cookie became invalid, which is probably due to this bug:
https://github.com/tubearchivist/browser-extension/issues/22

But because I didn't have a valid cookie anymore I was able to download the channel :D

**Comment by bbilly1** [comment]
consolidating all yt-dlp related errors in #522.
