### ISSUE TITLE
can't update to 0.4.1 error in new mappings to index ta_comment

### ISSUE THREAD

**Issue by stephennord** [tubearchivist/tubearchivist#543]
Hi,
Can't update to 0..4.1 due to error at applying new mappings to index ta_comment...
Other new mappings are complete.
ta_channel index is created and up to date...
2023-09-07T04:39:02.587845650Z ta_video index is created and up to date...
2023-09-07T04:39:02.600584952Z ta_download index is created and up to date...
2023-09-07T04:39:02.612285037Z ta_playlist index is created and up to date...
2023-09-07T04:39:02.624264292Z ta_subtitle index is created and up to date...
2023-09-07T04:39:02.636013197Z detected mapping change: comment_last_refresh, {'type': 'date', 'format': 'epoch_second'}
2023-09-07T04:39:02.653881936Z snapshot: executing now: {'snapshot_name': 'ta_daily_-rvwa6z5ys8u694hv8treia'}
2023-09-07T04:39:03.676822855Z snapshot: ta_daily_-rvwa6z5ys8u694hv8treia in state IN_PROGRESS
2023-09-07T04:39:03.722789205Z snapshot: wait to complete
2023-09-07T04:39:08.691475600Z snapshot: ta_daily_-rvwa6z5ys8u694hv8treia in state IN_PROGRESS
2023-09-07T04:39:08.692119790Z snapshot: wait to complete
2023-09-07T04:39:13.704759666Z snapshot: completed - {'snapshots': [{'snapshot': 'ta_daily_-rvwa6z5ys8u694hv8treia', 'uuid': 'Yzaf9B-uQkio1j4xqsia4Q', 'repository': 'ta_snapshot', 'version_id': 8090099, 'version': '8.9.0', 'indices': ['ta_playlist', '.geoip_databases', 'ta_comment', 'ta_channel', 'ta_video', 'ta_subtitle', 'ta_download'], 'data_streams': [], 'include_global_state': True, 'metadata': {'policy': 'ta_daily'}, 'state': 'SUCCESS', 'start_time': '2023-09-07T04:39:02.500Z', 'start_time_in_millis': 1694061542500, 'end_time': '2023-09-07T04:39:06.502Z', 'end_time_in_millis': 1694061546502, 'duration_in_millis': 4002, 'failures': [], 'shards': {'total': 7, 'failed': 0, 'successful': 7}, 'feature_states': [{'feature_name': 'geoip', 'indices': ['.geoip_databases']}]}], 'total': 1, 'remaining': 0}
2023-09-07T04:39:13.705421755Z applying new mappings to index ta_comment...
2023-09-07T04:39:13.705484919Z create new blank index with name ta_comment...
error={"root_cause":[{"type":"resource_already_exists_exception","reason":"index [ta_comment_backup/4-fxpwSXSGqpBX383Ae8eA] already exists","index_uuid":"4-fxpwSXSGqpBX383Ae8eA","index":"ta_comment_backup"}],"type":"resource_already_exists_exception","reason":"index [ta_comment_backup/4-fxpwSXSGqpBX383Ae8eA] already exists","index_uuid":"4-fxpwSXSGqpBX383Ae8eA","index":"ta_comment_backup"} status=400 
2023-09-07T04:39:13.717101539Z {'settings': {'analysis': {'normalizer': {'to_lower': {'type': 'custom', 'filter': ['lowercase']}}}, 'number_of_replicas': '0'}, 'mappings': {'properties': {'youtube_id': {'type': 'keyword'}, 'comment_last_refresh': {'type': 'date', 'format': 'epoch_second'}, 'comment_channel_id': {'type': 'keyword'}, 'comment_comments': {'properties': {'comment_id': {'type': 'keyword'}, 'comment_text': {'type': 'text'}, 'comment_timestamp': {'type': 'date', 'format': 'epoch_second'}, 'comment_time_text': {'type': 'text'}, 'comment_likecount': {'type': 'long'}, 'comment_is_favorited': {'type': 'boolean'}, 'comment_author': {'type': 'text', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256, 'normalizer': 'to_lower'}}}, 'comment_author_id': {'type': 'keyword'}, 'comment_author_thumbnail': {'type': 'keyword'}, 'comment_author_is_uploader': {'type': 'boolean'}, 'comment_parent': {'type': 'keyword'}}}}}}
2023-09-07T04:39:13.717102780Z Traceback (most recent call last):
2023-09-07T04:39:13.717450777Z   File "/app/manage.py", line 23, in <module>
2023-09-07T04:39:13.717511711Z     main()
2023-09-07T04:39:13.717554607Z   File "/app/manage.py", line 19, in main
2023-09-07T04:39:13.717600428Z     execute_from_command_line(sys.argv)
2023-09-07T04:39:13.717661207Z   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2023-09-07T04:39:13.717724645Z     utility.execute()
2023-09-07T04:39:13.717772419Z   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2023-09-07T04:39:13.718072862Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2023-09-07T04:39:13.718209626Z   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2023-09-07T04:39:13.718451831Z     self.execute(*args, **cmd_options)
2023-09-07T04:39:13.718524385Z   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2023-09-07T04:39:13.718767464Z     output = self.handle(*args, **options)
2023-09-07T04:39:13.718892822Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-07T04:39:13.718943249Z   File "/app/config/management/commands/ta_startup.py", line 43, in handle
2023-09-07T04:39:13.719099327Z     self._mig_index_setup()
2023-09-07T04:39:13.719241114Z   File "/app/config/management/commands/ta_startup.py", line 143, in _mig_index_setup
2023-09-07T04:39:13.719341142Z     ElasitIndexWrap().setup()
2023-09-07T04:39:13.719427874Z   File "/app/home/src/es/index_setup.py", line 161, in setup
2023-09-07T04:39:13.719601344Z     handler.rebuild_index()
2023-09-07T04:39:13.719720483Z   File "/app/home/src/es/index_setup.py", line 99, in rebuild_index
2023-09-07T04:39:13.719801358Z     self.create_blank(for_backup=True)
2023-09-07T04:39:13.719866086Z   File "/app/home/src/es/index_setup.py", line 139, in create_blank
2023-09-07T04:39:13.720025375Z     _, _ = ElasticWrap(path).put(data)
2023-09-07T04:39:13.720143956Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-07T04:39:13.720210931Z   File "/app/home/src/es/connect.py", line 77, in put
2023-09-07T04:39:13.720309982Z     raise ValueError("failed to add item to index")
2023-09-07T04:39:13.720610472Z ValueError: failed to add item to index

**Comment by bbilly1** [comment]
follow the steps here: https://docs.tubearchivist.com/advanced/#es-mapping-migrations-troubleshooting

**Comment by stephennord** [comment]
Thanks. all done.

**Comment by mortalkombatlegend92** [comment]
Hi, I have the same issue when trying to update to 0.4.1, but removing ta_comment like the wiki page you posted describes causes me to lose all of my archived comments, luckily i am running this in a vm so i have a snapshot before I deleted the ta_comment index but is there a way to fix this so tubearchivist can run without deleting my archived comments?

**Comment by bbilly1** [comment]
Take another close look at that wiki page. This suggests to delete the `_backup` index, not the main index:

> First make sure you have the original index still with the command above, after verifying that, stop the TA container then you can delete the _backup index e.g. in the case of ta_comment_backup

Obviously if you delete your main index, all your comments will be gone.

**Comment by mortalkombatlegend92** [comment]
Well I tried that first which just caused me to have the same problem so I thought since it was ta_comment giving me problems I had to delete ta_comment

**Comment by mortalkombatlegend92** [comment]
Here's my logs 
`{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:53.595726959Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:53.595817774Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:28:53.595829173Z"}
{"log":"#  Environment Setup  #\n","stream":"stdout","time":"2023-09-09T01:28:53.595834139Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:28:53.595838763Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:53.59584324Z"}
{"log":"[1] checking expected env vars\n","stream":"stdout","time":"2023-09-09T01:28:53.595940574Z"}
{"log":"    ✓ all expected env vars are set\n","stream":"stdout","time":"2023-09-09T01:28:53.59605397Z"}
{"log":"[2] set default ES user\n","stream":"stdout","time":"2023-09-09T01:28:53.596127393Z"}
{"log":"    ✓ ES user is set to elastic\n","stream":"stdout","time":"2023-09-09T01:28:53.596241346Z"}
{"log":"[3] check TA_PORT overwrite\n","stream":"stdout","time":"2023-09-09T01:28:53.596312477Z"}
{"log":"    TA_PORT is not set\n","stream":"stdout","time":"2023-09-09T01:28:53.596399914Z"}
{"log":"[4] check TA_UWSGI_PORT overwrite\n","stream":"stdout","time":"2023-09-09T01:28:53.596514736Z"}
{"log":"    TA_UWSGI_PORT is not set\n","stream":"stdout","time":"2023-09-09T01:28:53.596600213Z"}
{"log":"[5] check ENABLE_CAST overwrite\n","stream":"stdout","time":"2023-09-09T01:28:53.596670128Z"}
{"log":"    ENABLE_CAST is not set\n","stream":"stdout","time":"2023-09-09T01:28:53.596753995Z"}
{"log":"[6] create superuser\n","stream":"stdout","time":"2023-09-09T01:28:53.596823245Z"}
{"log":"    superuser already created\n","stream":"stdout","time":"2023-09-09T01:28:53.599685772Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:54.950291552Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:54.950346674Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:28:54.950354255Z"}
{"log":"#  Connection check   #\n","stream":"stdout","time":"2023-09-09T01:28:54.950359056Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:28:54.950363547Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:28:54.950367944Z"}
{"log":"[1] connect to Redis\n","stream":"stdout","time":"2023-09-09T01:28:54.95037238Z"}
{"log":"    ✓ Redis connection verified\n","stream":"stdout","time":"2023-09-09T01:28:54.953878149Z"}
{"log":"[2] set Redis config\n","stream":"stdout","time":"2023-09-09T01:28:54.95390921Z"}
{"log":"    ✓ Redis config set\n","stream":"stdout","time":"2023-09-09T01:28:54.955351411Z"}
{"log":"[3] connect to Elastic Search\n","stream":"stdout","time":"2023-09-09T01:28:54.955368944Z"}
{"log":"    ... waiting for ES [0/24]\n","stream":"stdout","time":"2023-09-09T01:28:54.955374571Z"}
{"log":"    ... waiting for ES [1/24]\n","stream":"stdout","time":"2023-09-09T01:28:59.968300297Z"}
{"log":"    ... waiting for ES [2/24]\n","stream":"stdout","time":"2023-09-09T01:29:04.975032021Z"}
{"log":"    ... waiting for ES [3/24]\n","stream":"stdout","time":"2023-09-09T01:29:09.988766749Z"}
{"log":"    ... waiting for ES [4/24]\n","stream":"stdout","time":"2023-09-09T01:29:14.994060494Z"}
{"log":"    ... waiting for ES [5/24]\n","stream":"stdout","time":"2023-09-09T01:29:19.99974435Z"}
{"log":"    ... waiting for ES [6/24]\n","stream":"stdout","time":"2023-09-09T01:29:25.012898398Z"}
{"log":"    ... waiting for ES [7/24]\n","stream":"stdout","time":"2023-09-09T01:29:31.0626531Z"}
{"log":"    ✓ ES connection established\n","stream":"stdout","time":"2023-09-09T01:29:31.168097374Z"}
{"log":"[4] Elastic Search version check\n","stream":"stdout","time":"2023-09-09T01:29:31.168135692Z"}
{"log":"    ✓ ES version check passed\n","stream":"stdout","time":"2023-09-09T01:29:31.177571133Z"}
{"log":"[5] check ES path.repo env var\n","stream":"stdout","time":"2023-09-09T01:29:31.17760834Z"}
{"log":"    ✓ path.repo env var is set\n","stream":"stdout","time":"2023-09-09T01:29:31.298646506Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:29:33.514417187Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:29:33.514492297Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:29:33.514507179Z"}
{"log":"#  Application Start  #\n","stream":"stdout","time":"2023-09-09T01:29:33.514518096Z"}
{"log":"#######################\n","stream":"stdout","time":"2023-09-09T01:29:33.51452671Z"}
{"log":"\n","stream":"stdout","time":"2023-09-09T01:29:33.514531811Z"}
{"log":"[1] set new config.json values\n","stream":"stdout","time":"2023-09-09T01:29:33.515414534Z"}
{"log":"    no new config values\n","stream":"stdout","time":"2023-09-09T01:29:33.519697727Z"}
{"log":"[2] create expected cache folders\n","stream":"stdout","time":"2023-09-09T01:29:33.51997007Z"}
{"log":"    ✓ expected folders created\n","stream":"stdout","time":"2023-09-09T01:29:33.522139737Z"}
{"log":"[3] clear leftover locks in redis\n","stream":"stdout","time":"2023-09-09T01:29:33.522411946Z"}
{"log":"    no locks found\n","stream":"stdout","time":"2023-09-09T01:29:33.525261245Z"}
{"log":"[4] clear task leftovers\n","stream":"stdout","time":"2023-09-09T01:29:33.525655189Z"}
{"log":"[5] clear leftover files from dl cache\n","stream":"stdout","time":"2023-09-09T01:29:33.531001062Z"}
{"log":"clear download cache\n","stream":"stdout","time":"2023-09-09T01:29:33.533054655Z"}
{"log":"    no files found\n","stream":"stdout","time":"2023-09-09T01:29:33.533425525Z"}
{"log":"[6] check for first run after update\n","stream":"stdout","time":"2023-09-09T01:29:33.533654874Z"}
{"log":"    ✓ update to v0.4.1 completed\n","stream":"stdout","time":"2023-09-09T01:29:33.53696172Z"}
{"log":"[MIGRATION] validate index mappings\n","stream":"stdout","time":"2023-09-09T01:29:33.537367332Z"}
{"log":"ta_channel index is created and up to date...\n","stream":"stdout","time":"2023-09-09T01:29:33.587516355Z"}
{"log":"ta_video index is created and up to date...\n","stream":"stdout","time":"2023-09-09T01:29:33.609224555Z"}
{"log":"ta_download index is created and up to date...\n","stream":"stdout","time":"2023-09-09T01:29:33.635197547Z"}
{"log":"ta_playlist index is created and up to date...\n","stream":"stdout","time":"2023-09-09T01:29:33.675258801Z"}
{"log":"ta_subtitle index is created and up to date...\n","stream":"stdout","time":"2023-09-09T01:29:33.697996505Z"}
{"log":"detected mapping change: comment_last_refresh, {'type': 'date', 'format': 'epoch_second'}\n","stream":"stdout","time":"2023-09-09T01:29:33.709860423Z"}
{"log":"snapshot: executing now: {'snapshot_name': 'ta_daily_-sapye8qrtxwjoivhpadrgg'}\n","stream":"stdout","time":"2023-09-09T01:29:33.847806755Z"}
{"log":"snapshot: completed - {'snapshots': [{'snapshot': 'ta_daily_-sapye8qrtxwjoivhpadrgg', 'uuid': 'VMN0O3PnSDyfwW_pkBhgjg', 'repository': 'ta_snapshot', 'version_id': 8090099, 'version': '8.9.0', 'indices': ['ta_channel', 'ta_comment', 'ta_subtitle', 'ta_video', 'ta_playlist', 'ta_download'], 'data_streams': [], 'include_global_state': True, 'metadata': {'policy': 'ta_daily'}, 'state': 'SUCCESS', 'start_time': '2023-09-09T01:29:33.845Z', 'start_time_in_millis': 1694222973845, 'end_time': '2023-09-09T01:29:34.245Z', 'end_time_in_millis': 1694222974245, 'duration_in_millis': 400, 'failures': [], 'shards': {'total': 6, 'failed': 0, 'successful': 6}, 'feature_states': []}], 'total': 1, 'remaining': 0}\n","stream":"stdout","time":"2023-09-09T01:29:35.103445868Z"}
{"log":"applying new mappings to index ta_comment...\n","stream":"stdout","time":"2023-09-09T01:29:35.103515454Z"}
{"log":"create new blank index with name ta_comment...\n","stream":"stdout","time":"2023-09-09T01:29:35.103529229Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-09-09T01:29:43.654783464Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n","stream":"stderr","time":"2023-09-09T01:29:43.65515495Z"}
{"log":"    response = self._make_request(\n","stream":"stderr","time":"2023-09-09T01:29:43.655338281Z"}
{"log":"               ^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.655446523Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n","stream":"stderr","time":"2023-09-09T01:29:43.656153013Z"}
{"log":"    response = conn.getresponse()\n","stream":"stderr","time":"2023-09-09T01:29:43.656167433Z"}
{"log":"               ^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.656173201Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connection.py\", line 461, in getresponse\n","stream":"stderr","time":"2023-09-09T01:29:43.656303982Z"}
{"log":"    httplib_response = super().getresponse()\n","stream":"stderr","time":"2023-09-09T01:29:43.656322589Z"}
{"log":"                       ^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.65633291Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 1375, in getresponse\n","stream":"stderr","time":"2023-09-09T01:29:43.656342649Z"}
{"log":"    response.begin()\n","stream":"stderr","time":"2023-09-09T01:29:43.656605068Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 318, in begin\n","stream":"stderr","time":"2023-09-09T01:29:43.73208655Z"}
{"log":"    version, status, reason = self._read_status()\n","stream":"stderr","time":"2023-09-09T01:29:43.732152725Z"}
{"log":"                              ^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732164162Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 287, in _read_status\n","stream":"stderr","time":"2023-09-09T01:29:43.732173441Z"}
{"log":"    raise RemoteDisconnected(\"Remote end closed connection without\"\n","stream":"stderr","time":"2023-09-09T01:29:43.732182679Z"}
{"log":"http.client.RemoteDisconnected: Remote end closed connection without response\n","stream":"stderr","time":"2023-09-09T01:29:43.732191855Z"}
{"log":"\n","stream":"stderr","time":"2023-09-09T01:29:43.732201457Z"}
{"log":"During handling of the above exception, another exception occurred:\n","stream":"stderr","time":"2023-09-09T01:29:43.732210261Z"}
{"log":"\n","stream":"stderr","time":"2023-09-09T01:29:43.732219543Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-09-09T01:29:43.732227853Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n","stream":"stderr","time":"2023-09-09T01:29:43.732236119Z"}
{"log":"    resp = conn.urlopen(\n","stream":"stderr","time":"2023-09-09T01:29:43.732244654Z"}
{"log":"           ^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732252685Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n","stream":"stderr","time":"2023-09-09T01:29:43.732261304Z"}
{"log":"    retries = retries.increment(\n","stream":"stderr","time":"2023-09-09T01:29:43.732269672Z"}
{"log":"              ^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732278347Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/util/retry.py\", line 470, in increment\n","stream":"stderr","time":"2023-09-09T01:29:43.73228688Z"}
{"log":"    raise reraise(type(error), error, _stacktrace)\n","stream":"stderr","time":"2023-09-09T01:29:43.732295153Z"}
{"log":"          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732303157Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/util/util.py\", line 38, in reraise\n","stream":"stderr","time":"2023-09-09T01:29:43.732311923Z"}
{"log":"    raise value.with_traceback(tb)\n","stream":"stderr","time":"2023-09-09T01:29:43.732319707Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n","stream":"stderr","time":"2023-09-09T01:29:43.732327358Z"}
{"log":"    response = self._make_request(\n","stream":"stderr","time":"2023-09-09T01:29:43.732335261Z"}
{"log":"               ^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732342852Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n","stream":"stderr","time":"2023-09-09T01:29:43.732351171Z"}
{"log":"    response = conn.getresponse()\n","stream":"stderr","time":"2023-09-09T01:29:43.732389481Z"}
{"log":"               ^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732398666Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/urllib3/connection.py\", line 461, in getresponse\n","stream":"stderr","time":"2023-09-09T01:29:43.73240696Z"}
{"log":"    httplib_response = super().getresponse()\n","stream":"stderr","time":"2023-09-09T01:29:43.732415712Z"}
{"log":"                       ^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732424913Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 1375, in getresponse\n","stream":"stderr","time":"2023-09-09T01:29:43.732433258Z"}
{"log":"    response.begin()\n","stream":"stderr","time":"2023-09-09T01:29:43.732442023Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 318, in begin\n","stream":"stderr","time":"2023-09-09T01:29:43.73245169Z"}
{"log":"    version, status, reason = self._read_status()\n","stream":"stderr","time":"2023-09-09T01:29:43.732461898Z"}
{"log":"                              ^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.732470889Z"}
{"log":"  File \"/usr/local/lib/python3.11/http/client.py\", line 287, in _read_status\n","stream":"stderr","time":"2023-09-09T01:29:43.732480276Z"}
{"log":"    raise RemoteDisconnected(\"Remote end closed connection without\"\n","stream":"stderr","time":"2023-09-09T01:29:43.732491784Z"}
{"log":"urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n","stream":"stderr","time":"2023-09-09T01:29:43.732502349Z"}
{"log":"\n","stream":"stderr","time":"2023-09-09T01:29:43.732511487Z"}
{"log":"During handling of the above exception, another exception occurred:\n","stream":"stderr","time":"2023-09-09T01:29:43.732519315Z"}
{"log":"\n","stream":"stderr","time":"2023-09-09T01:29:43.732527688Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-09-09T01:29:43.732535367Z"}
{"log":"  File \"/app/manage.py\", line 23, in \u003cmodule\u003e\n","stream":"stderr","time":"2023-09-09T01:29:43.732545037Z"}
{"log":"    main()\n","stream":"stderr","time":"2023-09-09T01:29:43.804262529Z"}
{"log":"  File \"/app/manage.py\", line 19, in main\n","stream":"stderr","time":"2023-09-09T01:29:43.804405404Z"}
{"log":"    execute_from_command_line(sys.argv)\n","stream":"stderr","time":"2023-09-09T01:29:43.804421276Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py\", line 442, in execute_from_command_line\n","stream":"stderr","time":"2023-09-09T01:29:43.804431005Z"}
{"log":"    utility.execute()\n","stream":"stderr","time":"2023-09-09T01:29:43.80444051Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py\", line 436, in execute\n","stream":"stderr","time":"2023-09-09T01:29:43.804449002Z"}
{"log":"    self.fetch_command(subcommand).run_from_argv(self.argv)\n","stream":"stderr","time":"2023-09-09T01:29:43.806496085Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/django/core/management/base.py\", line 412, in run_from_argv\n","stream":"stderr","time":"2023-09-09T01:29:43.806977212Z"}
{"log":"    self.execute(*args, **cmd_options)\n","stream":"stderr","time":"2023-09-09T01:29:43.808034484Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/django/core/management/base.py\", line 458, in execute\n","stream":"stderr","time":"2023-09-09T01:29:43.808500424Z"}
{"log":"    output = self.handle(*args, **options)\n","stream":"stderr","time":"2023-09-09T01:29:43.809716429Z"}
{"log":"             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:43.814697583Z"}
{"log":"  File \"/app/config/management/commands/ta_startup.py\", line 43, in handle\n","stream":"stderr","time":"2023-09-09T01:29:43.815309565Z"}
{"log":"    self._mig_index_setup()\n","stream":"stderr","time":"2023-09-09T01:29:43.966245941Z"}
{"log":"  File \"/app/config/management/commands/ta_startup.py\", line 143, in _mig_index_setup\n","stream":"stderr","time":"2023-09-09T01:29:43.966285236Z"}
{"log":"    ElasitIndexWrap().setup()\n","stream":"stderr","time":"2023-09-09T01:29:43.966291585Z"}
{"log":"  File \"/app/home/src/es/index_setup.py\", line 161, in setup\n","stream":"stderr","time":"2023-09-09T01:29:43.966296344Z"}
{"log":"    handler.rebuild_index()\n","stream":"stderr","time":"2023-09-09T01:29:44.100378727Z"}
{"log":"  File \"/app/home/src/es/index_setup.py\", line 100, in rebuild_index\n","stream":"stderr","time":"2023-09-09T01:29:44.100426556Z"}
{"log":"    self.reindex(\"backup\")\n","stream":"stderr","time":"2023-09-09T01:29:44.100439783Z"}
{"log":"  File \"/app/home/src/es/index_setup.py\", line 116, in reindex\n","stream":"stderr","time":"2023-09-09T01:29:44.100449416Z"}
{"log":"    _, _ = ElasticWrap(\"_reindex?refresh=true\").post(data=data)\n","stream":"stderr","time":"2023-09-09T01:29:44.100458999Z"}
{"log":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.100468778Z"}
{"log":"  File \"/app/home/src/es/connect.py\", line 58, in post\n","stream":"stderr","time":"2023-09-09T01:29:44.100479256Z"}
{"log":"    response = requests.post(\n","stream":"stderr","time":"2023-09-09T01:29:44.160406689Z"}
{"log":"               ^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.160456772Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n","stream":"stderr","time":"2023-09-09T01:29:44.160467998Z"}
{"log":"    return request(\"post\", url, data=data, json=json, **kwargs)\n","stream":"stderr","time":"2023-09-09T01:29:44.160477516Z"}
{"log":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.160486567Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n","stream":"stderr","time":"2023-09-09T01:29:44.160495577Z"}
{"log":"    return session.request(method=method, url=url, **kwargs)\n","stream":"stderr","time":"2023-09-09T01:29:44.170823926Z"}
{"log":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.170893273Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n","stream":"stderr","time":"2023-09-09T01:29:44.170905382Z"}
{"log":"    resp = self.send(prep, **send_kwargs)\n","stream":"stderr","time":"2023-09-09T01:29:44.170914769Z"}
{"log":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.170923533Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n","stream":"stderr","time":"2023-09-09T01:29:44.170931976Z"}
{"log":"    r = adapter.send(request, **kwargs)\n","stream":"stderr","time":"2023-09-09T01:29:44.170940906Z"}
{"log":"        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-09-09T01:29:44.170949329Z"}
{"log":"  File \"/root/.local/lib/python3.11/site-packages/requests/adapters.py\", line 501, in send\n","stream":"stderr","time":"2023-09-09T01:29:44.170958092Z"}
{"log":"    raise ConnectionError(err, request=request)\n","stream":"stderr","time":"2023-09-09T01:29:44.170966833Z"}
{"log":"requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n","stream":"stderr","time":"2023-09-09T01:29:44.170977117Z"}`
