### ISSUE TITLE
[Installation]: ValueError: Invalid weekday literal '*:'.

### ISSUE THREAD

**Issue by MartinR577** [tubearchivist/tubearchivist#550]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

WSL2 Linux ubuntu 

### Your installation or setup question

After a reboot Tubearchivist shows the  errors like "ValueError: Invalid weekday literal '*:'."  in the log. is there a Config file i can edit to look for and replace the asterisks?

### Relevant log output

```shell
raise ValueError(f'Invalid weekday literal {s!r}.')
ValueError: Invalid weekday literal '*:'.
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 300, in _expand_number
    i = int(s)
        ^^^^^^
ValueError: invalid literal for int() with base 10: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/utils/time.py", line 254, in weekday
    return WEEKDAYS[abbreviation]
           ~~~~~~~~^^^^^^^^^^^^^^
KeyError: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 303, in _expand_number
    i = weekday(s)
        ^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/utils/time.py", line 257, in weekday
    raise KeyError(name)
KeyError: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 365, in <module>
    app.conf.beat_schedule = ScheduleBuilder().build_schedule()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/ta/config.py", line 302, in build_schedule
    "schedule": crontab(
                ^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 406, in __init__
    self.day_of_week = self._expand_cronspec(day_of_week, 7)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 443, in _expand_cronspec
    result = crontab_parser(max_, min_).parse(cronspec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 263, in parse
    acc |= set(self._parse_part(part))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 271, in _parse_part
    return self._expand_range((part,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 274, in _expand_range
    fr = self._expand_number(toks[0])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 305, in _expand_number
    raise ValueError(f'Invalid weekday literal {s!r}.')
ValueError: Invalid weekday literal '*:'.
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 300, in _expand_number
    i = int(s)
        ^^^^^^
ValueError: invalid literal for int() with base 10: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/utils/time.py", line 254, in weekday
    return WEEKDAYS[abbreviation]
           ~~~~~~~~^^^^^^^^^^^^^^
KeyError: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 303, in _expand_number
    i = weekday(s)
        ^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/utils/time.py", line 257, in weekday
    raise KeyError(name)
KeyError: '*:'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings.py", line 20, in <module>
    from home.src.ta.config import AppConfig
  File "/app/home/__init__.py", line 3, in <module>
    from .tasks import app as celery_app
  File "/app/home/tasks.py", line 365, in <module>
    app.conf.beat_schedule = ScheduleBuilder().build_schedule()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/ta/config.py", line 302, in build_schedule
    "schedule": crontab(
                ^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 406, in __init__
    self.day_of_week = self._expand_cronspec(day_of_week, 7)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 443, in _expand_cronspec
    result = crontab_parser(max_, min_).parse(cronspec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 263, in parse
    acc |= set(self._parse_part(part))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 271, in _parse_part
    return self._expand_range((part,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 274, in _expand_range
    fr = self._expand_number(toks[0])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/schedules.py", line 305, in _expand_number
    raise ValueError(f'Invalid weekday literal {s!r}.')
ValueError: Invalid weekday literal '*:'.
```

**Comment by lamusmaser** [comment]
This is not handled through a configuration file, but instead through Redis.

Follow the instructions [here](https://github.com/tubearchivist/tubearchivist/issues/492#issuecomment-1620796838) to get Redis back into a working state. Let us know if you run into any issues following those instructions.

**Comment by bbilly1** [comment]
assuming this has been solver by now.
