### ISSUE TITLE
[Bug]: Task failed: 'bool' object does not support item assignment

### ISSUE THREAD

**Issue by Stefomat** [tubearchivist/tubearchivist#558]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian 11

## Describe the bug
When trying to subscribe to a playlist or add a playlist to the download queue, I get the error mentioned in the title.
The job abborts, without adding or subscribing the playlist. This has happened now for a few weeks.
In the tubearchivist docker logs there can be seen yt-dlp error messages, leading to the abortion of the job.
I can reproduce these errors (Incomplete yt initial data received/unable to extract yt initial data) with a manual standalone install of yt-dlp in version 2023.07.06.
If I then update to the newest version of yt-dlp (2023.09.04) there are no more errors and the extraction and download work fine.

My guess is, that tubearchivist would work again if updated to the newest yt-dlp version.
How is the procedure for this? Will it be included in the next release of tubearchivist?
Can I help by providing more information and/or testing a new version?

## Steps To Reproduce
Install tubearchivist in version 0.4.1 and try to download or subscribe to any playlist on youtube.

## Expected behavior
tubearchivist should subscribe to the playlist without problems.

### Relevant log output

```shell
https://www.youtube.com/playlist?list=PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7
[2023-09-24 16:03:34,488: INFO/MainProcess] Task subscribe_to[35ada8eb-283c-4430-8377-73226b7876ed] received
[2023-09-24 16:03:34,489: WARNING/ForkPoolWorker-4] subscribe_to create callback
[2023-09-24 16:03:34,775: WARNING/ForkPoolWorker-4] PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7: get metadata from es
[2023-09-24 16:03:34,782: WARNING/ForkPoolWorker-4] {"_index":"ta_playlist","_id":"PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7","found":false}
[2023-09-24 16:03:34,782: WARNING/ForkPoolWorker-4] PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7: get metadata from youtube
[2023-09-24 16:03:35,080: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-24 16:03:35,080: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-09-24 16:03:35,267: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-24 16:03:35,267: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-09-24 16:03:35,467: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-24 16:03:35,468: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-09-24 16:03:35,647: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-09-24 16:03:35,648: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-09-24 16:03:35,649: WARNING/ForkPoolWorker-4] ERROR: [youtube:tab] PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-24 16:03:35,649: WARNING/ForkPoolWorker-4] https://www.youtube.com/playlist?list=PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7: failed to get info from youtube with message ERROR: [youtube:tab] PLGWGc5dfbzn_uSMm5jfeaPcpDWo5olbN7: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-09-24 16:03:35,653: WARNING/ForkPoolWorker-4] 35ada8eb-283c-4430-8377-73226b7876ed Failed callback
[2023-09-24 16:03:35,655: ERROR/ForkPoolWorker-4] Task subscribe_to[35ada8eb-283c-4430-8377-73226b7876ed] raised unexpected: TypeError("'bool' object does not support item assignment")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 351, in subscribe_to
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
  File "/app/home/src/download/subscriptions.py", line 342, in subscribe
    self.subscribe_type(item, expected_type=expected_type)
  File "/app/home/src/download/subscriptions.py", line 352, in subscribe_type
    PlaylistSubscription().process_url_str([item])
  File "/app/home/src/download/subscriptions.py", line 190, in process_url_str
    playlist_h.json_data["playlist_subscribed"] = subscribed
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object does not support item assignment
[2023-09-24 16:03:35,656: WARNING/ForkPoolWorker-4] 35ada8eb-283c-4430-8377-73226b7876ed return callback
```

### Anything else?

Thank you for Tube Archivist!

**Comment by bbilly1** [comment]
let's consolidate all yt-dlp related things in #522. But ultimately I need to add a mention not to open issues with yt-dlp errors here.
