### ISSUE TITLE
[Bug]: Task failed: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by LucasR3C3** [tubearchivist/tubearchivist#565]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology > Docker

## Describe the bug
Error when trying to download a playlist "Task failed: 'bool' object has no attribute 'get'"
## Steps To Reproduce
Downloads > Add to download queue > Copy&paste the entire URL "https://www.youtube.com/playlist?list=XXXXXXXXXXX" and click on "Download now"
## Expected behavior
Download all the videos in the playlist

### Relevant log output

```shell
date	stream	content
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,447: WARNING/ForkPoolWorker-4] ea30d22d-86c8-4a43-997e-9f64a79e9859 return callback
2023/10/06 18:24:54	stderr	AttributeError: 'bool' object has no attribute 'get'
2023/10/06 18:24:54	stderr	                    ^^^^^^^^^^^^^^^^^^^^^^
2023/10/06 18:24:54	stderr	    video_results = playlist.json_data.get("playlist_entries")
2023/10/06 18:24:54	stderr	  File "/app/home/src/download/queue.py", line 232, in _parse_playlist
2023/10/06 18:24:54	stderr	    self._parse_playlist(entry["url"])
2023/10/06 18:24:54	stderr	  File "/app/home/src/download/queue.py", line 199, in _process_entry
2023/10/06 18:24:54	stderr	    self._process_entry(entry)
2023/10/06 18:24:54	stderr	  File "/app/home/src/download/queue.py", line 182, in parse_url_list
2023/10/06 18:24:54	stderr	    pending_handler.parse_url_list()
2023/10/06 18:24:54	stderr	  File "/app/home/tasks.py", line 223, in extrac_dl
2023/10/06 18:24:54	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/06 18:24:54	stderr	    return self.run(*args, **kwargs)
2023/10/06 18:24:54	stderr	  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023/10/06 18:24:54	stderr	                 ^^^^^^^^^^^^^^^^^^^^
2023/10/06 18:24:54	stderr	    R = retval = fun(*args, **kwargs)
2023/10/06 18:24:54	stderr	  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2023/10/06 18:24:54	stderr	Traceback (most recent call last):
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,447: ERROR/ForkPoolWorker-4] Task extract_download[ea30d22d-86c8-4a43-997e-9f64a79e9859] raised unexpected: AttributeError("'bool' object has no attribute 'get'")
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,444: WARNING/ForkPoolWorker-4] ea30d22d-86c8-4a43-997e-9f64a79e9859 Failed callback
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,442: WARNING/ForkPoolWorker-4] https://www.youtube.com/playlist?list=XXXXXXXXXXX: failed to get info from youtube with message ERROR: Incomplete data received
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,442: WARNING/ForkPoolWorker-4] ERROR: Incomplete data received
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,320: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,198: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
2023/10/06 18:24:54	stderr	[2023-10-06 18:24:54,081: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
2023/10/06 18:24:53	stderr	[2023-10-06 18:24:53,212: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
2023/10/06 18:24:53	stderr	[2023-10-06 18:24:53,212: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,938: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,938: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,642: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,642: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,304: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
2023/10/06 18:24:52	stderr	[2023-10-06 18:24:52,304: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023/10/06 18:24:51	stderr	[2023-10-06 18:24:51,894: WARNING/ForkPoolWorker-4] XXXXXXXXXXX: get metadata from youtube
2023/10/06 18:24:51	stderr	[2023-10-06 18:24:51,893: WARNING/ForkPoolWorker-4] {"_index":"ta_playlist","_id":"XXXXXXXXXXX","found":false}
2023/10/06 18:24:51	stderr	[2023-10-06 18:24:51,885: WARNING/ForkPoolWorker-4] XXXXXXXXXXX: get metadata from es
2023/10/06 18:24:51	stderr	[2023-10-06 18:24:51,838: WARNING/ForkPoolWorker-4] extract_download create callback
2023/10/06 18:24:51	stderr	[2023-10-06 18:24:51,837: INFO/MainProcess] Task extract_download[ea30d22d-86c8-4a43-997e-9f64a79e9859] received
```

**Comment by lamusmaser** [comment]
consolidate all yt-dlp errors in https://github.com/tubearchivist/tubearchivist/issues/522.
