### ISSUE TITLE
[Bug]: Manual import fails if files are placed in a directory with extension

### ISSUE THREAD

**Issue by dot-mike** [tubearchivist/tubearchivist#575]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

For reference, I'm importing from my legacy collection where the directory is `<channel name>/<channel name> - <video date> - <video title>/<channel name> - <video date> - <video title>  [<video id>].<ext>`.

Normally, I've had no issues importing files nested in directories, but today a specific channel failed import because the  video title contains a file extension.

For reference this is how I organized the Tubearchivist import folder:
```
└── directory: cache
    └── directory: import
        └── directory: 4chong - 20160111 - Heehee.mp4
            ├── file: 4chong - 20160111 - Heehee [wUBpd3SJ5ik].mp4
            ├── file: 4chong - 20160111 - Heehee [wUBpd3SJ5ik].jpg
            └── file: 4chong - 20160111 - Heehee [wUBpd3SJ5ik].info.json
```

### Relevant log output

```shell
[1;33m[2023-10-21 23:53:21,669: WARNING/ForkPoolWorker-4] 30212e8b-2378-44b7-9160-d67dbc54add3 return callback[0m
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'bool'[0m
  File "<frozen genericpath>", line 152, in _check_arg_types
  File "<frozen posixpath>", line 90, in join
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    json_path = os.path.join(self.CACHE_DIR, "import", json_file)
  File "/app/home/src/index/manual.py", line 196, in _extract_id_from_json
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    youtube_id = self._extract_id_from_json(current_video["metadata"])
  File "/app/home/src/index/manual.py", line 171, in _detect_youtube_id
    self._detect_youtube_id(current_video)
  File "/app/home/src/index/manual.py", line 139, in process_videos
    self.process_videos()
  File "/app/home/src/index/manual.py", line 55, in scan
    ImportFolderScanner(task=self).scan()
  File "/app/home/tasks.py", line 271, in run_manual_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.run(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
                 ^^^^^^^^^^^^^^^^^^^^
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Traceback (most recent call last):
[1;31m[2023-10-21 23:53:21,667: ERROR/ForkPoolWorker-4] Task manual_import[30212e8b-2378-44b7-9160-d67dbc54add3] raised unexpected: TypeError("join() argument must be str, bytes, or os.PathLike object, not 'bool'")
[1;33m[2023-10-21 23:53:21,664: WARNING/ForkPoolWorker-4] 30212e8b-2378-44b7-9160-d67dbc54add3 Failed callback[0m
[1;33m[2023-10-21 23:53:21,659: WARNING/ForkPoolWorker-4] id extraction failed from filename: /cache/import/4chong - 20160320 - hehe.mp4[0m
[1;33m[2023-10-21 23:53:21,656: WARNING/ForkPoolWorker-4] manual import: {'media': '/cache/import/4chong - 20160320 - hehe.mp4', 'video_id': False, 'metadata': False, 'thumb': False, 'subtitle': []}[0m
[1;33m[2023-10-21 23:53:21,554: WARNING/ForkPoolWorker-4] manual_import create callback[0m
[2023-10-21 23:53:21,553: INFO/MainProcess] Task manual_import[30212e8b-2378-44b7-9160-d67dbc54add3] received
```

**Comment by Jefferderp** [comment]
To clarify for future readers, because I was confused at first, this error will occur if your files being imported are not following the [proper naming convention](https://docs.tubearchivist.com/settings/actions/#manual-media-files-import).
