### ISSUE TITLE
[Bug]: Youtube Channel About Page Changed to Popout, yt-dlp Can No Longer Properly Parse Channel Metadata

### ISSUE THREAD

**Issue by trafficman** [tubearchivist/tubearchivist#587]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
It seems that youtube has modified channel pages, eliminating the About tab and replacing it with a popup, which yt-dlp cannot currently parse properly, meaning new channels cannot properly be indexed. A single video download will succeed and make an entry for the new channel, but all metadata (images, description, total views, etc) will be missing, and attempting to add a playlist from a new unindexed channel will fail completely with an error (the attached logs are from attempting to do just that). Videos and playlists added from channels that have already been indexed still function as normal as far as I can tell.
## Steps To Reproduce
Add a playlist from a new unindexed channel to the download queue OR Download any single video from a channel that has never been indexed in the past, then view that channel within TA

### Relevant log output

```shell
[2023-11-08 04:41:07,197: INFO/MainProcess] Task extract_download[9c3a14d1-ba6b-4661-81fe-9d6810741e98] received
[2023-11-08 04:41:07,201: WARNING/ForkPoolWorker-4] extract_download create callback
[2023-11-08 04:41:07,560: WARNING/ForkPoolWorker-4] PLYm7pAszOR7QVCNC6qYi0Px4nfPtGJpwh: get metadata from es
[2023-11-08 04:41:07,678: WARNING/ForkPoolWorker-4] PLYm7pAszOR7QVCNC6qYi0Px4nfPtGJpwh: get metadata from es
[2023-11-08 04:41:07,809: WARNING/ForkPoolWorker-4] UCf-vV5woXPFpkvZKwooWoyw: get metadata from es
[2023-11-08 04:41:07,812: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UCf-vV5woXPFpkvZKwooWoyw","found":false}
[2023-11-08 04:41:07,813: WARNING/ForkPoolWorker-4] UCf-vV5woXPFpkvZKwooWoyw: get metadata from youtube
[2023-11-08 04:41:08,191: WARNING/ForkPoolWorker-4] ERROR: [youtube:tab] UCf-vV5woXPFpkvZKwooWoyw: This channel does not have a about tab
[2023-11-08 04:41:08,195: WARNING/ForkPoolWorker-4] 9c3a14d1-ba6b-4661-81fe-9d6810741e98 Failed callback
[2023-11-08 04:41:08,198: ERROR/ForkPoolWorker-4] Task extract_download[9c3a14d1-ba6b-4661-81fe-9d6810741e98] raised unexpected: TypeError("'bool' object is not subscriptable")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 223, in extrac_dl
    pending_handler.parse_url_list()
  File "/app/home/src/download/queue.py", line 181, in parse_url_list
    self._process_entry(entry)
  File "/app/home/src/download/queue.py", line 199, in _process_entry
    PlaylistSubscription().process_url_str([entry], subscribed=False)
  File "/app/home/src/download/subscriptions.py", line 198, in process_url_str
    self.channel_validate(playlist_h.json_data["playlist_channel_id"])
  File "/app/home/src/download/subscriptions.py", line 216, in channel_validate
    channel.build_json(upload=True)
  File "/app/home/src/index/channel.py", line 49, in build_json
    self.process_youtube_meta()
  File "/app/home/src/index/channel.py", line 57, in process_youtube_meta
    self.youtube_meta["thumbnails"].reverse()
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
[2023-11-08 04:41:08,205: WARNING/ForkPoolWorker-4] 9c3a14d1-ba6b-4661-81fe-9d6810741e98 return callback
```

**Comment by bbilly1** [comment]
newest v0.4.3 has a workaround for that, please update.

**Comment by tgzw** [comment]
> newest v0.4.3 has a workaround for that, please update.

I don't know if I'm doing something wrong but I updated it and still have the same errors

**Comment by komish** [comment]
@tgzw Seems to be working here for me. Can you confirm (in the footer of the dashboard) that you're running v0.4.3?

**Comment by tgzw** [comment]
@komish That's correct, in the footer of the webapp says v0.4.3. 
I did `docker compose pull` and `docker compose up`. My docker-compose is basically like the default but with relative paths in the volumes.  Am I missing something?

**Comment by komish** [comment]
@tgzw I couldn't tell you for certain (I'm not using compose here), but it would seem like compose isn't recreating the containers even though the image changed. The documentation I read implies that compose should be recreating containers should take place when the image changes, though.

This can be done forcefully (see: `--force-recreate`); **do this at your own risk**, as I've already mentioned I don't use compose, and I'm not associated with the project. Just another user that ran into this bug.

I'd double check a few other things before hand, e.g.
- you're using the latest image tag, which is linked to v0.4.3 to my eye https://hub.docker.com/r/bbilly1/tubearchivist/tags
- the image you have on your system has the same repo digest as what's on docker.io, e.g.
```
          "RepoDigests": [
               "docker.io/bbilly1/tubearchivist@sha256:0d64a5b291f1608017107668e05b492d8aaa50e46af671441affa9ae28949238",
          ],
```

**Comment by tgzw** [comment]
@komish Thank you so much for your input. The container was being recreated properly and the image was appropriate. The only thing I could think of that it could be was something in the persistent storage of the volumes. It is finally working normally when I deleted the contents of the redis volume folder.
