### ISSUE TITLE
[Bug]: Fetching metadata from YT fails and stops TA from continuing

### ISSUE THREAD

**Issue by nguyend24** [tubearchivist/tubearchivist#615]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian 12

## Describe the bug
This started 2-3 days ago.

YT-DLP will fail trying to get metadata occasionally which will cause whatever task TubeArchivist is running to stop. This can be Metadata Refresh, Downloading Videos, or Refreshing subscriptions. 

My metadata refresh queue has been growing and growing for the past few days (over 1000 now) since it won't finish and then the scheduled task the next day will add to it. 

For downloading videos, I can manually restart the download task, so it's only a minor annoyance, but it will usually fail again in a couple hours. 

For rescanning subscriptions, this has completely failed to complete and no videos have been added for the past few days since I have ~510 channels to scan and once the issue occurs partway through the scanning no videos will be added to the download queue. 

## Steps To Reproduce
I'm passing in a cookie to TubeArchivist.

Downloading videos, rescanning subscriptions or refreshing metadata

## Expected behavior
Maybe retry the call to get the metadata from youtube if it fails? Or still allow the process to continue

### Relevant log output

```shell
Nov 24 17:23:46 tubearchivist docker[992]: tubearchivist    | [2023-11-24 17:23:46,749: WARNING/ForkPoolWorker-4] TgJfNGnSJII: get metadata from youtube
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | [2023-11-24 17:23:57,525: WARNING/ForkPoolWorker-4] ccd6f293-4077-4c15-801e-8c5bb9d1d6f7 Failed callback
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | [2023-11-24 17:23:57,528: ERROR/ForkPoolWorker-4] Task download_pending[ccd6f293-4077-4c15-801e-8c5bb9d1d6f7] raised unexpected: TransportError("HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out.")
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | Traceback (most recent call last):
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 712, in _error_catcher
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     yield
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 812, in _raw_read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     data = self._fp_read(amt) if not fp_closed else b""
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 797, in _fp_read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self._fp.read(amt) if amt is not None else self._fp.read()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                                                       ^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/http/client.py", line 460, in read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self._read_chunked(amt)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/http/client.py", line 583, in _read_chunked
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     chunk_left = self._get_chunk_left()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/http/client.py", line 566, in _get_chunk_left
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     chunk_left = self._read_next_chunk_size()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/http/client.py", line 526, in _read_next_chunk_size
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     line = self.fp.readline(_MAXLINE + 1)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self._sock.recv_into(b)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/ssl.py", line 1278, in recv_into
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self.read(nbytes, buffer)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/ssl.py", line 1134, in read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self._sslobj.read(len, buffer)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | TimeoutError: The read operation timed out
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | The above exception was the direct cause of the following exception:
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | Traceback (most recent call last):
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 139, in read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self.fp.read(amt, decode_content=True)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 877, in read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     data = self._raw_read(amt)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 811, in _raw_read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     with self._error_catcher():
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     self.gen.throw(typ, value, traceback)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/urllib3/response.py", line 717, in _error_catcher
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out.
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | The above exception was the direct cause of the following exception:
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | Traceback (most recent call last):
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     R = retval = fun(*args, **kwargs)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self.run(*args, **kwargs)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/tasks.py", line 208, in download_pending
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     videos_downloaded = downloader.run_queue(auto_only=auto_only)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 182, in run_queue
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     vid_dict = index_new_video(
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                ^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/src/index/video.py", line 393, in index_new_video
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     video.build_json()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/src/index/video.py", line 142, in build_json
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     self.get_from_youtube()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/src/index/generic.py", line 46, in get_from_youtube
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     self.youtube_meta = YtWrap(obs_request, self.config).extract(url)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/app/home/src/download/yt_dlp_base.py", line 64, in extract
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     response = yt_dlp.YoutubeDL(self.obs).extract_info(url)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return func(self, *args, **kwargs)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     ie_result = ie.extract(url)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                 ^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     ie_result = self._real_extract(url)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                 ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4073, in _real_extract
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4032, in _download_player_responses
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     webpage = self._download_webpage(
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |               ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1118, in _download_webpage
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1069, in download_content
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 907, in _download_webpage_handle
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 979, in _webpage_read_content
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     webpage_bytes = urlh.read()
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |                     ^^^^^^^^^^^
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 160, in read
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    |     raise TransportError(cause=e) from e
Nov 24 17:23:57 tubearchivist docker[992]: tubearchivist    | yt_dlp.networking.exceptions.TransportError: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out.
```

**Comment by bbilly1** [comment]
This will timeout eventually, I think after 10 seconds. And then it should retry. If that fails it will abort. That can be a wide range of reasons, from problems in your LAN, unstable internet, ISP problems, YT throttling.

But ultimately, that is working as expected, if you don't have internet connection, this tasks should stop.
