### ISSUE TITLE
[Bug]: yt-dlp / ffmpeg failing when downloading videos

### ISSUE THREAD

**Issue by CommanderRedYT** [tubearchivist/tubearchivist#635]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
When downloading videos / download, TA gives a error about some kind of ffprobe error

![image](https://github.com/tubearchivist/tubearchivist/assets/43087936/d995e837-24ed-4ef0-b047-d028080ec18e)

## Steps To Reproduce
Tell TA to directly download a video

## Expected behavior
Video should download

### Relevant log output

```shell
[2023-12-17 20:13:35,822: WARNING/ForkPoolWorker-2] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:35,975: WARNING/ForkPoolWorker-2] toI9jJfUKnc: [180/183]: add to queue
[2023-12-17 20:13:36,943: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "toI9jJfUKnc"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:37,053: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "toI9jJfUKnc"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:37,054: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "toI9jJfUKnc"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:37,080: WARNING/ForkPoolWorker-2] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:37,297: WARNING/ForkPoolWorker-2] RKsrrZikJaw: [181/183]: add to queue
[2023-12-17 20:13:38,171: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "RKsrrZikJaw"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:38,292: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "RKsrrZikJaw"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:38,293: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "RKsrrZikJaw"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:38,311: WARNING/ForkPoolWorker-2] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:38,531: WARNING/ForkPoolWorker-2] 6KH_w53ZuYQ: [182/183]: add to queue
[2023-12-17 20:13:39,523: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "6KH_w53ZuYQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:39,633: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "6KH_w53ZuYQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:39,634: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "6KH_w53ZuYQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:39,660: WARNING/ForkPoolWorker-2] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:39,827: WARNING/ForkPoolWorker-2] a6yCQdx3Pkg: [183/183]: add to queue
[2023-12-17 20:13:40,770: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "a6yCQdx3Pkg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:40,897: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "a6yCQdx3Pkg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:40,898: WARNING/ForkPoolWorker-2] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "a6yCQdx3Pkg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:40,929: WARNING/ForkPoolWorker-2] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:41,136: INFO/MainProcess] Task download_pending[4035afa0-cc94-4991-9397-5a2dbdd520f9] received
[2023-12-17 20:13:41,139: WARNING/ForkPoolWorker-4] download_pending create callback
[2023-12-17 20:13:41,155: WARNING/ForkPoolWorker-2] 16a0176c-4f2d-4889-bf36-b5219eabc328 success callback
[2023-12-17 20:13:41,158: INFO/ForkPoolWorker-2] Task extract_download[16a0176c-4f2d-4889-bf36-b5219eabc328] succeeded in 259.4627795550041s: None
[2023-12-17 20:13:41,158: WARNING/ForkPoolWorker-2] 16a0176c-4f2d-4889-bf36-b5219eabc328 return callback
[2023-12-17 20:13:41,225: WARNING/ForkPoolWorker-4] Cz4Q4QOuoo8: Downloading video
[2023-12-17 20:13:43,057: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:43,184: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:43,185: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:43,211: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (216.0 > 93) for chapter "Recap for how slowing happens"
[2023-12-17 20:13:43,211: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (308.0 > 93) for chapter "Birefringence"
[2023-12-17 20:13:43,211: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (379.0 > 93) for chapter "The barber pole"
[2023-12-17 20:13:43,211: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (500.0 > 93) for chapter "When the refractive index is less than 1"
[2023-12-17 20:13:43,219: WARNING/ForkPoolWorker-4] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:43,838: WARNING/ForkPoolWorker-4] Cz4Q4QOuoo8: get metadata from youtube
[2023-12-17 20:13:44,748: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:44,872: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:44,873: WARNING/ForkPoolWorker-4] WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "Cz4Q4QOuoo8"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-12-17 20:13:44,899: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (216.0 > 93) for chapter "Recap for how slowing happens"
[2023-12-17 20:13:44,899: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (308.0 > 93) for chapter "Birefringence"
[2023-12-17 20:13:44,899: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (379.0 > 93) for chapter "The barber pole"
[2023-12-17 20:13:44,899: WARNING/ForkPoolWorker-4] WARNING: [youtube] Invalid start time (500.0 > 93) for chapter "When the refractive index is less than 1"
[2023-12-17 20:13:44,907: WARNING/ForkPoolWorker-4] WARNING: Only images are available for download. use --list-formats to see them
[2023-12-17 20:13:45,081: WARNING/ForkPoolWorker-4] UCMDQxm7cUx3yXkfeHa5zJIQ: get metadata from es
[2023-12-17 20:13:45,105: WARNING/ForkPoolWorker-4] 4035afa0-cc94-4991-9397-5a2dbdd520f9 Failed callback
[2023-12-17 20:13:45,107: ERROR/ForkPoolWorker-4] Task download_pending[4035afa0-cc94-4991-9397-5a2dbdd520f9] raised unexpected: CalledProcessError(1, ['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/cache/download/Cz4Q4QOuoo8.mp4'])
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 208, in download_pending
    videos_downloaded = downloader.run_queue(auto_only=auto_only)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/download/yt_dlp_handler.py", line 182, in run_queue
    vid_dict = index_new_video(
               ^^^^^^^^^^^^^^^^
  File "/app/home/src/index/video.py", line 393, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 154, in build_json
    self.add_player(media_path)
  File "/app/home/src/index/video.py", line 242, in add_player
    duration = get_duration_sec(vid_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/ta/helper.py", line 149, in get_duration_sec
    duration = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/cache/download/Cz4Q4QOuoo8.mp4']' returned non-zero exit status 1.
[2023-12-17 20:13:45,108: WARNING/ForkPoolWorker-4] 4035afa0-cc94-4991-9397-5a2dbdd520f9 return callback
[2023-12-17 20:13:45,111: ERROR/ForkPoolWorker-4] Unhandled Notification Exception
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/apprise/Apprise.py", line 565, in _notify_sequential
    result = server.notify(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/apprise/plugins/NotifyBase.py", line 288, in notify
    send_calls = list(self._build_send_calls(*args, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/apprise/plugins/NotifyBase.py", line 376, in _build_send_calls
    for chunk in self._apply_overflow(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/apprise/plugins/NotifyBase.py", line 413, in _apply_overflow
    body = '' if not body else body.rstrip()
                               ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'rstrip'
[agg][video_stats] took 13 ms to process
[agg][channel_stats] took 6 ms to process
[agg][playlist_stats] took 3 ms to process
[agg][download_queue_stats] took 6 ms to process
[agg][watch_progress] took 10 ms to process
[agg][videos_last_week] took 5 ms to process
[agg][channel_stats] took 10 ms to process
[agg][channel_stats] took 13 ms to process
[agg][channel_stats] took 19 ms to process
_index=ta_channel _index=ta_channel _id=UCVmhVuAhhqO8IvGsaM5bS4g _index=ta_channel _index=ta_channel _id=UCVmhVuAhhqO8IvGsaM5bS4g found=false
[pid: 40|app: 0|req: 803/803] 192.168.0.202 () {56 vars in 971 bytes} [Sun Dec 17 20:18:37 2023] GET /api/channel/search/?q=@hardbeats7533 => generated 426 bytes in 825 msecs (HTTP/1.0 404) 9 headers in 346 bytes (1 switches on core 0)
```

**Comment by bbilly1** [comment]
works fine for me:
```
tubearchivist  | [2023-12-18 12:57:38,336: INFO/MainProcess] Task extract_download[ea1b0356-6f80-44a3-b27e-fbea061db3c6] received
tubearchivist  | [2023-12-18 12:57:38,337: WARNING/ForkPoolWorker-4] extract_download create callback
tubearchivist  | [2023-12-18 12:57:38,390: WARNING/ForkPoolWorker-4] Cz4Q4QOuoo8: [1/1]: add to queue
tubearchivist  | [2023-12-18 12:57:41,629: INFO/MainProcess] Task download_pending[6c1791cb-937d-4ba8-b890-a1a359e39bde] received
tubearchivist  | [2023-12-18 12:57:41,630: WARNING/ForkPoolWorker-2] download_pending create callback
tubearchivist  | [2023-12-18 12:57:41,631: WARNING/ForkPoolWorker-4] ea1b0356-6f80-44a3-b27e-fbea061db3c6 success callback
tubearchivist  | [2023-12-18 12:57:41,632: INFO/ForkPoolWorker-4] Task extract_download[ea1b0356-6f80-44a3-b27e-fbea061db3c6] succeeded in 3.293997223000005s: None
tubearchivist  | [2023-12-18 12:57:41,632: WARNING/ForkPoolWorker-4] ea1b0356-6f80-44a3-b27e-fbea061db3c6 return callback
tubearchivist  | [2023-12-18 12:57:41,665: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: Downloading video
tubearchivist  | [2023-12-18 12:57:55,616: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: get metadata from youtube
tubearchivist  | [2023-12-18 12:57:57,941: WARNING/ForkPoolWorker-2] UCYO_jab_esuFRV4b17AJtAw: get metadata from es
tubearchivist  | [2023-12-18 12:57:57,944: WARNING/ForkPoolWorker-2] {"_index":"ta_channel","_id":"UCYO_jab_esuFRV4b17AJtAw","found":false}
tubearchivist  | [2023-12-18 12:57:57,945: WARNING/ForkPoolWorker-2] UCYO_jab_esuFRV4b17AJtAw: get metadata from youtube
tubearchivist  | [2023-12-18 12:57:58,628: WARNING/ForkPoolWorker-2] UCYO_jab_esuFRV4b17AJtAw: download channel thumbnail
tubearchivist  | [2023-12-18 12:58:01,570: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: get ryd stats
tubearchivist  | [2023-12-18 12:58:02,433: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: get sponsorblock timestamps
tubearchivist  | [2023-12-18 12:58:03,102: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: sponsorblock failed: 404
tubearchivist  | [2023-12-18 12:58:03,103: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8-en: get user uploaded subtitles
tubearchivist  | [2023-12-18 12:58:03,103: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8-de: get user uploaded subtitles
tubearchivist  | [2023-12-18 12:58:03,565: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: get comments
tubearchivist  | [2023-12-18 12:58:08,715: WARNING/ForkPoolWorker-2] Cz4Q4QOuoo8: upload comments
tubearchivist  | [2023-12-18 12:58:08,790: WARNING/ForkPoolWorker-2] 6c1791cb-937d-4ba8-b890-a1a359e39bde success callback
tubearchivist  | [2023-12-18 12:58:08,792: INFO/ForkPoolWorker-2] Task download_pending[6c1791cb-937d-4ba8-b890-a1a359e39bde] succeeded in 27.161016232999998s: 'downloaded 1 videos.'
tubearchivist  | [2023-12-18 12:58:08,792: WARNING/ForkPoolWorker-2] 6c1791cb-937d-4ba8-b890-a1a359e39bde return callback
```

Temporary glitch from YT? You can see a bunch of yt-dlp errors in your logs there. I'd say clear your download cach and try again.

**Comment by CommanderRedYT** [comment]
This is what is in the mp4 inside the `download` folder:

![image](https://github.com/tubearchivist/tubearchivist/assets/43087936/08a8025d-8ce3-438d-92a6-99335fb915a7)

**Comment by bbilly1** [comment]
looks like a temporary glitch on YT, returning a html like that. You could also be experiencing blocking/throtteling from YT...

When in doubt, you can always refresh metadata, so it will gather missing things.
