### ISSUE TITLE
[Bug]: Companion cookie sync makes all downloads failing with message: unable to extract yt initial data

### ISSUE THREAD

**Issue by blob42** [tubearchivist/tubearchivist#646]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

- Arch Linux (latest)
- TA: 0.4.5
- TA Companion 0.2.2 with cookie sync

## Describe the bug

All downloads are failing since I upgraded to 0.4.5. 
 
If I connect to the container and manually download using yt-dlp I don't get any errors and can download any link with yt-dlp.

### UPDATE
- I disabled the youtube cookie and the downloads started working again
- When I enable cookies the downloads fail again, so the problem is with cookie sync

## Steps To Reproduce
- Any action that triggers `yt-dlp` downloads.
- 
### Relevant log output

I am seeing this kind of errors
```
tubearchivist  | [2024-01-06 22:07:59,544: WARNING/ForkPoolWorker-32] ERROR: [youtube:tab] UCEbYhDd6c6vngsF5PQpFVWg: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-01-06 22:07:59,544: WARNING/ForkPoolWorker-32] https://www.youtube.com/channel/UCEbYhDd6c6vngsF5PQpFVWg/videos: failed to get info from youtube with message ERROR: [youtube:tab] UCEbYhDd6c6vngsF5PQpFVWg: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-01-06 22:07:59,547: WARNING/ForkPoolWorker-32] UCrqM0Ym_NbK1fqeQG2VIohg: find missing videos.
tubearchivist  | [2024-01-06 22:07:59,912: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:07:59,912: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
tubearchivist  | [2024-01-06 22:08:00,099: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:08:00,099: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
tubearchivist  | [2024-01-06 22:08:00,291: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:08:00,291: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
tubearchivist  | [2024-01-06 22:08:00,472: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:08:00,472: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries

```

Also this:

```shell
tubearchivist  | [2024-01-06 21:54:32,766: WARNING/ForkPoolWorker-32] ERROR: [youtube:tab] PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-01-06 21:54:32,766: WARNING/ForkPoolWorker-32] https://www.youtube.com/playlist?list=PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: failed to get info from youtube with message ERROR: [youtube:tab] PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-01-06 21:54:32,766: WARNING/ForkPoolWorker-32] PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: failed to extract data
tubearchivist  | [2024-01-06 21:54:32,768: WARNING/ForkPoolWorker-32] 34c5fa8e-80da-49b4-b73c-1aefaafd42b5 Failed callback
tubearchivist  | [2024-01-06 21:54:32,771: ERROR/ForkPoolWorker-32] Task subscribe_to[34c5fa8e-80da-49b4-b73c-1aefaafd42b5] raised unexpected: ValueError('PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: failed to extract data')
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
tubearchivist  |     R = retval = fun(*args, **kwargs)
tubearchivist  |                  ^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
tubearchivist  |     return self.run(*args, **kwargs)
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/app/home/tasks.py", line 356, in subscribe_to
tubearchivist  |     SubscriptionHandler(url_str, task=self).subscribe(expected_type)
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 347, in subscribe
tubearchivist  |     self.subscribe_type(item, expected_type=expected_type)
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 357, in subscribe_type
tubearchivist  |     PlaylistSubscription().process_url_str([item])
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 193, in process_url_str
tubearchivist  |     raise ValueError(message)
tubearchivist  | ValueError: PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC: failed to extract data
```
```


### Anything else?

_No response_

**Comment by blob42** [comment]
Update: actually all downloads are failing with the following messages appearing in the logs:
```
tubearchivist  | [2024-01-06 22:07:43,116: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:07:43,117: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
tubearchivist  | [2024-01-06 22:07:43,294: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:07:43,294: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
tubearchivist  | [2024-01-06 22:07:43,486: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-01-06 22:07:43,486: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
```

**Comment by blob42** [comment]
it looks like it was related to the cookie. I disabled cookie synchronisation and enable it again, the scanning seems working now. Will report if I see the same error again

**Comment by bbilly1** [comment]
Same error as mentioned in the FAQ: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled

You also see some solutions there.
