### ISSUE TITLE
[Bug]: download fails with error Task failed: failed to add item to index

### ISSUE THREAD

**Issue by sg-s** [tubearchivist/tubearchivist#651]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

macOS 14.1 (but using docker)

## Describe the bug

Unable to download any video, either by pressing the "download now" button on an individual video, or by starting downloads of videos in the queue. 

## Steps To Reproduce

- have a few videos in the queue. 
- press "start download" button 

## Expected behavior

videos to start downloading. 

### Relevant log output

```shell
2024-01-12 08:23:10 [2024-01-12 08:23:10,626: ERROR/ForkPoolWorker-4] Task download_pending[5e94bd1a-c7c5-4b66-877c-d71b6b16efd5] raised unexpected: ValueError('failed to add item to index')
2024-01-12 08:23:10 Traceback (most recent call last):
2024-01-12 08:23:10   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2024-01-12 08:23:10     R = retval = fun(*args, **kwargs)
2024-01-12 08:23:10                  ^^^^^^^^^^^^^^^^^^^^
2024-01-12 08:23:10   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2024-01-12 08:23:10     return self.run(*args, **kwargs)
2024-01-12 08:23:10            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 08:23:10   File "/app/home/tasks.py", line 208, in download_pending
2024-01-12 08:23:10     videos_downloaded = downloader.run_queue(auto_only=auto_only)
2024-01-12 08:23:10                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 08:23:10   File "/app/home/src/download/yt_dlp_handler.py", line 182, in run_queue
2024-01-12 08:23:10     vid_dict = index_new_video(
2024-01-12 08:23:10                ^^^^^^^^^^^^^^^^
2024-01-12 08:23:10   File "/app/home/src/index/video.py", line 398, in index_new_video
2024-01-12 08:23:10     video.upload_to_es()
2024-01-12 08:23:10   File "/app/home/src/index/generic.py", line 57, in upload_to_es
2024-01-12 08:23:10     _, _ = ElasticWrap(self.es_path).put(self.json_data, refresh=True)
2024-01-12 08:23:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-12 08:23:10   File "/app/home/src/es/connect.py", line 112, in put
2024-01-12 08:23:10     raise ValueError("failed to add item to index")
2024-01-12 08:23:10 ValueError: failed to add item to index
2024-01-12 08:23:10 [2024-01-12 08:23:10,626: WARNING/ForkPoolWorker-4] 5e94bd1a-c7c5-4b66-877c-d71b6b16efd5 return callback
```

### Anything else?

<img width="1107" alt="Screenshot 2024-01-12 at 08 25 03" src="https://github.com/tubearchivist/tubearchivist/assets/6005346/a9c05d46-8d03-4e38-a4ee-f052898fdd09">

**Comment by sg-s** [comment]
update: I was able to "fix" this by wiping all images for tube archivist and rebuilding

**Comment by bbilly1** [comment]
glad you got it solved.
