### ISSUE TITLE
[Installation]: Initial configuration problem on debian

### ISSUE THREAD

**Issue by BancarelValentin** [tubearchivist/tubearchivist#657]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux VIZBAB 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### Your installation or setup question

I really don't believe this is a bug but I can't make it work no matter what I try. So I hope someone here will be able to help.

I'm trying to integrate Tubearchivist to my existingdocker compose; because I came across some problems I'm now trying a minimal setup with the compose file from the readme **untouched**. I'm trying without success on a debian VM installed on UNRAID OS; but Idid manage to make it work the same commands on my PC on an ubuntu variant and it works. Here is all I do.

```sh
cd /tmp
mkdir test
cd test
nano docker-compose.yml #Here I paste the compose file from readme
docker compose up
```

On the VM, all my containers starts but redis take so much time just to be created (before producing any logs) at first boot that I had to kill it everytime, `docker compose up -d archivist-redis` by itself and then rerun the up command for all.

After they all start, Redis show it's `Accepting connections messages`; Elastic seems to start fine as well as it produce no error messages. And tubearchvist boots and then start to configure itself. As you can see from the logs, it creates new indexes in ES but it always fails after that during the "Filesystem Migration" step; and always with the same error.

What I have tried includes:
* removing the ulimits from the ES compose config
* tried with volumes (default) but also mounting a folder from host **and setting permissions** to ES folder
* switching to official ES image

I also searched to set `allow_partial_search_results` to true as mentionned in the error log; but first i didn't found how to do that (is it just an env variable) ? And second I don't believe it's the root problem, and if it does work after that, I feel like I would just have hide the problem. 

I don't know what else I could try ? I suppose the message is because the Tubearchivist failed to properly setup ES but I'm not even sure of that and don't know of to further test this hypothese.

**After futher reading the contribution guide I found the discord; I'll go ask there and update this post with infos**

### Relevant log output

```Shell
media@VIZBAB:/tmp/test$ docker compose logs -f tubearchivist
tubearchivist  | Operations to perform:
tubearchivist  |   Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
tubearchivist  | Running migrations:
tubearchivist  |   Applying contenttypes.0001_initial... OK
tubearchivist  |   Applying contenttypes.0002_remove_content_type_name... OK
tubearchivist  |   Applying auth.0001_initial... OK
tubearchivist  |   Applying auth.0002_alter_permission_name_max_length... OK
tubearchivist  |   Applying auth.0003_alter_user_email_max_length... OK
tubearchivist  |   Applying auth.0004_alter_user_username_opts... OK
tubearchivist  |   Applying auth.0005_alter_user_last_login_null... OK
tubearchivist  |   Applying auth.0006_require_contenttypes_0002... OK
tubearchivist  |   Applying auth.0007_alter_validators_add_error_messages... OK
tubearchivist  |   Applying auth.0008_alter_user_username_max_length... OK
tubearchivist  |   Applying auth.0009_alter_user_last_name_max_length... OK
tubearchivist  |   Applying auth.0010_alter_group_name_max_length... OK
tubearchivist  |   Applying auth.0011_update_proxy_permissions... OK
tubearchivist  |   Applying auth.0012_alter_user_first_name_max_length... OK
tubearchivist  |   Applying home.0001_initial... OK
tubearchivist  |   Applying admin.0001_initial... OK
tubearchivist  |   Applying admin.0002_logentry_remove_auto_add... OK
tubearchivist  |   Applying admin.0003_logentry_add_action_flag_choices... OK
tubearchivist  |   Applying authtoken.0001_initial... OK
tubearchivist  |   Applying authtoken.0002_auto_20160226_1747... OK
tubearchivist  |   Applying authtoken.0003_tokenproxy... OK
tubearchivist  |   Applying sessions.0001_initial... OK
tubearchivist  | 
tubearchivist  | 230 static files copied to '/app/staticfiles', 974 post-processed.
tubearchivist  | 
tubearchivist  | LOGO REMOVED FOR CLARITY IN ISSUE
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Environment Setup  #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] checking expected env vars
tubearchivist  |     ✓ all expected env vars are set
tubearchivist  | [2] check ES user overwrite
tubearchivist  |     ✓ ES user is set to elastic
tubearchivist  | [3] check TA_PORT overwrite
tubearchivist  |     TA_PORT is not set
tubearchivist  | [4] check TA_UWSGI_PORT overwrite
tubearchivist  |     TA_UWSGI_PORT is not set
tubearchivist  | [5] check ENABLE_CAST overwrite
tubearchivist  |     ENABLE_CAST is not set
tubearchivist  | [6] create superuser
tubearchivist  |     ✓ new superuser with name tubearchivist created
tubearchivist  | 
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Connection check   #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] connect to Redis
tubearchivist  |     ✓ Redis connection verified
tubearchivist  | [2] set Redis config
tubearchivist  |     ✓ Redis config set
tubearchivist  | [3] connect to Elastic Search
tubearchivist  |     ... waiting for ES [0/24]
tubearchivist  |     ✓ ES connection established
tubearchivist  | [4] Elastic Search version check
tubearchivist  |     ✓ ES version check passed
tubearchivist  | [5] check ES path.repo env var
tubearchivist  |     ✓ path.repo env var is set
tubearchivist  | 
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Application Start  #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] set new config.json values
tubearchivist  |     ✓ new config values set
tubearchivist  | [2] create expected cache folders
tubearchivist  |     ✓ expected folders created
tubearchivist  | [3] clear leftover keys in redis
tubearchivist  |     no keys found
tubearchivist  | [4] clear task leftovers
tubearchivist  | [5] clear leftover files from dl cache
tubearchivist  | clear download cache
tubearchivist  |     no files found
tubearchivist  | [6] check for first run after update
tubearchivist  |     no new update found
tubearchivist  | [MIGRATION] validate index mappings
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_config]","resource.type":"index_or_alias","resource.id":"ta_config","index_uuid":"_na_","index":"ta_config"}],"type":"index_not_found_exception","reason":"no such index [ta_config]","resource.type":"index_or_alias","resource.id":"ta_config","index_uuid":"_na_","index":"ta_config"},"status":404}
tubearchivist  | create new blank index with name ta_config...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"}],"type":"index_not_found_exception","reason":"no such index [ta_channel]","resource.type":"index_or_alias","resource.id":"ta_channel","index_uuid":"_na_","index":"ta_channel"},"status":404}
tubearchivist  | create new blank index with name ta_channel...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"}],"type":"index_not_found_exception","reason":"no such index [ta_video]","resource.type":"index_or_alias","resource.id":"ta_video","index_uuid":"_na_","index":"ta_video"},"status":404}
tubearchivist  | create new blank index with name ta_video...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"}],"type":"index_not_found_exception","reason":"no such index [ta_download]","resource.type":"index_or_alias","resource.id":"ta_download","index_uuid":"_na_","index":"ta_download"},"status":404}
tubearchivist  | create new blank index with name ta_download...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"}],"type":"index_not_found_exception","reason":"no such index [ta_playlist]","resource.type":"index_or_alias","resource.id":"ta_playlist","index_uuid":"_na_","index":"ta_playlist"},"status":404}
tubearchivist  | create new blank index with name ta_playlist...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"}],"type":"index_not_found_exception","reason":"no such index [ta_subtitle]","resource.type":"index_or_alias","resource.id":"ta_subtitle","index_uuid":"_na_","index":"ta_subtitle"},"status":404}
tubearchivist  | create new blank index with name ta_subtitle...
tubearchivist  | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"}],"type":"index_not_found_exception","reason":"no such index [ta_comment]","resource.type":"index_or_alias","resource.id":"ta_comment","index_uuid":"_na_","index":"ta_comment"},"status":404}
tubearchivist  | create new blank index with name ta_comment...
tubearchivist  | [MIGRATION] setup snapshots
tubearchivist  | snapshot: run setup
tubearchivist  | {"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[ta_snapshot] missing"}],"type":"repository_missing_exception","reason":"[ta_snapshot] missing"},"status":404}
tubearchivist  | snapshot: setup repo ta_snapshot config {'compress': 'true', 'chunk_size': '1g', 'location': '/usr/share/elasticsearch/data/snapshot'}
tubearchivist  | snapshot: repo setup correctly: {'acknowledged': True}
tubearchivist  | {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [ta_daily] not found, no policies are configured"},"status":404}
tubearchivist  | snapshot: create policy ta_daily {'schedule': '0 0 17 * * ?', 'name': '<ta_daily_>', 'repository': 'ta_snapshot', 'config': {'indices': ['ta_config', 'ta_channel', 'ta_video', 'ta_download', 'ta_playlist', 'ta_subtitle', 'ta_comment'], 'ignore_unavailable': True, 'include_global_state': True}, 'retention': {'expire_after': '30d', 'min_count': 5, 'max_count': 50}}
tubearchivist  | snapshot: policy setup correctly: {'acknowledged': True}
tubearchivist  | snapshots: no snapshots found
tubearchivist  | snapshot: create initial snapshot
tubearchivist  | snapshot: executing now: {'snapshot_name': 'ta_daily_-yzsqlzz8qdg-wlp590uo8w'}
tubearchivist  | [MIGRATION] move user configuration to ES
tubearchivist  |     no users needed migrating to ES
tubearchivist  | 
tubearchivist  | 
tubearchivist  | ########################
tubearchivist  | # Filesystem Migration #
tubearchivist  | ########################
tubearchivist  | 
tubearchivist  | {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"indices:data/read/open_point_in_time","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[ta_video][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"indices:data/read/open_point_in_time","grouped":true,"failed_shards":[]}},"status":503}
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/app/manage.py", line 23, in <module>
tubearchivist  |     main()
tubearchivist  |   File "/app/manage.py", line 19, in main
tubearchivist  |     execute_from_command_line(sys.argv)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
tubearchivist  |     utility.execute()
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
tubearchivist  |     self.fetch_command(subcommand).run_from_argv(self.argv)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
tubearchivist  |     self.execute(*args, **cmd_options)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
tubearchivist  |     output = self.handle(*args, **options)
tubearchivist  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/app/config/management/commands/ta_migpath.py", line 31, in handle
tubearchivist  |     to_migrate = handler.get_to_migrate()
tubearchivist  |                  ^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/app/config/management/commands/ta_migpath.py", line 80, in get_to_migrate
tubearchivist  |     response = IndexPaginate("ta_video", data).get_results()
tubearchivist  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/app/home/src/es/connect.py", line 162, in get_results
tubearchivist  |     self.get_pit()
tubearchivist  |   File "/app/home/src/es/connect.py", line 172, in get_pit
tubearchivist  |     self.pit_id = response["id"]
tubearchivist  |                   ~~~~~~~~^^^^^^
tubearchivist  | KeyError: 'id'
tubearchivist exited with code 0
```

**Comment by lamusmaser** [comment]
This is caused by an issue with ES. I believe you have indicated that this is a new installation/ does not have information in it. Can you confirm this and we can go from there?

**Comment by BancarelValentin** [comment]
Yes indeed it's a fresh install.

**Comment by lamusmaser** [comment]
Stop all the containers. 
Clear out the local ES directory on your FS.
Restart the containers. 

That should see it as a new install and not die during setup.

**Comment by BancarelValentin** [comment]
I did that in between all my tests. Everytime I have the same issue.

**Comment by lamusmaser** [comment]
Can you provide a copy of your compose file?

**Comment by BancarelValentin** [comment]
Its literally the one from the readme

**Comment by BancarelValentin** [comment]
Yes, the only commands I run are in the original issue.
I create a dir in /tmp (it has 777 permissions). Create a compose file,. Paste the one from the Readme into it. Anr run the up command.

Envoyé depuis ProtonMail mobile

-------- Original Message --------

**Comment by lamusmaser** [comment]
Can I confirm how you are clearing out the ES directory? Please provide the relevant commands you use so I can confirm that they are doing the job correctly.

**Comment by BancarelValentin** [comment]
When I was using bind mount to /appdata/data/es, I cleared it with the following.
rm - rf /appdata/data/es/*

Now that I use the original compose with volumes i do this. It's prefixed with test_ because docker gave it that name because I'm in project test
Docker volume rm test_elastic

In the last command I'm not sure about the name because I'm on my phone right now. But im doing a volume ls command before to get the correct name.

Envoyé depuis ProtonMail mobile

-------- Original Message --------

**Comment by BancarelValentin** [comment]
After that last answer, I had a doubt about deleting all volumes, I did so many tests that maybe the order of things I did was not clear in my head. I reclean everything and started from a new directory. 

It seems to work... At least I have more logs than before and without the error I always had. So I'll keep the investigation for now. You can drop this subject temporarily.

I'll update this ticket with my results

**Comment by BancarelValentin** [comment]
It was indeed mistakes from my part during cleaning between tests. I also came across problems with traefik because of the custom healthcheck, but I removed that from the compose file and t works great. I asked the dev on github if there is any side effects to that; I'll update this with answer.
