### ISSUE TITLE
[Installation]: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)

### ISSUE THREAD

**Issue by hhharsha36** [tubearchivist/tubearchivist#683]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Synology

### Your installation or setup question

Hi,

I am trying to setup and install TubeArchivist on mu Synology DS1621+ unit. However, I getting the below error from `kombu` dering `Celery` initialisation.

```
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```

Below are the containerised application versions I am using:

- TubeArchivist -> 0.4.6
- redis-stack-server -> 7.2.0-v9
- Elasticsearch -> 8.12.2 (Official Image)

Below are the contents of my `docker-compose` file

```yaml
version: '3.5'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - .//YouTube:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://host.docker.internal:32160 
      - ES_SNAPSHOT_DIR=/usr/share/elasticsearch/data/snapshot
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=<PASSWORD>
      - REDIS_HOST=redis-stack
      - HOST_UID=1026
      - HOST_GID=100
      - TA_HOST=https://tubearchivist.example.com http:/192.168.1.1
      - TA_USERNAME=user
      - TA_PASSWORD=<PASSWORD> 
      - TZ=Pacific/Auckland
      - DJANGO_DEBUG=True
    labels:
      - "diun.enable=true"
      - "diun.notify_on=new;update"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  web:
    external: true
```

I am pretty sure that the error is related to redis or (celery and kombu). Would appreciate if you can help me out with this issue.

Additionally, the web app loads on my browser and I am able to log in. But, when I enter a Youtube URL and hit download, nothing happens :(

### Relevant log output

```Shell
tubearchivist  | Operations to perform:
tubearchivist  |   Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
tubearchivist  | Running migrations:
tubearchivist  |   No migrations to apply.
tubearchivist  | 
tubearchivist  | 
tubearchivist  |                          ....  .....
tubearchivist  |                   ...'',;:cc,. .;::;;,'...
tubearchivist  |                ..,;:cccllclc,  .:ccllllcc;,..
tubearchivist  |             ..,:cllcc:;,'.',.  ....'',;ccllc:,..
tubearchivist  |           ..;cllc:,'..                ...,:cccc:'.
tubearchivist  |          .;cccc;..                        ..,:ccc:'.
tubearchivist  |        .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
tubearchivist  |       .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
tubearchivist  |      .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
tubearchivist  |      .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
tubearchivist  |    .......     .xMMMNl           .dWMMXdOMMMO'   ........
tubearchivist  |    .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
tubearchivist  |    .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
tubearchivist  |    .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
tubearchivist  |    .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
tubearchivist  |    .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
tubearchivist  |    .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
tubearchivist  |     .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
tubearchivist  |     .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
tubearchivist  |      .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
tubearchivist  |       .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
tubearchivist  |        .':lcc:'.....      .  ..            ..,;cllc,.
tubearchivist  |          .,cclc,....                     ....;clc;..
tubearchivist  |           ..,:,..,c:'..              ...';:,..,:,.
tubearchivist  |             ....:lcccc:;,'''.....'',;;:clllc,....
tubearchivist  |                .'',;:cllllllccccclllllcc:,'..
tubearchivist  |                    ...'',,;;;;;;;;;,''...
tubearchivist  |                             .....
tubearchivist  | 
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Environment Setup  #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] checking expected env vars
tubearchivist  |     ✓ all expected env vars are set
tubearchivist  | [2] check ES user overwrite
tubearchivist  |     ✓ ES user is set to elastic
tubearchivist  | [3] check TA_PORT overwrite
tubearchivist  |     TA_PORT is not set
tubearchivist  | [4] check TA_UWSGI_PORT overwrite
tubearchivist  |     TA_UWSGI_PORT is not set
tubearchivist  | [5] check ENABLE_CAST overwrite
tubearchivist  |     ENABLE_CAST is not set
tubearchivist  | [6] create superuser
tubearchivist  |     superuser already created
tubearchivist  | 
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Connection check   #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] connect to Redis
tubearchivist  |     ✓ Redis connection verified
tubearchivist  | [2] set Redis config
tubearchivist  |     ✓ Redis config set
tubearchivist  | [3] connect to Elastic Search
tubearchivist  |     ... waiting for ES [0/24]
tubearchivist  |     ✓ ES connection established
tubearchivist  | [4] Elastic Search version check
tubearchivist  |     ✓ ES version check passed
tubearchivist  | [5] check ES path.repo env var
tubearchivist  |     ✓ path.repo env var is set
tubearchivist  | 
tubearchivist  | 
tubearchivist  | #######################
tubearchivist  | #  Application Start  #
tubearchivist  | #######################
tubearchivist  | 
tubearchivist  | [1] set new config.json values
tubearchivist  |     ✓ new config values set
tubearchivist  | [2] create expected cache folders
tubearchivist  |     ✓ expected folders created
tubearchivist  | [3] clear leftover keys in redis
tubearchivist  |     no keys found
tubearchivist  | [4] clear task leftovers
tubearchivist  | [5] clear leftover files from dl cache
tubearchivist  | clear download cache
tubearchivist  |     no files found
tubearchivist  | [6] check for first run after update
tubearchivist  |     no new update found
tubearchivist  | [MIGRATION] validate index mappings
tubearchivist  | ta_config index is created and up to date...
tubearchivist  | ta_channel index is created and up to date...
tubearchivist  | ta_video index is created and up to date...
tubearchivist  | ta_download index is created and up to date...
tubearchivist  | ta_playlist index is created and up to date...
tubearchivist  | ta_subtitle index is created and up to date...
tubearchivist  | ta_comment index is created and up to date...
tubearchivist  | [MIGRATION] setup snapshots
tubearchivist  | snapshot: run setup
tubearchivist  | snapshot: repo ta_snapshot already created
tubearchivist  | snapshot: policy is set.
tubearchivist  | snapshot: last snapshot is up-to-date
tubearchivist  | [MIGRATION] move user configuration to ES
tubearchivist  |     no users needed migrating to ES
tubearchivist  | 
tubearchivist  | 
tubearchivist  | ########################
tubearchivist  | # Filesystem Migration #
tubearchivist  | ########################
tubearchivist  | 
tubearchivist  |     no channel migration needed
tubearchivist  | [uWSGI] getting INI configuration from uwsgi.ini
tubearchivist  | *** Starting uWSGI 2.0.23 (64bit) on [Sat Mar 16 06:00:44 2024] ***
tubearchivist  | compiled with version: 10.2.1 20210110 on 27 January 2024 04:04:41
tubearchivist  | os: Linux-4.4.302+ #69057 SMP Fri Jan 12 17:02:27 CST 2024
tubearchivist  | nodename: 858ca087610a
tubearchivist  | machine: x86_64
tubearchivist  | clock source: unix
tubearchivist  | detected number of CPU cores: 8
tubearchivist  | current working directory: /app
tubearchivist  | writing pidfile to /tmp/project-master.pid
tubearchivist  | detected binary path: /root/.local/bin/uwsgi
tubearchivist  | !!! no internal routing support, rebuild with pcre support !!!
tubearchivist  | uWSGI running as root, you can use --uid/--gid/--chroot options
tubearchivist  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tubearchivist  | your memory page size is 4096 bytes
tubearchivist  | detected max file descriptor number: 1048576
tubearchivist  | lock engine: pthread robust mutexes
tubearchivist  | thunder lock: disabled (you can enable it with --thunder-lock)
tubearchivist  | uwsgi socket 0 bound to TCP address :8080 fd 3
tubearchivist  | uWSGI running as root, you can use --uid/--gid/--chroot options
tubearchivist  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tubearchivist  | Python version: 3.11.3 (main, May 23 2023, 13:34:03) [GCC 10.2.1 20210110]
tubearchivist  | *** Python threads support is disabled. You can enable it with --enable-threads ***
tubearchivist  | Python main interpreter initialized at 0x7fa6c925b558
tubearchivist  | uWSGI running as root, you can use --uid/--gid/--chroot options
tubearchivist  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tubearchivist  | your server socket listen backlog is limited to 100 connections
tubearchivist  | your mercy for graceful operations on workers is 60 seconds
tubearchivist  | mapped 154032 bytes (150 KB) for 1 cores
tubearchivist  | *** Operational MODE: single process ***
tubearchivist  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fa6c925b558 pid: 25 (default app)
tubearchivist  | uWSGI running as root, you can use --uid/--gid/--chroot options
tubearchivist  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
tubearchivist  | *** uWSGI is running in multiple interpreter mode ***
tubearchivist  | spawned uWSGI master process (pid: 25)
tubearchivist  | spawned uWSGI worker 1 (pid: 41, cores: 1)
tubearchivist  | celery beat v5.3.6 (emerald-rush) is starting.
tubearchivist  | /root/.local/lib/python3.11/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
tubearchivist  | absolutely not recommended!
tubearchivist  | 
tubearchivist  | Please specify a different user using the --uid option.
tubearchivist  | 
tubearchivist  | User information: uid=0 euid=0 gid=0 egid=0
tubearchivist  | 
tubearchivist  |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
tubearchivist  | __    -    ... __   -        _
tubearchivist  | LocalTime -> 2024-03-16 06:00:45
tubearchivist  | Configuration ->
tubearchivist  |     . broker -> redis://redis-stack:6379//
tubearchivist  |     . loader -> celery.loaders.app.AppLoader
tubearchivist  |     . scheduler -> celery.beat.PersistentScheduler
tubearchivist  |     . db -> /celerybeat-schedule
tubearchivist  |     . logfile -> [stderr]@%INFO
tubearchivist  |     . maxinterval -> 5.00 minutes (300s)
tubearchivist  | [2024-03-16 06:00:45,841: INFO/MainProcess] beat: Starting...
tubearchivist  |  
tubearchivist  |  -------------- celery@858ca087610a v5.3.6 (emerald-rush)
tubearchivist  | --- ***** ----- 
tubearchivist  | -- ******* ---- Linux-4.4.302+-x86_64-with-glibc2.31 2024-03-16 06:00:45
tubearchivist  | - *** --- * --- 
tubearchivist  | - ** ---------- [config]
tubearchivist  | - ** ---------- .> app:         tasks:0x7f4e391492d0
tubearchivist  | - ** ---------- .> transport:   redis://redis-stack:6379//
tubearchivist  | - ** ---------- .> results:     redis://redis-stack:6379/
tubearchivist  | - *** --- * --- .> concurrency: 8 (prefork)
tubearchivist  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
tubearchivist  | --- ***** ----- 
tubearchivist  |  -------------- [queues]
tubearchivist  |                 .> celery           exchange=celery(direct) key=celery
tubearchivist  |                 
tubearchivist  | 
tubearchivist  | [tasks]
tubearchivist  |   . check_reindex
tubearchivist  |   . download_pending
tubearchivist  |   . extract_download
tubearchivist  |   . index_playlists
tubearchivist  |   . manual_import
tubearchivist  |   . rescan_filesystem
tubearchivist  |   . restore_backup
tubearchivist  |   . resync_thumbs
tubearchivist  |   . run_backup
tubearchivist  |   . subscribe_to
tubearchivist  |   . thumbnail_check
tubearchivist  |   . update_subscribed
tubearchivist  |   . version_check
tubearchivist  | 
tubearchivist  | [2024-03-16 06:00:46,449: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
tubearchivist  | whether broker connection retries are made during startup in Celery 6.0 and above.
tubearchivist  | If you wish to retain the existing behavior for retrying connections on startup,
tubearchivist  | you should set broker_connection_retry_on_startup to True.
tubearchivist  |   warnings.warn(
tubearchivist  | 
tubearchivist  | [2024-03-16 06:00:46,455: INFO/MainProcess] Connected to redis://redis-stack:6379//
tubearchivist  | [2024-03-16 06:00:46,457: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
tubearchivist  | whether broker connection retries are made during startup in Celery 6.0 and above.
tubearchivist  | If you wish to retain the existing behavior for retrying connections on startup,
tubearchivist  | you should set broker_connection_retry_on_startup to True.
tubearchivist  |   warnings.warn(
tubearchivist  | 
tubearchivist  | [2024-03-16 06:00:46,459: INFO/MainProcess] mingle: searching for neighbors
tubearchivist  | [2024-03-16 06:00:46,473: CRITICAL/MainProcess] Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
tubearchivist  |     self.blueprint.start(self)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
tubearchivist  |     step.start(parent)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
tubearchivist  |     return self.obj.start()
tubearchivist  |            ^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
tubearchivist  |     blueprint.start(self)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
tubearchivist  |     step.start(parent)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 37, in start
tubearchivist  |     self.sync(c)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
tubearchivist  |     replies = self.send_hello(c)
tubearchivist  |               ^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
tubearchivist  |     replies = inspect.hello(c.hostname, our_revoked._data) or {}
tubearchivist  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 389, in hello
tubearchivist  |     return self._request('hello', from_node=from_node, revoked=revoked)
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 106, in _request
tubearchivist  |     return self._prepare(self.app.control.broadcast(
tubearchivist  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 776, in broadcast
tubearchivist  |     return self.mailbox(conn)._broadcast(
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/pidbox.py", line 346, in _broadcast
tubearchivist  |     return self._collect(reply_ticket, limit=limit,
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/pidbox.py", line 388, in _collect
tubearchivist  |     self.connection.drain_events(timeout=timeout)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/connection.py", line 341, in drain_events
tubearchivist  |     return self.transport.drain_events(self.connection, **kwargs)
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
tubearchivist  |     get(self._deliver, timeout=timeout)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 591, in get
tubearchivist  |     ret = self.handle_event(fileno, event)
tubearchivist  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 573, in handle_event
tubearchivist  |     return self.on_readable(fileno), self
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 569, in on_readable
tubearchivist  |     chan.handlers[type]()
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 974, in _brpop_read
tubearchivist  |     self.connection._deliver(loads(bytes_to_str(item)), dest)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
tubearchivist  |     callback(message)
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
tubearchivist  |     return callback(message)
tubearchivist  |            ^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
tubearchivist  |     decoded = None if on_m else message.decode()
tubearchivist  |                                 ^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
tubearchivist  |     self._decoded_cache = self._decode()
tubearchivist  |                           ^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
tubearchivist  |     return loads(self.body, self.content_type,
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
tubearchivist  |     raise self._for_untrusted_content(content_type, 'untrusted')
tubearchivist  | kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```

**Comment by lamusmaser** [comment]
Is this a shared Redis instance?

**Comment by hhharsha36** [comment]
@lamusmaser yes, the redis instance is shared amount other dockerised applications.

Sorry, I entered wrong value while masking.

**Comment by lamusmaser** [comment]
This is probably causing the issues, as we note in our documentation here: https://docs.tubearchivist.com/installation/docker-compose/#redis

We have this in a bit more detail on one of our [Discord support threads](https://discord.com/channels/920056098122248193/1199775789219053639). Basically, if one of the other services is also using Celery, then they will conflict with each other while they are making calls to Redis, causing some amount of overwriting. The easiest solution is to split off a new Redis instance for TubeArchivist.

**Comment by hhharsha36** [comment]
@lamusmaser first off, I would like to apologise as I completely missed the `#redis` section in documentation and was not able to find similar issue on Github.

I created a dedicated Redis instance for TubeArchivist and everything works like a charm.

Thanks for this awesome project, I am closing this issue.
