### ISSUE TITLE
[Bug]: Playlist Metadata extraction failed

### ISSUE THREAD

**Issue by CommanderRedYT** [tubearchivist/tubearchivist#688]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
I am not able to download any playlists

## Steps To Reproduce
1. Open Tubearchivist
2. Insert playlist link
3. Click on download playlist

## Expected behavior
Playlist should be downloading

### Relevant log output

```shell
2024-03-21 14:28:49,801: INFO/MainProcess] Task extract_download[7d8e977e-a900-4f32-9dba-dee80a614ded] received
[2024-03-21 14:28:49,803: WARNING/ForkPoolWorker-4] extract_download create callback
[2024-03-21 14:28:50,703: WARNING/ForkPoolWorker-4] PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: get metadata from es
[2024-03-21 14:28:50,707: WARNING/ForkPoolWorker-4] {"_index":"ta_playlist","_id":"PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T","found":false}
[2024-03-21 14:28:50,707: WARNING/ForkPoolWorker-4] PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: get metadata from youtube
[2024-03-21 14:28:51,312: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2024-03-21 14:28:51,313: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2024-03-21 14:28:51,551: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2024-03-21 14:28:51,552: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2024-03-21 14:28:51,781: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2024-03-21 14:28:51,781: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2024-03-21 14:28:52,015: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2024-03-21 14:28:52,016: WARNING/ForkPoolWorker-4] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2024-03-21 14:28:52,018: WARNING/ForkPoolWorker-4] ERROR: [youtube:tab] PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2024-03-21 14:28:52,019: WARNING/ForkPoolWorker-4] https://www.youtube.com/playlist?list=PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: failed to get info from youtube with message ERROR: [youtube:tab] PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2024-03-21 14:28:52,019: WARNING/ForkPoolWorker-4] PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: failed to extract metadata
[2024-03-21 14:28:52,022: WARNING/ForkPoolWorker-4] 7d8e977e-a900-4f32-9dba-dee80a614ded Failed callback
[2024-03-21 14:28:52,025: ERROR/ForkPoolWorker-4] Task extract_download[7d8e977e-a900-4f32-9dba-dee80a614ded] raised unexpected: ValueError('PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: failed to extract metadata')
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 226, in extrac_dl
    pending_handler.parse_url_list()
  File "/app/home/src/download/queue.py", line 181, in parse_url_list
    self._process_entry(entry)
  File "/app/home/src/download/queue.py", line 198, in _process_entry
    self._parse_playlist(entry["url"])
  File "/app/home/src/download/queue.py", line 234, in _parse_playlist
    raise ValueError(message)
ValueError: PL845lQkWyS9JQRYTfFzhQSh1LbV75t20T: failed to extract metadata
[2024-03-21 14:28:52,042: WARNING/ForkPoolWorker-4] 7d8e977e-a900-4f32-9dba-dee80a614ded return callback
```

### Anything else?

I have cookie sync turned on and am able to download these playlists with a local yt-dlp installation on my laptop.

**Comment by lamusmaser** [comment]
Related, in some part, to #686.

**Comment by RafaelSchridi** [comment]
For some reason if you toggle "sync cookies" setting in the extension it allows me to add playlists sometimes?

**Comment by CommanderRedYT** [comment]
I disabled the youtube cookie and now everything works....

**Comment by bbilly1** [comment]
This isn't broken, you are getting blocked by YT. The FAQ has some more workarounds you can test.

**Comment by RafaelSchridi** [comment]
I got this error before I downloaded anything at all.

**Comment by ewoks** [comment]
> FAQ

for future reference: `Solutions` section [here](https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled) what might help
