### ISSUE TITLE
[Bug]: Tubearchivist has stop downloading and detecting new videos few days ago without any errors in the logs

### ISSUE THREAD

**Issue by Froggy232** [tubearchivist/tubearchivist#704]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Fedora Silverblue 40 + Podman

## Describe the bug
Hi,
Since few days ago, tubearchivist has stopped downloading and detecting new videos without showing any errors in the logs.
## Steps To Reproduce
Simply using the app as usual.

## Expected behavior
Tubearchivist should detect and download new videos.

### Relevant log output

```shell
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, home, sessions
Running migrations:
  No migrations to apply.

239 static files copied to '/app/staticfiles', 1013 post-processed.


                         ....  .....
                  ...'',;:cc,. .;::;;,'...
               ..,;:cccllclc,  .:ccllllcc;,..
            ..,:cllcc:;,'.',.  ....'',;ccllc:,..
          ..;cllc:,'..                ...,:cccc:'.
         .;cccc;..                        ..,:ccc:'.
       .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
      .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
     .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
     .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
   .......     .xMMMNl           .dWMMXdOMMMO'   ........
   .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
   .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
   .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
   .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
   .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
   .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
    .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
    .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
     .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
      .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
       .':lcc:'.....      .  ..            ..,;cllc,.
         .,cclc,....                     ....;clc;..
          ..,:,..,c:'..              ...';:,..,:,.
            ....:lcccc:;,'''.....'',;;:clllc,....
               .'',;:cllllllccccclllllcc:,'..
                   ...'',,;;;;;;;;;,''...
                            .....


#######################
#  Environment Setup  #
#######################

[1] checking expected env vars
    ✓ all expected env vars are set
[2] check ES user overwrite
    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
    TA_PORT is not set
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    superuser already created


#######################
#  Connection check   #
#######################

[1] connect to Redis
    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
    ✓ ES connection established
[4] Elastic Search version check
    ✓ ES version check passed
[5] check ES path.repo env var
    ✓ path.repo env var is set


#######################
#  Application Start  #
#######################

[1] set new config.json values
    ✓ new config values set
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover keys in redis
    no keys found
[4] clear task leftovers
[5] clear leftover files from dl cache
clear download cache
    no files found
[6] check for first run after update
    no new update found
[MIGRATION] validate index mappings
ta_config index is created and up to date...
ta_channel index is created and up to date...
ta_video index is created and up to date...
ta_download index is created and up to date...
ta_playlist index is created and up to date...
ta_subtitle index is created and up to date...
ta_comment index is created and up to date...
[MIGRATION] setup snapshots
snapshot: run setup
snapshot: repo ta_snapshot already created
snapshot: policy is set.
snapshot: last snapshot is up-to-date
[MIGRATION] move user configuration to ES
    ✓ Settings for user '1' migrated to ES
    ✓ Settings for all users migrated to ES
[MIGRATION] custom playlist
    no playlist_type needed updating in ta_playlist
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.24 (64bit) on [Sun Apr 28 17:26:17 2024] ***
compiled with version: 10.2.1 20210110 on 10 April 2024 18:49:58
os: Linux-6.8.7-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:21:08 UTC 2024
nodename: d30cfeea4b7b
machine: x86_64
clock source: unix
detected number of CPU cores: 32
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 256331
your memory page size is 4096 bytes
detected max file descriptor number: 524288
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.11.3 (main, May 23 2023, 13:34:03) [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f9a88449558
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 154032 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
celery beat v5.3.6 (emerald-rush) is starting.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f9a88449558 pid: 22 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22)
spawned uWSGI worker 1 (pid: 62, cores: 1)
__    -    ... __   -        _
LocalTime -> 2024-04-28 17:26:17
Configuration ->
    . broker -> redis://10.44.155.2:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2024-04-28 17:26:17,821: INFO/MainProcess] beat: Starting...
/root/.local/lib/python3.11/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@d30cfeea4b7b v5.3.6 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.8.7-300.fc40.x86_64-x86_64-with-glibc2.31 2024-04-28 17:26:17
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f20c8ba7fd0
- ** ---------- .> transport:   redis://10.44.155.2:6379//
- ** ---------- .> results:     redis://10.44.155.2:6379/
- *** --- * --- .> concurrency: 32 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . check_reindex
  . download_pending
  . extract_download
  . index_playlists
  . manual_import
  . rescan_filesystem
  . restore_backup
  . resync_thumbs
  . run_backup
  . subscribe_to
  . thumbnail_check
  . update_subscribed
  . version_check

[2024-04-28 17:26:18,931: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-04-28 17:26:18,934: INFO/MainProcess] Connected to redis://10.44.155.2:6379//
[2024-04-28 17:26:18,935: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-04-28 17:26:18,937: INFO/MainProcess] mingle: searching for neighbors
[2024-04-28 17:26:18,942: CRITICAL/MainProcess] Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/root/.local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
  File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
              ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/root/.local/lib/python3.11/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 974, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
    callback(message)
  File "/root/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
    return callback(message)
           ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
    decoded = None if on_m else message.decode()
                                ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
    self._decoded_cache = self._decode()
                          ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
    return loads(self.body, self.content_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
[agg][video_stats] took 21 ms to process
[agg][channel_stats] took 1 ms to process
[agg][playlist_stats] took 1 ms to process
[agg][download_queue_stats] took 4 ms to process
[agg][watch_progress] took 13 ms to process
[agg][videos_last_week] took 11 ms to process
[agg][channel_stats] took 5 ms to process
[agg][channel_stats] took 2 ms to process
[agg][channel_stats] took 2 ms to process
[agg][video_stats] took 2 ms to process
[agg][channel_stats] took 0 ms to process
[agg][playlist_stats] took 0 ms to process
[agg][download_queue_stats] took 1 ms to process
[agg][watch_progress] took 1 ms to process
[agg][videos_last_week] took 2 ms to process
[agg][channel_stats] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][channel_stats] took 1 ms to process
User 1 value 'hide_watched' change: True -> False
User 1 value 'hide_watched' change: False -> True
[agg][video_stats] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][playlist_stats] took 0 ms to process
[agg][download_queue_stats] took 1 ms to process
[agg][watch_progress] took 1 ms to process
[agg][videos_last_week] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][channel_stats] took 0 ms to process
[agg][channel_stats] took 1 ms to process
[agg][video_stats] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][playlist_stats] took 0 ms to process
[agg][download_queue_stats] took 0 ms to process
[agg][watch_progress] took 1 ms to process
[agg][videos_last_week] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][channel_stats] took 1 ms to process
[agg][channel_stats] took 0 ms to process
```

### Anything else?

Thanks you a lot for your work!

**Comment by lamusmaser** [comment]
Is your redis instance being used by multiple applications?

**Comment by lamusmaser** [comment]
This looks like the same issue as #683. Please check and confirm.

**Comment by Froggy232** [comment]
Hi,
Thanks for your help!
So, I use a server with multiple redis instance indeed, but every service is in it's own user and I exclusively use podman rootless, so in my understanding there should be isolated from each other, and this redis instance should be used only for TA, but maybe I'm wrong of course.
I will post my `.container` files in an edit very soon, so it will be easier to debug.
Thanks you!

**Comment by Froggy232** [comment]
Hi again,
It seems it was the case, as after changing the port everything works again.
Thanks you!
