### ISSUE TITLE
[Bug]: TypeError bool object is not subscriptable

### ISSUE THREAD

**Issue by gituser823** [tubearchivist/tubearchivist#734]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology in docker

## Describe the bug

When trying to add some non-yoututbe channels I get this errormessage
Seems to be a python issue according to goole.

## Steps To Reproduce
Go to channels and try to add these channels:
https://www.pornhub.com/model/paintstars33
https://watchmdh.to/models/lialucia/

## Expected behavior
It should add the channel

### Relevant log output

```shell
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,638: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,639: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (1/3)...
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,675: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,675: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (2/3)...
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,714: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,714: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (3/3)...
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,753: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,758: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] paintstars33: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,758: WARNING/ForkPoolWorker-2] https://www.youtube.com/channel/paintstars33/about: failed to get info from youtube with message ERROR: [youtube:tab] paintstars33: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,763: WARNING/ForkPoolWorker-2] 36fc6cff-6c49-449b-b06f-61045a85abbf Failed callback
05/21/2024
12:38:37 AM
[2024-05-21 00:38:37,768: ERROR/ForkPoolWorker-2] Task subscribe_to[36fc6cff-6c49-449b-b06f-61045a85abbf] raised unexpected: TypeError("'bool' object is not subscriptable")
05/21/2024
12:38:37 AM
Traceback (most recent call last):
05/21/2024
12:38:37 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
05/21/2024
12:38:37 AM
    R = retval = fun(*args, **kwargs)
05/21/2024
12:38:37 AM
                 ^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:38:37 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
05/21/2024
12:38:37 AM
    return self.run(*args, **kwargs)
05/21/2024
12:38:37 AM
           ^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:38:37 AM
  File "/app/home/tasks.py", line 356, in subscribe_to
05/21/2024
12:38:37 AM
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
05/21/2024
12:38:37 AM
  File "/app/home/src/download/subscriptions.py", line 347, in subscribe
05/21/2024
12:38:37 AM
    self.subscribe_type(item, expected_type=expected_type)
05/21/2024
12:38:37 AM
  File "/app/home/src/download/subscriptions.py", line 374, in subscribe_type
05/21/2024
12:38:37 AM
    self._subscribe(channel_id)
05/21/2024
12:38:37 AM
  File "/app/home/src/download/subscriptions.py", line 378, in _subscribe
05/21/2024
12:38:37 AM
    ChannelSubscription().change_subscribe(
05/21/2024
12:38:37 AM
  File "/app/home/src/download/subscriptions.py", line 144, in change_subscribe
05/21/2024
12:38:37 AM
    channel.build_json()
05/21/2024
12:38:37 AM
  File "/app/home/src/index/channel.py", line 47, in build_json
05/21/2024
12:38:37 AM
    self.process_youtube_meta()
05/21/2024
12:38:37 AM
  File "/app/home/src/index/channel.py", line 55, in process_youtube_meta
05/21/2024
12:38:37 AM
    self.youtube_meta["thumbnails"].reverse()
05/21/2024
12:38:37 AM
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
05/21/2024
12:38:37 AM
TypeError: 'bool' object is not subscriptable

05/21/2024
12:36:02 AM
[2024-05-21 00:36:02,446: INFO/MainProcess] Task subscribe_to[ce1fb6a3-ccef-42de-944e-b508764140c0] received
05/21/2024
12:36:02 AM
[2024-05-21 00:36:02,450: WARNING/ForkPoolWorker-2] subscribe_to create callback
05/21/2024
12:36:04 AM
[2024-05-21 00:36:04,464: WARNING/ForkPoolWorker-2] WARNING: [generic] Falling back on generic information extractor
05/21/2024
12:36:07 AM
[2024-05-21 00:36:07,413: WARNING/ForkPoolWorker-2] WARNING: [generic] Untested major version (8.14.12) in player engine - download may fail.
05/21/2024
12:36:08 AM
[2024-05-21 00:36:08,891: WARNING/ForkPoolWorker-2] 6: get metadata from es
05/21/2024
12:36:08 AM
[2024-05-21 00:36:08,912: WARNING/ForkPoolWorker-2] {"_index":"ta_channel","_id":"6","found":false}
05/21/2024
12:36:08 AM
[2024-05-21 00:36:08,913: WARNING/ForkPoolWorker-2] 6: get metadata from youtube
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,277: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,433: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,544: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,639: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>). Giving up after 3 retries
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,735: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,736: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (1/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,773: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,773: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (2/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,819: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,819: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (3/3)...
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,861: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,919: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] 6: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,920: WARNING/ForkPoolWorker-2] https://www.youtube.com/channel/6/about: failed to get info from youtube with message ERROR: [youtube:tab] 6: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
05/21/2024
12:36:09 AM
[2024-05-21 00:36:09,987: WARNING/ForkPoolWorker-2] ce1fb6a3-ccef-42de-944e-b508764140c0 Failed callback
05/21/2024
12:36:10 AM
[2024-05-21 00:36:09,999: ERROR/ForkPoolWorker-2] Task subscribe_to[ce1fb6a3-ccef-42de-944e-b508764140c0] raised unexpected: TypeError("'bool' object is not subscriptable")
05/21/2024
12:36:10 AM
Traceback (most recent call last):
05/21/2024
12:36:10 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
05/21/2024
12:36:10 AM
    R = retval = fun(*args, **kwargs)
05/21/2024
12:36:10 AM
                 ^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:10 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
05/21/2024
12:36:10 AM
    return self.run(*args, **kwargs)
05/21/2024
12:36:10 AM
           ^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:10 AM
  File "/app/home/tasks.py", line 356, in subscribe_to
05/21/2024
12:36:10 AM
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
05/21/2024
12:36:10 AM
  File "/app/home/src/download/subscriptions.py", line 347, in subscribe
05/21/2024
12:36:10 AM
    self.subscribe_type(item, expected_type=expected_type)
05/21/2024
12:36:10 AM
  File "/app/home/src/download/subscriptions.py", line 374, in subscribe_type
05/21/2024
12:36:10 AM
    self._subscribe(channel_id)
05/21/2024
12:36:10 AM
  File "/app/home/src/download/subscriptions.py", line 378, in _subscribe
05/21/2024
12:36:10 AM
    ChannelSubscription().change_subscribe(
05/21/2024
12:36:10 AM
  File "/app/home/src/download/subscriptions.py", line 144, in change_subscribe
05/21/2024
12:36:10 AM
    channel.build_json()
05/21/2024
12:36:10 AM
  File "/app/home/src/index/channel.py", line 47, in build_json
05/21/2024
12:36:10 AM
    self.process_youtube_meta()
05/21/2024
12:36:10 AM
  File "/app/home/src/index/channel.py", line 55, in process_youtube_meta
05/21/2024
12:36:10 AM
    self.youtube_meta["thumbnails"].reverse()
05/21/2024
12:36:10 AM
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
05/21/2024
12:36:10 AM
TypeError: 'bool' object is not subscriptable
05/21/2024
12:36:10 AM
[2024-05-21 00:36:10,003: WARNING/ForkPoolWorker-2] ce1fb6a3-ccef-42de-944e-b508764140c0 return callback
05/21/2024
12:36:38 AM
https://watchmdh.to/models/lialucia/
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,230: INFO/MainProcess] Task subscribe_to[8f687f71-ab75-4ea2-a32d-8fdd7cc9403c] received
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,233: WARNING/ForkPoolWorker-2] subscribe_to create callback
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,633: WARNING/ForkPoolWorker-2] WARNING: [generic] Falling back on generic information extractor
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,761: WARNING/ForkPoolWorker-2] ERROR: Unsupported URL: https://watchmdh.to/models/lialucia/
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,761: WARNING/ForkPoolWorker-2] https://watchmdh.to/models/lialucia/: failed to get info from youtube with message ERROR: Unsupported URL: https://watchmdh.to/models/lialucia/
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,818: WARNING/ForkPoolWorker-2] 8f687f71-ab75-4ea2-a32d-8fdd7cc9403c Failed callback
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,823: ERROR/ForkPoolWorker-2] Task subscribe_to[8f687f71-ab75-4ea2-a32d-8fdd7cc9403c] raised unexpected: AttributeError("'bool' object has no attribute 'get'")
05/21/2024
12:36:38 AM
Traceback (most recent call last):
05/21/2024
12:36:38 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
05/21/2024
12:36:38 AM
    R = retval = fun(*args, **kwargs)
05/21/2024
12:36:38 AM
                 ^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:38 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
05/21/2024
12:36:38 AM
    return self.run(*args, **kwargs)
05/21/2024
12:36:38 AM
           ^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:38 AM
  File "/app/home/tasks.py", line 356, in subscribe_to
05/21/2024
12:36:38 AM
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
05/21/2024
12:36:38 AM
  File "/app/home/src/download/subscriptions.py", line 340, in subscribe
05/21/2024
12:36:38 AM
    self.to_subscribe = Parser(self.url_str).parse()
05/21/2024
12:36:38 AM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:38 AM
  File "/app/home/src/ta/urlparser.py", line 26, in parse
05/21/2024
12:36:38 AM
    identified = self.process_url(parsed)
05/21/2024
12:36:38 AM
                 ^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:38 AM
  File "/app/home/src/ta/urlparser.py", line 67, in process_url
05/21/2024
12:36:38 AM
    channel_id = self._extract_channel_name(parsed.geturl())
05/21/2024
12:36:38 AM
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:38 AM
  File "/app/home/src/ta/urlparser.py", line 112, in _extract_channel_name
05/21/2024
12:36:38 AM
    channel_id = url_info.get("channel_id", False)
05/21/2024
12:36:38 AM
                 ^^^^^^^^^^^^
05/21/2024
12:36:38 AM
AttributeError: 'bool' object has no attribute 'get'
05/21/2024
12:36:38 AM
[2024-05-21 00:36:38,824: WARNING/ForkPoolWorker-2] 8f687f71-ab75-4ea2-a32d-8fdd7cc9403c return callback
05/21/2024
12:36:55 AM
https://watchmdh.to/models/lialucia/
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,028: INFO/MainProcess] Task subscribe_to[bb8ef84e-9494-4fae-adbe-b07a00bc3e62] received
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,030: WARNING/ForkPoolWorker-2] subscribe_to create callback
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,412: WARNING/ForkPoolWorker-2] WARNING: [generic] Falling back on generic information extractor
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,553: WARNING/ForkPoolWorker-2] ERROR: Unsupported URL: https://watchmdh.to/models/lialucia/
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,553: WARNING/ForkPoolWorker-2] https://watchmdh.to/models/lialucia/: failed to get info from youtube with message ERROR: Unsupported URL: https://watchmdh.to/models/lialucia/
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,558: WARNING/ForkPoolWorker-2] bb8ef84e-9494-4fae-adbe-b07a00bc3e62 Failed callback
05/21/2024
12:36:55 AM
[2024-05-21 00:36:55,564: ERROR/ForkPoolWorker-2] Task subscribe_to[bb8ef84e-9494-4fae-adbe-b07a00bc3e62] raised unexpected: AttributeError("'bool' object has no attribute 'get'")
05/21/2024
12:36:55 AM
Traceback (most recent call last):
05/21/2024
12:36:55 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
05/21/2024
12:36:55 AM
    R = retval = fun(*args, **kwargs)
05/21/2024
12:36:55 AM
                 ^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:55 AM
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
05/21/2024
12:36:55 AM
    return self.run(*args, **kwargs)
05/21/2024
12:36:55 AM
           ^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:55 AM
  File "/app/home/tasks.py", line 356, in subscribe_to
05/21/2024
12:36:55 AM
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
05/21/2024
12:36:55 AM
  File "/app/home/src/download/subscriptions.py", line 340, in subscribe
05/21/2024
12:36:55 AM
    self.to_subscribe = Parser(self.url_str).parse()
05/21/2024
12:36:55 AM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:55 AM
  File "/app/home/src/ta/urlparser.py", line 26, in parse
05/21/2024
12:36:55 AM
    identified = self.process_url(parsed)
05/21/2024
12:36:55 AM
                 ^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:55 AM
  File "/app/home/src/ta/urlparser.py", line 67, in process_url
05/21/2024
12:36:55 AM
    channel_id = self._extract_channel_name(parsed.geturl())
05/21/2024
12:36:55 AM
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/21/2024
12:36:55 AM
  File "/app/home/src/ta/urlparser.py", line 112, in _extract_channel_name
05/21/2024
12:36:55 AM
    channel_id = url_info.get("channel_id", False)
05/21/2024
12:36:55 AM
                 ^^^^^^^^^^^^
05/21/2024
12:36:55 AM
AttributeError: 'bool' object has no attribute 'get'
```

### Anything else?

i was told yt-dlp should be able to handle these non-youtube pages.

**Comment by lamusmaser** [comment]
Non-YouTube videos are out of scope: https://docs.tubearchivist.com/faq/#what-is-the-scope-of-this-project

This is not an expected feature. 

`yt-dlp` itself does handle videos from other sites, but we parse links beforehand to determine if they are youtube videos.
