### ISSUE TITLE
service can't start when update from v0.4.7 to v0.4.8

### ISSUE THREAD

**Issue by xinmans** [tubearchivist/tubearchivist#750]
[MIGRATION] setup snapshots
snapshot: run setup
snapshot: repo ta_snapshot already created
snapshot: policy is set.
snapshot: last snapshot is up-to-date
[MIGRATION] migrate schedule store
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
home.models.CustomPeriodicTask.DoesNotExist: CustomPeriodicTask matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
version: '3.5'
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config/management/commands/ta_startup.py", line 52, in handle
    self._mig_schedule_store()
  File "/app/config/management/commands/ta_startup.py", line 174, in _mig_schedule_store
    self._mig_update_subscribed(current_schedules)
  File "/app/config/management/commands/ta_startup.py", line 189, in _mig_update_subscribed
    self._create_task(task_name, update_subscribed_schedule)
  File "/app/config/management/commands/ta_startup.py", line 255, in _create_task
    task, _ = CustomPeriodicTask.objects.get_or_create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/root/.local/lib/python3.11/site-packages/django_celery_beat/models.py", line 603, in save
    self.validate_unique()
  File "/root/.local/lib/python3.11/site-packages/django_celery_beat/models.py", line 570, in validate_unique
    super().validate_unique(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1290, in validate_unique
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'name': ['Periodic task with this Name already exists.']}

**Comment by bbilly1** [comment]
Probably something else before that failed. Share complete startup logs to paste bin or somewhere.

Easiest would probably be to delete `db.sqlite3` from the cache volume. That will reset things.

**Comment by xinmans** [comment]
> delete db.sqlite3 from the cache volume. 

will delete db.sqlite3 from the cache volume remove the meta data of video and channels？

**Comment by lamusmaser** [comment]
No, it will not remove any of that data.

**Comment by xinmans** [comment]
> Probably something else before that failed. Share complete startup logs to paste bin or somewhere.
> 
> 
> 
> Easiest would probably be to delete `db.sqlite3` from the cache volume. That will reset things.

work fine，thanks

**Comment by xinmans** [comment]
> > Probably something else before that failed. Share complete startup logs to paste bin or somewhere.
> > 
> > 
> > 
> > Easiest would probably be to delete `db.sqlite3` from the cache volume. That will reset things.
> 
> work fine，thanks

will crash while running a while



#######################
#  Application Start  #
#######################

[1] set new config.json values
    no new config values
[2] create expected cache folders
    ✓ expected folders created
[3] clear leftover keys in redis
    no keys found
[4] clear task leftovers
[5] clear leftover files from dl cache
clear download cache
    no files found
[6] check for first run after update
    no new update found
[MIGRATION] validate index mappings
ta_config index is created and up to date...
ta_channel index is created and up to date...
ta_video index is created and up to date...
ta_download index is created and up to date...
ta_playlist index is created and up to date...
ta_subtitle index is created and up to date...
ta_comment index is created and up to date...
[MIGRATION] setup snapshots
snapshot: run setup
snapshot: repo ta_snapshot already created
snapshot: policy is set.
snapshot: last snapshot is up-to-date
[MIGRATION] migrate schedule store
    ✓ new task created: 'update_subscribed: 0 1 * * * (m/h/dM/MY/d) Asia/Shanghai'
    ✓ new task created: 'download_pending: 0 2 * * * (m/h/dM/MY/d) Asia/Shanghai'
    ✓ new task created: 'check_reindex: 0 12 * * * (m/h/dM/MY/d) Asia/Shanghai'
    ✓ new task created: 'thumbnail_check: 0 17 * * * (m/h/dM/MY/d) Asia/Shanghai'
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
home.models.CustomPeriodicTask.DoesNotExist: CustomPeriodicTask matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config/management/commands/ta_startup.py", line 52, in handle
    self._mig_schedule_store()
  File "/app/config/management/commands/ta_startup.py", line 179, in _mig_schedule_store
    self._mig_version_check()
  File "/app/config/management/commands/ta_startup.py", line 246, in _mig_version_check
    self._create_task("version_check", version_check_schedule)
  File "/app/config/management/commands/ta_startup.py", line 255, in _create_task
    task, _ = CustomPeriodicTask.objects.get_or_create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/root/.local/lib/python3.11/site-packages/django_celery_beat/models.py", line 603, in save
    self.validate_unique()
  File "/root/.local/lib/python3.11/site-packages/django_celery_beat/models.py", line 570, in validate_unique
    super().validate_unique(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1290, in validate_unique
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'name': ['Periodic task with this Name already exists.']}

**Comment by bbilly1** [comment]
Take it down again, remove the db.sqlite3 file, and up it again. Then copy the *complete* log, you cut of the migrations section from django that should have happen at the beginning. 

Or are you running a none standard install somehow? Share some details of your setup.

**Comment by bbilly1** [comment]
assuming this has been solved by now.
