### ISSUE TITLE
[Installation]: docker container - python errors

### ISSUE THREAD

**Issue by lockheed** [tubearchivist/tubearchivist#761]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Arch Linux

### Your installation or setup question

I have based my setup on your docker-compose example, and checked the installation guide to make sure I did not miss anything, but my archivist container won't start. It throws out python errors in a loop.

### Relevant log output

```Shell
....  .....
                  ...'',;:cc,. .;::;;,'...
               ..,;:cccllclc,  .:ccllllcc;,..
            ..,:cllcc:;,'.',.  ....'',;ccllc:,..
          ..;cllc:,'..                ...,:cccc:'.
         .;cccc;..                        ..,:ccc:'.
       .ckkkOkxollllllllllllc.      .,:::;.  .,cclc;
      .:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:
     .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.
     .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.
   .......     .xMMMNl           .dWMMXdOMMMO'   ........
   .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.
   .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc'
   .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,
   .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc'
   .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc'
   .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.
    .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.
    .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.
     .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.
      .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.
       .':lcc:'.....      .  ..            ..,;cllc,.
         .,cclc,....                     ....;clc;..
          ..,:,..,c:'..              ...';:,..,:,.
            ....:lcccc:;,'''.....'',;;:clllc,....
               .'',;:cllllllccccclllllcc:,'..
                   ...'',,;;;;;;;;;,''...
                            .....
#######################
#  Environment Setup  #
#######################
[1] checking expected env vars
    ✓ all expected env vars are set
[2] check ES user overwrite
    ✓ ES user is set to elastic
[3] check TA_PORT overwrite
    TA_PORT is not set
[4] check TA_UWSGI_PORT overwrite
    TA_UWSGI_PORT is not set
[5] check ENABLE_CAST overwrite
    ENABLE_CAST is not set
[6] create superuser
    superuser already created
#######################
#  Connection check   #
#######################
[1] connect to Redis
    ✓ Redis connection verified
[2] set Redis config
    ✓ Redis config set
[3] connect to Elastic Search
    ... waiting for ES [0/24]
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config/management/commands/ta_connection.py", line 38, in handle
    self._es_connection_check()
  File "/app/config/management/commands/ta_connection.py", line 82, in _es_connection_check
    _, status_code = ElasticWrap("/").get(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/es/connect.py", line 56, in get
    return response.json(), response.status_code
           ^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bbilly1** [comment]
Your connection to ES isn't working, or ES itself. Share your compose file and ES startup logs.

**Comment by lockheed** [comment]
Here it is: https://pastebin.com/raw/knDQMnCF

**Comment by bbilly1** [comment]
What's with the ES_URL env var https://my.domain.com for the elasticsearch container? Do you resolve that somehow?

**Comment by lockheed** [comment]
> What's with the ES_URL env var https://my.domain.com for the elasticsearch container? Do you resolve that somehow?

Yes, good catch. I changed it to ES_URL=http://archivist-es:9200 and it started fine.

But now when I go to archivist's url, i get 
**Bad Request (400)**



> Having a `#` in your mount location may also cause problems later on, too.

Valid point, I never thought of that, but I've been using it for years in many docker-compose files without any issues

**Comment by bbilly1** [comment]
Please read the docs before posting here. That's usually TA_HOST related.

**Comment by lockheed** [comment]
All I can see in the doc is TA_HOST - Server IP or hostname.

It is a docker container behind a reverse proxy, so I don't think I should put in container's IP, and there's no hostname(unless it's the name of the container). Should it be the external URL from reverse proxy?

**Comment by bbilly1** [comment]
Copy pasted from the docs: 

Set the environment variable TA_HOST to match with the expected ways you will access your Tube Archivist instance.

This can be a domain like example.com, a subdomain like ta.example.com or an IP address like 192.168.1.20.

If you are running Tube Archivist behind a SSL reverse proxy, specify the protocol (https://).

You can add multiple hostnames separated with a space.

Any wrong configurations here will result in a Bad Request (400) response.

**Comment by lockheed** [comment]
Ah, then I've been reading wrong documentation. Thanks, that solved it.
