### ISSUE TITLE
[Bug]: rescan filesystem fails when a deleted video is encountered

### ISSUE THREAD

**Issue by erentar** [tubearchivist/tubearchivist#769]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

linux docker

## Describe the bug

reindex filesystem,
filesystem has deleted video
error

### Relevant log output

```shell
tubearchivist    | [2024-07-20 17:00:17,011: WARNING/ForkPoolWorker-8] rescan_filesystem create callback
tubearchivist    | [2024-07-20 17:00:17,081: WARNING/ForkPoolWorker-8] nothing to delete
tubearchivist    | [2024-07-20 17:00:17,088: WARNING/ForkPoolWorker-8] hyI2nUjoF80: get metadata from youtube
tubearchivist    | [2024-07-20 17:00:17,388: WARNING/ForkPoolWorker-8] ERROR: [youtube] hyI2nUjoF80: Video unavailable. This video has been removed by the uploader
tubearchivist    | [2024-07-20 17:00:17,388: WARNING/ForkPoolWorker-8] https://www.youtube.com/watch?v=hyI2nUjoF80: failed to get info from youtube with message ERROR: [youtube] hyI2nUjoF80: Video unavailable. This video has been removed by the uploader
tubearchivist    | [2024-07-20 17:00:17,392: WARNING/ForkPoolWorker-8] 108e905a-860b-4add-b822-0794703bd721 Failed callback
tubearchivist    | [2024-07-20 17:00:17,398: ERROR/ForkPoolWorker-8] Task rescan_filesystem[108e905a-860b-4add-b822-0794703bd721] raised unexpected: ValueError('failed to get metadata for ahy5ejaiD0i')
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
tubearchivist    |     R = retval = fun(*args, **kwargs)
tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
tubearchivist    |     return self.run(*args, **kwargs)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/home/tasks.py", line 264, in rescan_filesystem
tubearchivist    |     handler.apply()
tubearchivist    |   File "/app/home/src/index/filesystem.py", line 58, in apply
tubearchivist    |     self.index()
tubearchivist    |   File "/app/home/src/index/filesystem.py", line 90, in index
tubearchivist    |     index_new_video(youtube_id)
tubearchivist    |   File "/app/home/src/index/video.py", line 400, in index_new_video
tubearchivist    |     raise ValueError("failed to get metadata for " + youtube_id)
tubearchivist    | ValueError: failed to get metadata for ahy5ejaiD0i
tubearchivist    | [2024-07-20 17:00:17,399: WARNING/ForkPoolWorker-8] 108e905a-860b-4add-b822-0794703bd721 return callback
```

**Comment by bbilly1** [comment]
Ah, you are talking about "rescan filesystem", not reindex. That is expected behavior: 

https://docs.tubearchivist.com/settings/actions/#rescan-filesystem

You'll have to deal with these cases outside of the application, as that is not something TA can do.

Also duplicate and more details: #440, #206
