### ISSUE TITLE
[Bug]: Certain channels can't be subscribed

### ISSUE THREAD

**Issue by robertas90poe** [tubearchivist/tubearchivist#772]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 22.04 server

## Tried to subscribe one of my followed channels, but got unexpected error.

error log is attached:

### Relevant log output

```shell
[2024-07-22 09:30:00,641: INFO/MainProcess] Task subscribe_to[730c0cce-0e1a-4797-b22f-3c6e2372611c] received
[2024-07-22 09:30:00,644: WARNING/ForkPoolWorker-11] subscribe_to create callback
[2024-07-22 09:30:01,362: WARNING/ForkPoolWorker-11] UCyXiDU5qjfOPxgOPeFWGwKw: get metadata from es
[2024-07-22 09:30:01,455: WARNING/ForkPoolWorker-11] {"_index":"ta_channel","_id":"UCyXiDU5qjfOPxgOPeFWGwKw","found":false}
[2024-07-22 09:30:01,455: WARNING/ForkPoolWorker-11] UCyXiDU5qjfOPxgOPeFWGwKw: get metadata from youtube
[2024-07-22 09:30:02,812: WARNING/ForkPoolWorker-11] ERROR: [youtube] 73s5sPyBMoE: The following content is not available on this app.. Watch on the latest version of YouTube.
[2024-07-22 09:30:02,812: WARNING/ForkPoolWorker-11] https://www.youtube.com/channel/UCyXiDU5qjfOPxgOPeFWGwKw: failed to get info from youtube with message ERROR: [youtube] 73s5sPyBMoE: The following content is not available on this app.. Watch on the latest version of YouTube.
[2024-07-22 09:30:02,816: WARNING/ForkPoolWorker-11] 730c0cce-0e1a-4797-b22f-3c6e2372611c Failed callback
[2024-07-22 09:30:02,819: ERROR/ForkPoolWorker-11] Task subscribe_to[730c0cce-0e1a-4797-b22f-3c6e2372611c] raised unexpected: TypeError("'bool' object is not subscriptable")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 302, in subscribe_to
    SubscriptionHandler(url_str, task=self).subscribe(expected_type)
  File "/app/home/src/download/subscriptions.py", line 392, in subscribe
    self.subscribe_type(item, expected_type=expected_type)
  File "/app/home/src/download/subscriptions.py", line 421, in subscribe_type
    self._subscribe(channel_id)
  File "/app/home/src/download/subscriptions.py", line 425, in _subscribe
    ChannelSubscription().change_subscribe(
  File "/app/home/src/download/subscriptions.py", line 118, in change_subscribe
    channel.build_json()
  File "/app/home/src/index/channel.py", line 45, in build_json
    self.process_youtube_meta()
  File "/app/home/src/index/channel.py", line 53, in process_youtube_meta
    self.youtube_meta["thumbnails"].reverse()
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by bbilly1** [comment]
> The following content is not available on this app.. Watch on the latest version of YouTube.

You are getting blocked by YT. See our FAQ with some ideas for workarounds.

**Comment by robertas90poe** [comment]
To be fare, it would be useful to get this "_The following content is not available on this app.. Watch on the latest version of YouTube._" on GUI error message instead of "bool can't be susbscribed..."
