### ISSUE TITLE
[Bug]: Cookies become obsolete after roughly 1 hour.

### ISSUE THREAD

**Issue by Nymnz** [tubearchivist/tubearchivist#817]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 24.04 VM via proxmox

## Describe the bug
I am currently manually importing videos to tubearchivist according to method [#2](https://docs.tubearchivist.com/settings/actions/#method-2) on the wiki because I accidentally removed the database. 

I need to import new cookies roughly every hour otherwise videos that have age-verification halt the process. I import them by unchecking and checking the tubearchivist companion app. I am not sure if I have set up something wrong or if it's a new issue on youtubes side. 

Worth to note is that the tubearchivist directories are woroking in a remote NTFS directory which I mounted to my VM with cifs-utils. I believe that NTFS and/or network drives can cause trouble with permissions so if that is suspected please tell me. 

## Steps To Reproduce

1. Import cookies and wait roughly one hour.
2. Try to manually import a age restricted video.

## Expected behavior

For cookies to be valid for longer.

### Relevant log output

```shell
[2024-09-24 18:29:13,639: WARNING/ForkPoolWorker-8] manual import: {'media': '/cache/import/UCR1D15p_vdP3HkrH8wgjQRw[Ffh7cWRrqF4].mp4', 'video_id': 'Ffh7cWRrqF4', 'metadata': False, 'thumb': False, 'subtitle': []}
[2024-09-24 18:29:13,640: WARNING/ForkPoolWorker-8] Ffh7cWRrqF4: get metadata from youtube
[2024-09-24 18:29:14,680: WARNING/ForkPoolWorker-8] WARNING: [youtube] Ffh7cWRrqF4: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = kfDXZSWzS9tJJ-ulf ; player = https://www.youtube.com/s/player/c41f1db5/player_ias.vflset/en_US/base.js
[2024-09-24 18:29:14,683: WARNING/ForkPoolWorker-8] WARNING: [youtube] Ffh7cWRrqF4: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 9mLHzzpk8yyjUeMOr ; player = https://www.youtube.com/s/player/c41f1db5/player_ias.vflset/en_US/base.js
[2024-09-24 18:29:14,686: WARNING/ForkPoolWorker-8] ERROR: [youtube] Ffh7cWRrqF4: Sign in to confirm your age. This video may be inappropriate for some users.
[2024-09-24 18:29:14,686: WARNING/ForkPoolWorker-8] https://www.youtube.com/watch?v=Ffh7cWRrqF4: failed to get info from youtube with message ERROR: [youtube] Ffh7cWRrqF4: Sign in to confirm your age. This video may be inappropriate for some users.
[2024-09-24 18:29:14,686: WARNING/ForkPoolWorker-8] Ffh7cWRrqF4: manual import failed, and no metadata found.
[2024-09-24 18:29:14,688: WARNING/ForkPoolWorker-8] 5798966e-7212-430f-a87a-6911f67d75d7 Failed callback
[2024-09-24 18:29:14,690: ERROR/ForkPoolWorker-8] Task manual_import[5798966e-7212-430f-a87a-6911f67d75d7] raised unexpected: ValueError()
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 218, in run_manual_import
    ImportFolderScanner(task=self).scan()
  File "/app/home/src/index/manual.py", line 56, in scan
    self.process_videos()
  File "/app/home/src/index/manual.py", line 147, in process_videos
    ManualImport(current_video, self.CONFIG).run()
  File "/app/home/src/index/manual.py", line 397, in run
    json_data = self.index_metadata()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/index/manual.py", line 411, in index_metadata
    raise ValueError
ValueError
[2024-09-24 18:29:14,690: WARNING/ForkPoolWorker-8] 5798966e-7212-430f-a87a-6911f67d75d7 return callback
```

Bug is easy to work around but I mainly wanted to post to see if this is a me problem or if it's something more people are experiencing.

**Comment by barrelltitor** [comment]
Having this issue as well for quite some time. I wish the companion app would refresh the cookie at some interval

**Comment by Zulux91** [comment]
I was having the same issue. My solution was to download the extension, modify it and then loading it from my browser as a 3rd party extension. Mind you, you need dev mode turn on if and this modification is for the chrome version.

If you wanna do the same, once you download the extension open the file _script.js_. Look for the _checkVideoExists_ function (should start at line 470) and at the end add `refreshCookie();` just below `sending.then(handleResponse, handleError);` and above the function closing `}`.

So now every time a video is loaded or you hover your mouse over any video the cookie gets refreshed. Might be a bit overkill but solved the issue and since I'm hosting my TA instance locally, it gets done almost instantly. Of course this is a solution if you are frequently active in youtube, which is my case.

**Comment by Dontkickmi22** [comment]
Same here awhile back. Shame I overcome it manually.  I went sync via extension, and remove via setting page every couple minutes. sad

**Comment by Dontkickmi22** [comment]
me? Nope, too much heat to go thru. Me just tagging along post. Sorry, should have done more for the community. orz

Zulux91, probably not either cause he fixed it. ;)

**Comment by bbilly1** [comment]
That is well known, YT deactivates that server side when it detects strange behavior. You'll find various issues on the yt-dlp repo, e.g. here: https://github.com/yt-dlp/yt-dlp/issues/8227

Ultimately not a TA bug, but a yt-dlp/YT limitation.

**Comment by barrelltitor** [comment]
But if the cookie gets invalidated more often shouldn't there be an option to refresh the cookie more often? Since the cookie is invalidated server side I assume we're going to need a new cookie anyway?
