### ISSUE TITLE
[Bug]: Cache directory permissions problem

### ISSUE THREAD

**Issue by kuligs2** [tubearchivist/tubearchivist#825]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

debian-12

## Describe the bug
I want to move my cache folder to my smb share. SMB share is mounted under not-root user, and all permissions are different.
Why is it that the cache folder uses root permissions while youtube folder has the env defined perms?
![image](https://github.com/user-attachments/assets/48c0573b-5763-466a-b494-8ece3745cc29)
```yaml
services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - /home/tubearchivist/tubearchive-data:/youtube
      - /home/tubearchivist/tubearchive-data/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=3000
      - HOST_GID=568
```
### Relevant log output

```shell
tubearchivist    | ta_comment index is created and up to date...
tubearchivist    | [MIGRATION] setup snapshots
tubearchivist    | snapshot: run setup
tubearchivist    | snapshot: repo ta_snapshot already created
tubearchivist    | snapshot: policy is set.
tubearchivist    | snapshot: last snapshot is up-to-date
tubearchivist    | [MIGRATION] migrate schedule store
tubearchivist    |     no schedules to migrate
tubearchivist    | [MIGRATION] custom playlist
tubearchivist    |     no playlist_type needed updating in ta_playlist
tubearchivist    | [7] create initial schedules
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 948, in get_or_create
tubearchivist    |     return self.get(**kwargs), False
tubearchivist    |            ^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
tubearchivist    |     raise self.model.DoesNotExist(
tubearchivist    | django_celery_beat.models.CrontabSchedule.DoesNotExist: CrontabSchedule matching query does not exist.
tubearchivist    |
tubearchivist    | During handling of the above exception, another exception occurred:
tubearchivist    |
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _commit
tubearchivist    |     return self.connection.commit()
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    | sqlite3.OperationalError: database is locked
tubearchivist    |
tubearchivist    | The above exception was the direct cause of the following exception:
tubearchivist    |
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/app/manage.py", line 23, in <module>
tubearchivist    |     main()
tubearchivist    |   File "/app/manage.py", line 19, in main
tubearchivist    |     execute_from_command_line(sys.argv)
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
tubearchivist    |     utility.execute()
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
tubearchivist    |     self.fetch_command(subcommand).run_from_argv(self.argv)
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
tubearchivist    |     self.execute(*args, **cmd_options)
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
tubearchivist    |     output = self.handle(*args, **options)
tubearchivist    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/config/management/commands/ta_startup.py", line 58, in handle
tubearchivist    |     self._create_default_schedules()
tubearchivist    |   File "/app/config/management/commands/ta_startup.py", line 367, in _create_default_schedules
tubearchivist    |     check_reindex = builder.get_set_task(
tubearchivist    |                     ^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/home/src/ta/config_schedule.py", line 68, in get_set_task
tubearchivist    |     task_crontab = self.get_set_cron_tab(schedule)
tubearchivist    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/home/src/ta/config_schedule.py", line 80, in get_set_cron_tab
tubearchivist    |     crontab, _ = CrontabSchedule.objects.get_or_create(**kwargs)
tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
tubearchivist    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 953, in get_or_create
tubearchivist    |     with transaction.atomic(using=self.db):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/transaction.py", line 263, in __exit__
tubearchivist    |     connection.commit()
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
tubearchivist    |     return func(*args, **kwargs)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 323, in commit
tubearchivist    |     self._commit()
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 298, in _commit
tubearchivist    |     with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
tubearchivist    |     raise dj_exc_value.with_traceback(traceback) from exc_value
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _commit
tubearchivist    |     return self.connection.commit()
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    | django.db.utils.OperationalError: database is locked
tubearchivist    | Operations to perform:
tubearchivist    |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, home, sessions
tubearchivist    | Running migrations:
tubearchivist    |   No migrations to apply.
tubearchivist    | Deleting 'progress.e8ac0d1e89f4.js.br'
tubearchivist    | Deleting 'stats.js'
tubearchivist    | Deleting 'stats.f4ccd010452a.js.br'
tubearchivist    | Deleting 'cast-videos.dd0b3153f3a0.js.br'
tubearchivist    | Deleting 'progress.js'
tubearchivist    | Deleting 'stats.js.gz'
tubearchivist    | Deleting 'script.js'
tubearchivist    | Deleting 'cast-videos.js.br'
tubearchivist    | Deleting 'script.js.gz'
```

**Comment by bbilly1** [comment]
What you see is your sqlite db locking up. That is likely to happen, sqlite is really not meant to be used over a network drive like that.

the /youtube folder supports ownership change with `chown`, but originally the file will still be written as the docker user, that is root, then chowned to whatever ID you have specified. 

So all in all, moving the /cache mount to a networked drive is likely not a good idea.

**Comment by kuligs2** [comment]
maybe then add some sort of cache folder info like size of it to the admin page like you did to the youtube folder? What kind of files are stored in cache anyways? how much storage should be allowed for cache?

**Comment by bbilly1** [comment]
The size is totally depended on your archive size. For what is stored there, easy enough to look at it.

**Comment by kuligs2** [comment]
> The size is totally depended on your archive size. For what is stored there, easy enough to look at it.

So if the /youtube is 19GB in size, does that mean /cache is going to be the same size?
