### ISSUE TITLE
[Bug]: Rescan: One unknown ID stops the whole process

### ISSUE THREAD

**Issue by IngwiePhoenix** [tubearchivist/tubearchivist#831]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux (Armbian, aarch64)

## Describe the bug

My old NAS imploded and took with it my TubeArchivist config - at least in part. Everything on the old eMMC is gone, whilst everything else (mainly `/youtube`) remains. Since I have now moved to Kubernetes and written myself a lengthy deployment, I made the old downloads accessible to TA and hoped that clicking "Rescan filesystem" would fix the missing information.

Well... but a single ID stops it, every time.

```
[2024-11-04 05:34:36,789: INFO/MainProcess] Task rescan_filesystem[90faa7e5-2391-4fc4-8a08-fa67c15dff22] received
[2024-11-04 05:34:36,791: WARNING/ForkPoolWorker-8] rescan_filesystem create callback
[2024-11-04 05:34:36,944: WARNING/ForkPoolWorker-8] nothing to delete
[2024-11-04 05:34:36,951: WARNING/ForkPoolWorker-8] Ug9ZGo8ki7E: get metadata from youtube
[2024-11-04 05:34:37,350: WARNING/ForkPoolWorker-8] ERROR: [youtube] Ug9ZGo8ki7E: Video unavailable. This video is no longer available due to a copyright claim by Square Enix Co., Ltd.
[2024-11-04 05:34:37,350: WARNING/ForkPoolWorker-8] https://www.youtube.com/watch?v=Ug9ZGo8ki7E: failed to get info from youtube with message ERROR: [youtube] Ug9ZGo8ki7E: Video unavailable. This video is no longer available due to a copyright claim by Square Enix Co., Ltd.
[2024-11-04 05:34:37,355: WARNING/ForkPoolWorker-8] 90faa7e5-2391-4fc4-8a08-fa67c15dff22 Failed callback
[2024-11-04 05:34:37,359: ERROR/ForkPoolWorker-8] Task rescan_filesystem[90faa7e5-2391-4fc4-8a08-fa67c15dff22] raised unexpected: ValueError('failed to get metadata for Ug9ZGo8ki7E')
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 264, in rescan_filesystem
    handler.apply()
  File "/app/home/src/index/filesystem.py", line 58, in apply
    self.index()
  File "/app/home/src/index/filesystem.py", line 90, in index
    index_new_video(youtube_id)
  File "/app/home/src/index/video.py", line 400, in index_new_video
    raise ValueError("failed to get metadata for " + youtube_id)
ValueError: failed to get metadata for Ug9ZGo8ki7E
[2024-11-04 05:34:37,362: WARNING/ForkPoolWorker-8] 90faa7e5-2391-4fc4-8a08-fa67c15dff22 return callback
```

So I went and looked for the file:
```
root@cluserboi /m/s/YouTube# find . -name "*Ug9ZGo8ki7E*"
./UCrGuRVn653ZjCTrW28teNRg/Ug9ZGo8ki7E.mp4
root@cluserboi /m/s/YouTube# file ./UCrGuRVn653ZjCTrW28teNRg/Ug9ZGo8ki7E.mp4
./UCrGuRVn653ZjCTrW28teNRg/Ug9ZGo8ki7E.mp4: ISO Media, MP4 Base Media v1 [ISO 14496-12:2003]
root@cluserboi /m/s/YouTube# mediainfo ./UCrGuRVn653ZjCTrW28teNRg/Ug9ZGo8ki7E.mp4
General
Complete name                            : ./UCrGuRVn653ZjCTrW28teNRg/Ug9ZGo8ki7E.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 15.2 MiB
Duration                                 : 1 min 59 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 061 kb/s
Frame rate                               : 25.000 FPS
Movie name                               : DLC - Emil - Drakengard 3 Original Soundtrack
Performer                                : stek
Recorded date                            : 20230415
Writing application                      : Lavf60.4.101
Cover                                    : Yes
Comment                                  : https://www.youtube.com/watch?v=Ug9ZGo8ki7E

Video
ID                                       : 1
Format                                   : vp09
Codec ID                                 : vp09
Duration                                 : 1 min 59 s
Bit rate                                 : 919 kb/s
Width                                    : 1 888 pixels
Height                                   : 1 830 pixels
Display aspect ratio                     : 1.032
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Bits/(Pixel*Frame)                       : 0.011
Stream size                              : 13.1 MiB (87%)
Language                                 : English
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : Opus
Duration                                 : 1 min 59 s
Duration_FirstFrame                      : 1 ms
Bit rate mode                            : Variable
Bit rate                                 : 131 kb/s
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 1.87 MiB (12%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
```

I bet the viddy's just gone... x)

## Steps To Reproduce
- Create new TA instance (deployment below)
  * Ensure it has access to a pre-populated `/youtube` directory!
- Settings -> Actions -> Rescan filesystem

## Expected behavior

I expected - or rather hoped - that it would reproduce my old channel subscriptions off of the file structure. It does not, unfortunately.

### Relevant log output

```shell
(( This was my first attempt - hence more output. The other was my second, so the logs were shorter. ))

[2024-11-04 05:33:05,621: WARNING/ForkPoolWorker-8] UC3OvESMThc9sA0MzZwkpmhg: get metadata from es
[2024-11-04 05:33:05,630: WARNING/ForkPoolWorker-8] {"_index":"ta_channel","_id":"UC3OvESMThc9sA0MzZwkpmhg","found":false}
[2024-11-04 05:33:05,630: WARNING/ForkPoolWorker-8] UC3OvESMThc9sA0MzZwkpmhg: get metadata from youtube
[2024-11-04 05:33:06,892: WARNING/ForkPoolWorker-8] WARNING: [youtube] bucHz8LF6no: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 9IVJ3omi27G4CUlgn ; player = https://www.youtube.com/s/player/4e23410d/player_ias.vflset/en_US/base.js
[2024-11-04 05:33:07,795: WARNING/ForkPoolWorker-8] UC3OvESMThc9sA0MzZwkpmhg: download channel thumbnail
[2024-11-04 05:33:14,378: WARNING/ForkPoolWorker-8] Ug9ZGo8ki7E: get metadata from youtube
[2024-11-04 05:33:14,870: WARNING/ForkPoolWorker-8] ERROR: [youtube] Ug9ZGo8ki7E: Video unavailable. This video is no longer available due to a copyright claim by Square Enix Co., Ltd.
[2024-11-04 05:33:14,870: WARNING/ForkPoolWorker-8] https://www.youtube.com/watch?v=Ug9ZGo8ki7E: failed to get info from youtube with message ERROR: [youtube] Ug9ZGo8ki7E: Video unavailable. This video is no longer available due to a copyright claim by Square Enix Co., Ltd.
[2024-11-04 05:33:14,877: WARNING/ForkPoolWorker-8] a5f8ad12-d67e-4438-8438-6199fafc862a Failed callback
[2024-11-04 05:33:14,883: ERROR/ForkPoolWorker-8] Task rescan_filesystem[a5f8ad12-d67e-4438-8438-6199fafc862a] raised unexpected: ValueError('failed to get metadata for Ug9ZGo8ki7E')
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 264, in rescan_filesystem
    handler.apply()
  File "/app/home/src/index/filesystem.py", line 58, in apply
    self.index()
  File "/app/home/src/index/filesystem.py", line 90, in index
    index_new_video(youtube_id)
  File "/app/home/src/index/video.py", line 400, in index_new_video
    raise ValueError("failed to get metadata for " + youtube_id)
ValueError: failed to get metadata for Ug9ZGo8ki7E
[2024-11-04 05:33:14,885: WARNING/ForkPoolWorker-8] a5f8ad12-d67e-4438-8438-6199fafc862a return callback
```

### Anything else?

Here's the whole deployment.

Make sure to change the `TA_HOST`, `TA_USERNAME`, `TA_PASSWORD`, `ELASTIC_PASSWORD` in the TA deployment and `ELASTIC_PASSWORD` in the ElasticSearch one. In the future I'll try and see if I can possibly abuse something like Cert-Manager to generate something nice. x)
The PV/PVC at the top just help me bind my NAS - it's a copypasta I use in another deployment to share the same PVC across deployments without needing to copypasta into `volumeMounts` should I ever need to adjust the IP or path.
Also, swap the Traefik ingress for your prefered method.

<details>

<summary>TubeArchivist k3s Deployment</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tubearchivist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ta-direct-pv
  namespace: tubearchivist
  labels:
    store: bunker
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Ti
  nfs:
    server: 192.168.X.X # FILL ME
    path: /path/to/youtube/folder # FILL ME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ta-direct-pvc
  namespace: tubearchivist
spec:
  # Hack: This allows to directly link PV and PVC which makes the PVC act as a neat proxy into the NFS!
  # It also makes it easier to share across deployments.
  storageClassName: ""
  selector:
    matchLabels:
      store: bunker
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ta-cache-pvc
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
  namespace: tubearchivist
spec:
  storageClassName: "nfs-bunker"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack-app
  namespace: tubearchivist
  labels:
    app: redis-stack
spec:
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      volumes:
        - name: redis-data-vol
          persistentVolumeClaim:
            claimName: redis-data-pvc
      containers:
        - name: app
          image: "redis/redis-stack-server:latest"
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data-vol
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack-svc
  namespace: tubearchivist
spec:
  type: ClusterIP
  selector:
    app: redis-stack
  ports:
    - targetPort: redis
      name: redis
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-app
  namespace: tubearchivist
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-data-vol
          persistentVolumeClaim:
            claimName: elasticsearch-data-pvc
      containers:
        - name: app
          image: "elasticsearch:8.14.3"
          env:
            # TODO: Turn into Secret to share between deployments
            - name: ELASTIC_PASSWORD
              value: "" # FILL ME
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: xpack.security.enabled
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: path.repo
              value: "/usr/share/elasticsearch/data/snapshot"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9200
              name: es
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data-vol
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: tubearchivist
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - targetPort: es
      name: es
      port: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta-app
  namespace: tubearchivist
  labels:
    app: tubearchivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubearchivist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      volumes:
        - name: ta-cache-vol
          persistentVolumeClaim:
            claimName: ta-cache-pvc
        - name: ta-direct-vol
          persistentVolumeClaim:
            claimName: ta-direct-pvc
      initContainers:
        - name: wait-for-redis
          image: cgr.dev/chainguard/wait-for-it:latest
          args: ["-h", "redis-stack-svc", "-p", "6379", "-t", "60"]
        - name: wait-for-es
          image: cgr.dev/chainguard/wait-for-it:latest
          args: ["-h", "elasticsearch-svc", "-p", "9200", "-t", "60"]
      containers:
        - name: app
          image: "bbilly1/tubearchivist:latest"
          imagePullPolicy: Always
          env:
            - name: ES_URL
              value: "http://elasticsearch-svc:9200"
            - name: REDIS_HOST
              value: "redis-stack-svc"
            - name: HOST_UID
              value: "1000"
            - name: HOST_GID
              value: "1000"
            - name: TA_HOST
              value: "https://tube-archivist.your-domain.tld" # FILL ME
            - name: TA_USERNAME
              value: "" # FILL ME
            - name: TA_PASSWORD
              value: "" # FILL ME
            - name: ELASTIC_PASSWORD
              value: "" # FILL ME
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 8000
              name: webui
              protocol: TCP
          volumeMounts:
            - mountPath: /cache
              name: ta-cache-vol
            - mountPath: /youtube
              name: ta-direct-vol
---
apiVersion: v1
kind: Service
metadata:
  name: ta-svc
  namespace: tubearchivist
spec:
  type: ClusterIP
  ports:
    - targetPort: webui
      port: 8000
      name: webui
  selector:
    app: tubearchivist
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ta-tr
  namespace: tubearchivist
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tube-archivist.your-domain.tld`)
      kind: Rule
      services:
        - name: ta-svc
          port: webui
```

</details>

**Comment by bbilly1** [comment]
Duplicate: #769 with more details.

On a side note, that is also a good opportunity to implement a proper backup solution.
