### ISSUE TITLE
[Bug]: Unable to subscribe to channel : Unable to extract yt data

### ISSUE THREAD

**Issue by Eclegv** [tubearchivist/tubearchivist#833]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian 12

## Describe the bug

I tought it was similar to the issue#795, but the logs seems quite different, so I prefered to open a ticket.

I was adding channel to download their video and suddenly, I was unable to add any new channel.

I did some tests with a friend that added the same channel as me, and, there was no bug for him. We used the same version 4.11

## Steps To Reproduce

Add any of those channels :
 - https://www.youtube.com/@ggmilgram
 - https://www.youtube.com/@alanbecker

## Expected behavior

Channel should be added and videos put in queue

### Relevant log output

```shell
tubearchivist  | [2024-11-09 16:11:58,592: INFO/MainProcess] Task subscribe_to[367b85c4-43a0-4787-ba51-2ca6693e12fe] received
tubearchivist  | [2024-11-09 16:11:58,593: WARNING/ForkPoolWorker-32] subscribe_to create callback
tubearchivist  | [2024-11-09 16:11:59,119: WARNING/ForkPoolWorker-32] UCAoUBng0Mfu0qn4lPimS6MA: get metadata from es
tubearchivist  | [2024-11-09 16:11:59,128: WARNING/ForkPoolWorker-32] {"_index":"ta_channel","_id":"UCAoUBng0Mfu0qn4lPimS6MA","found":false}
tubearchivist  | [2024-11-09 16:11:59,129: WARNING/ForkPoolWorker-32] UCAoUBng0Mfu0qn4lPimS6MA: get metadata from youtube
tubearchivist  | [2024-11-09 16:11:59,470: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-11-09 16:11:59,471: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
tubearchivist  | [2024-11-09 16:11:59,601: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-11-09 16:11:59,601: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
tubearchivist  | [2024-11-09 16:11:59,703: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-11-09 16:11:59,704: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
tubearchivist  | [2024-11-09 16:11:59,814: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
tubearchivist  | [2024-11-09 16:11:59,814: WARNING/ForkPoolWorker-32] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
tubearchivist  | [2024-11-09 16:11:59,819: WARNING/ForkPoolWorker-32] ERROR: [youtube:tab] UCAoUBng0Mfu0qn4lPimS6MA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-11-09 16:11:59,819: WARNING/ForkPoolWorker-32] https://www.youtube.com/channel/UCAoUBng0Mfu0qn4lPimS6MA: failed to get info from youtube with message ERROR: [youtube:tab] UCAoUBng0Mfu0qn4lPimS6MA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
tubearchivist  | [2024-11-09 16:11:59,824: WARNING/ForkPoolWorker-32] 367b85c4-43a0-4787-ba51-2ca6693e12fe Failed callback
tubearchivist  | [2024-11-09 16:11:59,826: ERROR/ForkPoolWorker-32] Task subscribe_to[367b85c4-43a0-4787-ba51-2ca6693e12fe] raised unexpected: TypeError("'bool' object is not subscriptable")
tubearchivist  | Traceback (most recent call last):
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
tubearchivist  |     R = retval = fun(*args, **kwargs)
tubearchivist  |                  ^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
tubearchivist  |     return self.run(*args, **kwargs)
tubearchivist  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist  |   File "/app/home/tasks.py", line 302, in subscribe_to
tubearchivist  |     SubscriptionHandler(url_str, task=self).subscribe(expected_type)
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 392, in subscribe
tubearchivist  |     self.subscribe_type(item, expected_type=expected_type)
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 421, in subscribe_type
tubearchivist  |     self._subscribe(channel_id)
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 425, in _subscribe
tubearchivist  |     ChannelSubscription().change_subscribe(
tubearchivist  |   File "/app/home/src/download/subscriptions.py", line 118, in change_subscribe
tubearchivist  |     channel.build_json()
tubearchivist  |   File "/app/home/src/index/channel.py", line 45, in build_json
tubearchivist  |     self.process_youtube_meta()
tubearchivist  |   File "/app/home/src/index/channel.py", line 53, in process_youtube_meta
tubearchivist  |     self.youtube_meta["thumbnails"].reverse()
tubearchivist  |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
tubearchivist  | TypeError: 'bool' object is not subscriptable
tubearchivist  | [2024-11-09 16:11:59,827: WARNING/ForkPoolWorker-32] 367b85c4-43a0-4787-ba51-2ca6693e12fe return callback
```

**Comment by bbilly1** [comment]
You are getting blocked by YT. See FAQ here: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled

**Comment by Eclegv** [comment]
Yup !
I refreshed my cookies and it worked again. Sorry, I didn't saw the post in the FAQ.
