### ISSUE TITLE
[Installation]: using Dragonfly cluster IP for redis_host

### ISSUE THREAD

**Issue by mrugges** [tubearchivist/tubearchivist#849]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Docker

### Your installation or setup question

Installation works fine if I am pointing to a redis host running in a local docker compose service. However if I try to point it to an externally hosted IP of a dragonfly cluster I get an interesting error.

### Relevant log output

```Shell
[1] connect to Redis

    ✓ Redis connection verified

[2] set Redis config

Traceback (most recent call last):

  File "/app/manage.py", line 23, in <module>

    main()

  File "/app/manage.py", line 19, in main

    execute_from_command_line(sys.argv)

  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line

    utility.execute()

  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/config/management/commands/ta_connection.py", line 37, in handle

    self._redis_config_set()

  File "/app/config/management/commands/ta_connection.py", line 69, in _redis_config_set

    timeout_is = int(redis_conn.config_get("timeout").get("timeout"))

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by bbilly1** [comment]
What you see failing is that it appears that there is no timeout value set in your redis cluster, that is set to 0 (zero) in a regular docker container. If you can set that, this might work. This project tries to set a sensible default at application start.

But ultimately:
- There is no expectation that this is going to work. 
- What this project expects and is developed with is as documented: A dedicated redis container.
- Also see the docs [here](https://docs.tubearchivist.com/installation/docker-compose/#redis) regarding sharing redis instances.
