### ISSUE TITLE
[Frontend Migration]: Handle bulk add from text field

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#851]
### Domain

Frontend

### Description

Text form can take multiple lines of items to add in bulk. The frontend should parse that first to a list before sending this to the API. 

- [x] Adding videos to the queue
- [x] Subscribing to channels
- [x] Subscribing to playlist

E.g. currently:

```json
{
  "data": [{
    "youtube_id": "https://www.youtube.com/watch?v=xxx\nhttps://www.youtube.com/watch?v=yyy",
    "status": "pending"
  }]
}
```

should be:
```json
{
  "data": [
    {
      "youtube_id": "https://www.youtube.com/watch?v=xxx",
      "status": "pending"
    },
    {
      "youtube_id": "https://www.youtube.com/watch?v=yyy",
      "status": "pending"
    }
  ]
}
```

The backend currently parses that by splitting the string, but that is not great restful design and a leftover from the old django frontend...

**Comment by MerlinScheurer** [comment]
Frontend part should work.
But there are errors in the logs:
```
tubearchivist    | [2024-12-27 11:31:12,899: ERROR/ForkPoolWorker-16] Task subscribe_to[7e832776-7987-4631-a650-f4c7633863a8] raised unexpected: ValueError('PL96C35uN7xGLr6zFFMabALFOFy6RnZhir: failed to extract data')
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
tubearchivist    |     R = retval = fun(*args, **kwargs)
tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
tubearchivist    |     return self.run(*args, **kwargs)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/task/tasks.py", line 299, in subscribe_to
tubearchivist    |     SubscriptionHandler(url_str, task=self).subscribe(expected_type)
tubearchivist    |   File "/app/download/src/subscriptions.py", line 392, in subscribe
tubearchivist    |     self.subscribe_type(item, expected_type=expected_type)
tubearchivist    |   File "/app/download/src/subscriptions.py", line 402, in subscribe_type
tubearchivist    |     PlaylistSubscription().process_url_str([item])
tubearchivist    |   File "/app/download/src/subscriptions.py", line 248, in process_url_str
tubearchivist    |     raise ValueError(message)
tubearchivist    | ValueError: PL96C35uN7xGLr6zFFMabALFOFy6RnZhir: failed to extract data
tubearchivist    | [2024-12-27 11:31:12,900: WARNING/ForkPoolWorker-16] 7e832776-7987-4631-a650-f4c7633863a8 return callback
```

```
tubearchivist    | [2024-12-27 11:25:38,250: ERROR/ForkPoolWorker-16] Task subscribe_to[32c0f20b-6184-402f-9aef-e33145374acd] raised unexpected: TypeError("'bool' object is not subscriptable")
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
tubearchivist    |     R = retval = fun(*args, **kwargs)
tubearchivist    |                  ^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
tubearchivist    |     return self.run(*args, **kwargs)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/task/tasks.py", line 299, in subscribe_to
tubearchivist    |     SubscriptionHandler(url_str, task=self).subscribe(expected_type)
tubearchivist    |   File "/app/download/src/subscriptions.py", line 392, in subscribe
tubearchivist    |     self.subscribe_type(item, expected_type=expected_type)
tubearchivist    |   File "/app/download/src/subscriptions.py", line 421, in subscribe_type
tubearchivist    |     self._subscribe(channel_id)
tubearchivist    |   File "/app/download/src/subscriptions.py", line 425, in _subscribe
tubearchivist    |     ChannelSubscription().change_subscribe(
tubearchivist    |   File "/app/download/src/subscriptions.py", line 118, in change_subscribe
tubearchivist    |     channel.build_json()
tubearchivist    |   File "/app/channel/src/index.py", line 45, in build_json
tubearchivist    |     self.process_youtube_meta()
tubearchivist    |   File "/app/channel/src/index.py", line 53, in process_youtube_meta
tubearchivist    |     self.youtube_meta["thumbnails"].reverse()
tubearchivist    |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
tubearchivist    | TypeError: 'bool' object is not subscriptable
tubearchivist    | [2024-12-27 11:25:38,250: WARNING/ForkPoolWorker-16] 32c0f20b-6184-402f-9aef-e33145374acd return callback
```

**Comment by bbilly1** [comment]
Hmm, works fine for me, sure you aren't getting blocked?

**Comment by MerlinScheurer** [comment]
Nevermind, it was because of `Unsupported language code: false.` 🤣 
Apparently my application config was messed up.
